// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.

package contracts

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/trakrai/device-services/internal/ipc"
)

const (
	AudioManagerService = "audio-manager"
	AudioManagerPlayAudioMethod = "play-audio"
	AudioManagerPlayAudioSubtopic = "command"
	AudioManagerGetJobMethod = "get-job"
	AudioManagerGetJobSubtopic = "command"
	AudioManagerListJobsMethod = "list-jobs"
	AudioManagerListJobsSubtopic = "command"
	AudioManagerGetStatusMethod = "get-status"
	AudioManagerGetStatusSubtopic = "command"
	AudioManagerJobMessage = "audio-manager-job"
	AudioManagerResultMessage = "audio-manager-result"
	AudioManagerListMessage = "audio-manager-list"
	AudioManagerStatusMessage = "audio-manager-status"
	AudioManagerErrorMessage = "audio-manager-error"
)

type AudioManagerAudioStats struct {
	Completed int `json:"completed"`
	Deduped int `json:"deduped"`
	Failed int `json:"failed"`
	Processing int `json:"processing"`
	Queued int `json:"queued"`
	Total int `json:"total"`
}

type AudioManagerAudioJob struct {
	Id string `json:"id"`
	RequestId string `json:"requestId"`
	SourceService string `json:"sourceService"`
	Text string `json:"text"`
	Language string `json:"language"`
	PlayLocal bool `json:"playLocal"`
	PlaySpeaker bool `json:"playSpeaker"`
	SpeakerAddress string `json:"speakerAddress"`
	SpeakerMessageId string `json:"speakerMessageId"`
	SpeakerCode string `json:"speakerCode"`
	CameraId string `json:"cameraId"`
	CameraName string `json:"cameraName"`
	DedupeKey string `json:"dedupeKey"`
	State string `json:"state"`
	LocalState string `json:"localState"`
	SpeakerState string `json:"speakerState"`
	SpeakerPayload string `json:"speakerPayload"`
	AudioPath string `json:"audioPath"`
	Attempts int `json:"attempts"`
	Error string `json:"error"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	CompletedAt string `json:"completedAt"`
}

type AudioManagerAudioRequest struct {
	CameraId string `json:"cameraId,omitempty"`
	CameraName string `json:"cameraName,omitempty"`
	DedupeKey string `json:"dedupeKey,omitempty"`
	Language string `json:"language,omitempty"`
	Message string `json:"message,omitempty"`
	PlayLocal bool `json:"playLocal,omitempty"`
	PlaySpeaker bool `json:"playSpeaker,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	SpeakerAddress string `json:"speakerAddress,omitempty"`
	SpeakerCode string `json:"speakerCode,omitempty"`
	SpeakerMessageId string `json:"speakerMessageId,omitempty"`
	Text string `json:"text,omitempty"`
}

type AudioManagerGetJobRequest struct {
	JobId string `json:"jobId"`
	RequestId string `json:"requestId,omitempty"`
}

type AudioManagerListJobsRequest struct {
	Limit int `json:"limit,omitempty"`
	RequestId string `json:"requestId,omitempty"`
}

type AudioManagerStatusRequest struct {
	RequestId string `json:"requestId,omitempty"`
}

type AudioManagerAudioJobPayload struct {
	Job AudioManagerAudioJob `json:"job"`
	RequestId string `json:"requestId,omitempty"`
}

type AudioManagerAudioListPayload struct {
	Jobs []AudioManagerAudioJob `json:"jobs"`
	RequestId string `json:"requestId,omitempty"`
	Stats AudioManagerAudioStats `json:"stats"`
}

type AudioManagerAudioStatusPayload struct {
	CacheDir string `json:"cacheDir"`
	DeviceId string `json:"deviceId"`
	EventLogPath string `json:"eventLogPath"`
	PendingQueueDepth int `json:"pendingQueueDepth"`
	PlaybackBackend string `json:"playbackBackend"`
	RequestId string `json:"requestId,omitempty"`
	SpeakerEnabled bool `json:"speakerEnabled"`
	SpeakerTransport string `json:"speakerTransport"`
	StateDbPath string `json:"stateDbPath"`
	Stats AudioManagerAudioStats `json:"stats"`
	TtsBackend string `json:"ttsBackend"`
}

type AudioManagerAudioErrorPayload struct {
	Error string `json:"error"`
	RequestId string `json:"requestId,omitempty"`
	RequestType string `json:"requestType,omitempty"`
}

func ParseAudioManagerAudioStats(payload json.RawMessage) (AudioManagerAudioStats, error) {
	var decoded AudioManagerAudioStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseAudioManagerAudioJob(payload json.RawMessage) (AudioManagerAudioJob, error) {
	var decoded AudioManagerAudioJob
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseAudioManagerAudioRequest(payload json.RawMessage) (AudioManagerAudioRequest, error) {
	var decoded AudioManagerAudioRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseAudioManagerGetJobRequest(payload json.RawMessage) (AudioManagerGetJobRequest, error) {
	var decoded AudioManagerGetJobRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseAudioManagerListJobsRequest(payload json.RawMessage) (AudioManagerListJobsRequest, error) {
	var decoded AudioManagerListJobsRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseAudioManagerStatusRequest(payload json.RawMessage) (AudioManagerStatusRequest, error) {
	var decoded AudioManagerStatusRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseAudioManagerAudioJobPayload(payload json.RawMessage) (AudioManagerAudioJobPayload, error) {
	var decoded AudioManagerAudioJobPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseAudioManagerAudioListPayload(payload json.RawMessage) (AudioManagerAudioListPayload, error) {
	var decoded AudioManagerAudioListPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseAudioManagerAudioStatusPayload(payload json.RawMessage) (AudioManagerAudioStatusPayload, error) {
	var decoded AudioManagerAudioStatusPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseAudioManagerAudioErrorPayload(payload json.RawMessage) (AudioManagerAudioErrorPayload, error) {
	var decoded AudioManagerAudioErrorPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

type AudioManagerHandler interface {
	HandlePlayAudio(ctx context.Context, sourceService string, request AudioManagerAudioRequest) error
	HandleGetJob(ctx context.Context, sourceService string, request AudioManagerGetJobRequest) error
	HandleListJobs(ctx context.Context, sourceService string, request AudioManagerListJobsRequest) error
	HandleGetStatus(ctx context.Context, sourceService string, request AudioManagerStatusRequest) error
}

func DispatchAudioManager(ctx context.Context, sourceService string, subtopic string, env ipc.MQTTEnvelope, handler AudioManagerHandler) (bool, error) {
	normalizedSubtopic := strings.Trim(strings.TrimSpace(subtopic), "/")
	normalizedType := strings.TrimSpace(env.Type)
	switch normalizedSubtopic {
	case "command":
		switch normalizedType {
		case AudioManagerPlayAudioMethod:
			request, err := ParseAudioManagerAudioRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode play-audio: %w", err)
			}
			return true, handler.HandlePlayAudio(ctx, sourceService, request)
		case AudioManagerGetJobMethod:
			request, err := ParseAudioManagerGetJobRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-job: %w", err)
			}
			return true, handler.HandleGetJob(ctx, sourceService, request)
		case AudioManagerListJobsMethod:
			request, err := ParseAudioManagerListJobsRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode list-jobs: %w", err)
			}
			return true, handler.HandleListJobs(ctx, sourceService, request)
		case AudioManagerGetStatusMethod:
			request, err := ParseAudioManagerStatusRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-status: %w", err)
			}
			return true, handler.HandleGetStatus(ctx, sourceService, request)
		default:
			return false, nil
		}
	default:
		return false, nil
	}
}

type AudioManagerClient struct {
	ipcClient *ipc.Client
	responseRouter *ipc.ResponseRouter
	targetService string
}

func NewAudioManagerClient(ipcClient *ipc.Client, responseRouter *ipc.ResponseRouter, targetService string) *AudioManagerClient {
	if strings.TrimSpace(targetService) == "" {
		targetService = AudioManagerService
	}
	return &AudioManagerClient{
		ipcClient: ipcClient,
		responseRouter: responseRouter,
		targetService: strings.TrimSpace(targetService),
	}
}

func (c *AudioManagerClient) PlayAudio(ctx context.Context, request AudioManagerAudioRequest) (AudioManagerAudioJobPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, AudioManagerPlayAudioMethod, request)
	if err != nil {
		return AudioManagerAudioJobPayload{}, err
	}
	return DecodeAudioManagerPlayAudioResponse(message)
}

func DecodeAudioManagerPlayAudioResponse(message ipc.ServiceMessageNotification) (AudioManagerAudioJobPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case AudioManagerJobMessage:
		return ParseAudioManagerAudioJobPayload(message.Envelope.Payload)
	case AudioManagerErrorMessage:
		errorPayload, err := ParseAudioManagerAudioErrorPayload(message.Envelope.Payload)
		if err != nil {
			return AudioManagerAudioJobPayload{}, err
		}
		return AudioManagerAudioJobPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return AudioManagerAudioJobPayload{}, fmt.Errorf("unexpected play-audio response type %q", message.Envelope.Type)
	}
}

func (c *AudioManagerClient) GetJob(ctx context.Context, request AudioManagerGetJobRequest) (AudioManagerAudioJobPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, AudioManagerGetJobMethod, request)
	if err != nil {
		return AudioManagerAudioJobPayload{}, err
	}
	return DecodeAudioManagerGetJobResponse(message)
}

func DecodeAudioManagerGetJobResponse(message ipc.ServiceMessageNotification) (AudioManagerAudioJobPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case AudioManagerJobMessage:
		return ParseAudioManagerAudioJobPayload(message.Envelope.Payload)
	case AudioManagerErrorMessage:
		errorPayload, err := ParseAudioManagerAudioErrorPayload(message.Envelope.Payload)
		if err != nil {
			return AudioManagerAudioJobPayload{}, err
		}
		return AudioManagerAudioJobPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return AudioManagerAudioJobPayload{}, fmt.Errorf("unexpected get-job response type %q", message.Envelope.Type)
	}
}

func (c *AudioManagerClient) ListJobs(ctx context.Context, request AudioManagerListJobsRequest) (AudioManagerAudioListPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, AudioManagerListJobsMethod, request)
	if err != nil {
		return AudioManagerAudioListPayload{}, err
	}
	return DecodeAudioManagerListJobsResponse(message)
}

func DecodeAudioManagerListJobsResponse(message ipc.ServiceMessageNotification) (AudioManagerAudioListPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case AudioManagerListMessage:
		return ParseAudioManagerAudioListPayload(message.Envelope.Payload)
	default:
		return AudioManagerAudioListPayload{}, fmt.Errorf("unexpected list-jobs response type %q", message.Envelope.Type)
	}
}

func (c *AudioManagerClient) GetStatus(ctx context.Context, request AudioManagerStatusRequest) (AudioManagerAudioStatusPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, AudioManagerGetStatusMethod, request)
	if err != nil {
		return AudioManagerAudioStatusPayload{}, err
	}
	return DecodeAudioManagerGetStatusResponse(message)
}

func DecodeAudioManagerGetStatusResponse(message ipc.ServiceMessageNotification) (AudioManagerAudioStatusPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case AudioManagerStatusMessage:
		return ParseAudioManagerAudioStatusPayload(message.Envelope.Payload)
	default:
		return AudioManagerAudioStatusPayload{}, fmt.Errorf("unexpected get-status response type %q", message.Envelope.Type)
	}
}
