// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.

package contracts

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/trakrai/device-services/internal/ipc"
)

const (
	CloudTransferService = "cloud-transfer"
	CloudTransferEnqueueUploadMethod = "enqueue-upload"
	CloudTransferEnqueueUploadSubtopic = "command"
	CloudTransferEnqueueDownloadMethod = "enqueue-download"
	CloudTransferEnqueueDownloadSubtopic = "command"
	CloudTransferGetTransferMethod = "get-transfer"
	CloudTransferGetTransferSubtopic = "command"
	CloudTransferListTransfersMethod = "list-transfers"
	CloudTransferListTransfersSubtopic = "command"
	CloudTransferGetStatsMethod = "get-stats"
	CloudTransferGetStatsSubtopic = "command"
	CloudTransferGetStatusMethod = "get-status"
	CloudTransferGetStatusSubtopic = "command"
	CloudTransferTransferMessage = "cloud-transfer-transfer"
	CloudTransferListMessage = "cloud-transfer-list"
	CloudTransferStatsMessage = "cloud-transfer-stats"
	CloudTransferStatusMessage = "cloud-transfer-status"
	CloudTransferErrorMessage = "cloud-transfer-error"
)

type CloudTransferQueueStats struct {
	Completed int `json:"completed"`
	DownloadQueued int `json:"downloadQueued"`
	DownloadsCompleted int `json:"downloadsCompleted"`
	DownloadsFailed int `json:"downloadsFailed"`
	Failed int `json:"failed"`
	NextAttemptAt string `json:"nextAttemptAt,omitempty"`
	Pending int `json:"pending"`
	Running int `json:"running"`
	Total int `json:"total"`
	UploadQueued int `json:"uploadQueued"`
	UploadsCompleted int `json:"uploadsCompleted"`
	UploadsFailed int `json:"uploadsFailed"`
}

type CloudTransferTransfer struct {
	Attempts int `json:"attempts"`
	CompletedAt string `json:"completedAt,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	CreatedAt string `json:"createdAt"`
	DeadlineAt string `json:"deadlineAt,omitempty"`
	DeviceId string `json:"deviceId"`
	Direction string `json:"direction"`
	Id string `json:"id"`
	LastError string `json:"lastError,omitempty"`
	LocalPath string `json:"localPath"`
	Metadata map[string]string `json:"metadata,omitempty"`
	NextAttemptAt string `json:"nextAttemptAt,omitempty"`
	ObjectKey string `json:"objectKey,omitempty"`
	RemotePath string `json:"remotePath"`
	Scope string `json:"scope,omitempty"`
	StartedAt string `json:"startedAt,omitempty"`
	State string `json:"state"`
	UpdatedAt string `json:"updatedAt"`
}

type CloudTransferTransferMetadata map[string]string

type CloudTransferEnqueueUploadRequest struct {
	ContentType string `json:"contentType,omitempty"`
	LocalPath string `json:"localPath"`
	Metadata map[string]string `json:"metadata,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	RemotePath string `json:"remotePath"`
	Scope string `json:"scope,omitempty"`
	Timeout string `json:"timeout,omitempty"`
}

type CloudTransferEnqueueUploadRequestMetadata map[string]string

type CloudTransferEnqueueDownloadRequest struct {
	LocalPath string `json:"localPath"`
	Metadata map[string]string `json:"metadata,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	RemotePath string `json:"remotePath"`
	Scope string `json:"scope,omitempty"`
	Timeout string `json:"timeout,omitempty"`
}

type CloudTransferEnqueueDownloadRequestMetadata map[string]string

type CloudTransferGetTransferRequest struct {
	RequestId string `json:"requestId,omitempty"`
	TransferId string `json:"transferId"`
}

type CloudTransferListTransfersRequest struct {
	Direction string `json:"direction,omitempty"`
	Limit int `json:"limit,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	State string `json:"state,omitempty"`
}

type CloudTransferStatsRequest struct {
	RequestId string `json:"requestId,omitempty"`
}

type CloudTransferTransferPayload struct {
	RequestId string `json:"requestId,omitempty"`
	Transfer CloudTransferTransfer `json:"transfer"`
}

type CloudTransferTransferListPayload struct {
	Items []CloudTransferTransfer `json:"items"`
	RequestId string `json:"requestId,omitempty"`
}

type CloudTransferTransferStatsPayload struct {
	RequestId string `json:"requestId,omitempty"`
	Stats CloudTransferQueueStats `json:"stats"`
}

type CloudTransferTransferStatusPayload struct {
	DatabasePath string `json:"databasePath"`
	DeviceId string `json:"deviceId"`
	RequestId string `json:"requestId,omitempty"`
	SharedDir string `json:"sharedDir"`
	Stats CloudTransferQueueStats `json:"stats"`
}

type CloudTransferTransferErrorPayload struct {
	Error string `json:"error"`
	RequestId string `json:"requestId,omitempty"`
	RequestType string `json:"requestType,omitempty"`
}

func ParseCloudTransferQueueStats(payload json.RawMessage) (CloudTransferQueueStats, error) {
	var decoded CloudTransferQueueStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferTransfer(payload json.RawMessage) (CloudTransferTransfer, error) {
	var decoded CloudTransferTransfer
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferEnqueueUploadRequest(payload json.RawMessage) (CloudTransferEnqueueUploadRequest, error) {
	var decoded CloudTransferEnqueueUploadRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferEnqueueDownloadRequest(payload json.RawMessage) (CloudTransferEnqueueDownloadRequest, error) {
	var decoded CloudTransferEnqueueDownloadRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferGetTransferRequest(payload json.RawMessage) (CloudTransferGetTransferRequest, error) {
	var decoded CloudTransferGetTransferRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferListTransfersRequest(payload json.RawMessage) (CloudTransferListTransfersRequest, error) {
	var decoded CloudTransferListTransfersRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferStatsRequest(payload json.RawMessage) (CloudTransferStatsRequest, error) {
	var decoded CloudTransferStatsRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferTransferPayload(payload json.RawMessage) (CloudTransferTransferPayload, error) {
	var decoded CloudTransferTransferPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferTransferListPayload(payload json.RawMessage) (CloudTransferTransferListPayload, error) {
	var decoded CloudTransferTransferListPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferTransferStatsPayload(payload json.RawMessage) (CloudTransferTransferStatsPayload, error) {
	var decoded CloudTransferTransferStatsPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferTransferStatusPayload(payload json.RawMessage) (CloudTransferTransferStatusPayload, error) {
	var decoded CloudTransferTransferStatusPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseCloudTransferTransferErrorPayload(payload json.RawMessage) (CloudTransferTransferErrorPayload, error) {
	var decoded CloudTransferTransferErrorPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

type CloudTransferHandler interface {
	HandleEnqueueUpload(ctx context.Context, sourceService string, request CloudTransferEnqueueUploadRequest) error
	HandleEnqueueDownload(ctx context.Context, sourceService string, request CloudTransferEnqueueDownloadRequest) error
	HandleGetTransfer(ctx context.Context, sourceService string, request CloudTransferGetTransferRequest) error
	HandleListTransfers(ctx context.Context, sourceService string, request CloudTransferListTransfersRequest) error
	HandleGetStats(ctx context.Context, sourceService string, request CloudTransferStatsRequest) error
	HandleGetStatus(ctx context.Context, sourceService string, request CloudTransferStatsRequest) error
}

func DispatchCloudTransfer(ctx context.Context, sourceService string, subtopic string, env ipc.MQTTEnvelope, handler CloudTransferHandler) (bool, error) {
	normalizedSubtopic := strings.Trim(strings.TrimSpace(subtopic), "/")
	normalizedType := strings.TrimSpace(env.Type)
	switch normalizedSubtopic {
	case "command":
		switch normalizedType {
		case CloudTransferEnqueueUploadMethod:
			request, err := ParseCloudTransferEnqueueUploadRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode enqueue-upload: %w", err)
			}
			return true, handler.HandleEnqueueUpload(ctx, sourceService, request)
		case CloudTransferEnqueueDownloadMethod:
			request, err := ParseCloudTransferEnqueueDownloadRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode enqueue-download: %w", err)
			}
			return true, handler.HandleEnqueueDownload(ctx, sourceService, request)
		case CloudTransferGetTransferMethod:
			request, err := ParseCloudTransferGetTransferRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-transfer: %w", err)
			}
			return true, handler.HandleGetTransfer(ctx, sourceService, request)
		case CloudTransferListTransfersMethod:
			request, err := ParseCloudTransferListTransfersRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode list-transfers: %w", err)
			}
			return true, handler.HandleListTransfers(ctx, sourceService, request)
		case CloudTransferGetStatsMethod:
			request, err := ParseCloudTransferStatsRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-stats: %w", err)
			}
			return true, handler.HandleGetStats(ctx, sourceService, request)
		case CloudTransferGetStatusMethod:
			request, err := ParseCloudTransferStatsRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-status: %w", err)
			}
			return true, handler.HandleGetStatus(ctx, sourceService, request)
		default:
			return false, nil
		}
	default:
		return false, nil
	}
}

type CloudTransferClient struct {
	ipcClient *ipc.Client
	responseRouter *ipc.ResponseRouter
	targetService string
}

func NewCloudTransferClient(ipcClient *ipc.Client, responseRouter *ipc.ResponseRouter, targetService string) *CloudTransferClient {
	if strings.TrimSpace(targetService) == "" {
		targetService = CloudTransferService
	}
	return &CloudTransferClient{
		ipcClient: ipcClient,
		responseRouter: responseRouter,
		targetService: strings.TrimSpace(targetService),
	}
}

func (c *CloudTransferClient) EnqueueUpload(ctx context.Context, request CloudTransferEnqueueUploadRequest) (CloudTransferTransferPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, CloudTransferEnqueueUploadMethod, request)
	if err != nil {
		return CloudTransferTransferPayload{}, err
	}
	return DecodeCloudTransferEnqueueUploadResponse(message)
}

func DecodeCloudTransferEnqueueUploadResponse(message ipc.ServiceMessageNotification) (CloudTransferTransferPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case CloudTransferTransferMessage:
		return ParseCloudTransferTransferPayload(message.Envelope.Payload)
	case CloudTransferErrorMessage:
		errorPayload, err := ParseCloudTransferTransferErrorPayload(message.Envelope.Payload)
		if err != nil {
			return CloudTransferTransferPayload{}, err
		}
		return CloudTransferTransferPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return CloudTransferTransferPayload{}, fmt.Errorf("unexpected enqueue-upload response type %q", message.Envelope.Type)
	}
}

func (c *CloudTransferClient) EnqueueDownload(ctx context.Context, request CloudTransferEnqueueDownloadRequest) (CloudTransferTransferPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, CloudTransferEnqueueDownloadMethod, request)
	if err != nil {
		return CloudTransferTransferPayload{}, err
	}
	return DecodeCloudTransferEnqueueDownloadResponse(message)
}

func DecodeCloudTransferEnqueueDownloadResponse(message ipc.ServiceMessageNotification) (CloudTransferTransferPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case CloudTransferTransferMessage:
		return ParseCloudTransferTransferPayload(message.Envelope.Payload)
	case CloudTransferErrorMessage:
		errorPayload, err := ParseCloudTransferTransferErrorPayload(message.Envelope.Payload)
		if err != nil {
			return CloudTransferTransferPayload{}, err
		}
		return CloudTransferTransferPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return CloudTransferTransferPayload{}, fmt.Errorf("unexpected enqueue-download response type %q", message.Envelope.Type)
	}
}

func (c *CloudTransferClient) GetTransfer(ctx context.Context, request CloudTransferGetTransferRequest) (CloudTransferTransferPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, CloudTransferGetTransferMethod, request)
	if err != nil {
		return CloudTransferTransferPayload{}, err
	}
	return DecodeCloudTransferGetTransferResponse(message)
}

func DecodeCloudTransferGetTransferResponse(message ipc.ServiceMessageNotification) (CloudTransferTransferPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case CloudTransferTransferMessage:
		return ParseCloudTransferTransferPayload(message.Envelope.Payload)
	case CloudTransferErrorMessage:
		errorPayload, err := ParseCloudTransferTransferErrorPayload(message.Envelope.Payload)
		if err != nil {
			return CloudTransferTransferPayload{}, err
		}
		return CloudTransferTransferPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return CloudTransferTransferPayload{}, fmt.Errorf("unexpected get-transfer response type %q", message.Envelope.Type)
	}
}

func (c *CloudTransferClient) ListTransfers(ctx context.Context, request CloudTransferListTransfersRequest) (CloudTransferTransferListPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, CloudTransferListTransfersMethod, request)
	if err != nil {
		return CloudTransferTransferListPayload{}, err
	}
	return DecodeCloudTransferListTransfersResponse(message)
}

func DecodeCloudTransferListTransfersResponse(message ipc.ServiceMessageNotification) (CloudTransferTransferListPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case CloudTransferListMessage:
		return ParseCloudTransferTransferListPayload(message.Envelope.Payload)
	case CloudTransferErrorMessage:
		errorPayload, err := ParseCloudTransferTransferErrorPayload(message.Envelope.Payload)
		if err != nil {
			return CloudTransferTransferListPayload{}, err
		}
		return CloudTransferTransferListPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return CloudTransferTransferListPayload{}, fmt.Errorf("unexpected list-transfers response type %q", message.Envelope.Type)
	}
}

func (c *CloudTransferClient) GetStats(ctx context.Context, request CloudTransferStatsRequest) (CloudTransferTransferStatsPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, CloudTransferGetStatsMethod, request)
	if err != nil {
		return CloudTransferTransferStatsPayload{}, err
	}
	return DecodeCloudTransferGetStatsResponse(message)
}

func DecodeCloudTransferGetStatsResponse(message ipc.ServiceMessageNotification) (CloudTransferTransferStatsPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case CloudTransferStatsMessage:
		return ParseCloudTransferTransferStatsPayload(message.Envelope.Payload)
	case CloudTransferErrorMessage:
		errorPayload, err := ParseCloudTransferTransferErrorPayload(message.Envelope.Payload)
		if err != nil {
			return CloudTransferTransferStatsPayload{}, err
		}
		return CloudTransferTransferStatsPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return CloudTransferTransferStatsPayload{}, fmt.Errorf("unexpected get-stats response type %q", message.Envelope.Type)
	}
}

func (c *CloudTransferClient) GetStatus(ctx context.Context, request CloudTransferStatsRequest) (CloudTransferTransferStatusPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, CloudTransferGetStatusMethod, request)
	if err != nil {
		return CloudTransferTransferStatusPayload{}, err
	}
	return DecodeCloudTransferGetStatusResponse(message)
}

func DecodeCloudTransferGetStatusResponse(message ipc.ServiceMessageNotification) (CloudTransferTransferStatusPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case CloudTransferStatusMessage:
		return ParseCloudTransferTransferStatusPayload(message.Envelope.Payload)
	case CloudTransferErrorMessage:
		errorPayload, err := ParseCloudTransferTransferErrorPayload(message.Envelope.Payload)
		if err != nil {
			return CloudTransferTransferStatusPayload{}, err
		}
		return CloudTransferTransferStatusPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return CloudTransferTransferStatusPayload{}, fmt.Errorf("unexpected get-status response type %q", message.Envelope.Type)
	}
}
