// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.

package contracts

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/trakrai/device-services/internal/ipc"
)

const (
	LiveFeedService = "live-feed"
	LiveFeedStartLiveMethod = "start-live"
	LiveFeedStartLiveSubtopic = "command"
	LiveFeedUpdateLiveLayoutMethod = "update-live-layout"
	LiveFeedUpdateLiveLayoutSubtopic = "command"
	LiveFeedStopLiveMethod = "stop-live"
	LiveFeedStopLiveSubtopic = "command"
	LiveFeedSdpAnswerMethod = "sdp-answer"
	LiveFeedSdpAnswerSubtopic = "webrtc/answer"
	LiveFeedIceCandidateMethod = "ice-candidate"
	LiveFeedIceCandidateSubtopic = "webrtc/ice"
	LiveFeedStartLiveAckMessage = "start-live-ack"
	LiveFeedSdpOfferMessage = "sdp-offer"
	LiveFeedLiveLayoutUpdatedMessage = "live-layout-updated"
	LiveFeedIceCandidateMessage = "ice-candidate"
)

type LiveFeedLiveLayoutRequest struct {
	Camera string `json:"camera,omitempty"`
	CameraName string `json:"cameraName,omitempty"`
	CameraNames []string `json:"cameraNames,omitempty"`
	FrameSource string `json:"frameSource,omitempty"`
	LayoutMode string `json:"layoutMode,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	SessionId string `json:"sessionId,omitempty"`
}

type LiveFeedStopLiveRequest struct {
	RequestId string `json:"requestId,omitempty"`
	SessionId string `json:"sessionId,omitempty"`
}

type LiveFeedSdpAnswerRequest struct {
	RequestId string `json:"requestId,omitempty"`
	Sdp string `json:"sdp"`
	SessionId string `json:"sessionId"`
}

type LiveFeedIceCandidateBody map[string]interface{}

type LiveFeedIceCandidateRequest struct {
	Candidate LiveFeedIceCandidateBody `json:"candidate"`
	RequestId string `json:"requestId,omitempty"`
	SessionId string `json:"sessionId"`
}

type LiveFeedStartLiveAckPayload struct {
	CameraName string `json:"cameraName"`
	Error string `json:"error,omitempty"`
	FrameSource string `json:"frameSource"`
	Ok bool `json:"ok"`
	RequestId string `json:"requestId,omitempty"`
	SessionId string `json:"sessionId"`
}

type LiveFeedSdpOfferPayload struct {
	CameraName string `json:"cameraName"`
	FrameSource string `json:"frameSource"`
	RequestId string `json:"requestId,omitempty"`
	Sdp string `json:"sdp"`
	SessionId string `json:"sessionId"`
}

type LiveFeedLiveLayoutUpdatedPayload struct {
	CameraName string `json:"cameraName"`
	CameraNames []string `json:"cameraNames"`
	FrameSource string `json:"frameSource"`
	LayoutMode string `json:"layoutMode"`
	RequestId string `json:"requestId"`
	SessionId string `json:"sessionId"`
}

type LiveFeedIceCandidateEventPayload struct {
	Candidate LiveFeedIceCandidateBody `json:"candidate"`
	Origin string `json:"origin"`
	RequestId string `json:"requestId,omitempty"`
	SessionId string `json:"sessionId"`
}

func ParseLiveFeedLiveLayoutRequest(payload json.RawMessage) (LiveFeedLiveLayoutRequest, error) {
	var decoded LiveFeedLiveLayoutRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseLiveFeedStopLiveRequest(payload json.RawMessage) (LiveFeedStopLiveRequest, error) {
	var decoded LiveFeedStopLiveRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseLiveFeedSdpAnswerRequest(payload json.RawMessage) (LiveFeedSdpAnswerRequest, error) {
	var decoded LiveFeedSdpAnswerRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseLiveFeedIceCandidateBody(payload json.RawMessage) (LiveFeedIceCandidateBody, error) {
	var decoded LiveFeedIceCandidateBody
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseLiveFeedIceCandidateRequest(payload json.RawMessage) (LiveFeedIceCandidateRequest, error) {
	var decoded LiveFeedIceCandidateRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseLiveFeedStartLiveAckPayload(payload json.RawMessage) (LiveFeedStartLiveAckPayload, error) {
	var decoded LiveFeedStartLiveAckPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseLiveFeedSdpOfferPayload(payload json.RawMessage) (LiveFeedSdpOfferPayload, error) {
	var decoded LiveFeedSdpOfferPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseLiveFeedLiveLayoutUpdatedPayload(payload json.RawMessage) (LiveFeedLiveLayoutUpdatedPayload, error) {
	var decoded LiveFeedLiveLayoutUpdatedPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseLiveFeedIceCandidateEventPayload(payload json.RawMessage) (LiveFeedIceCandidateEventPayload, error) {
	var decoded LiveFeedIceCandidateEventPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

type LiveFeedHandler interface {
	HandleStartLive(ctx context.Context, sourceService string, request LiveFeedLiveLayoutRequest) error
	HandleUpdateLiveLayout(ctx context.Context, sourceService string, request LiveFeedLiveLayoutRequest) error
	HandleStopLive(ctx context.Context, sourceService string, request LiveFeedStopLiveRequest) error
	HandleSdpAnswer(ctx context.Context, sourceService string, request LiveFeedSdpAnswerRequest) error
	HandleIceCandidate(ctx context.Context, sourceService string, request LiveFeedIceCandidateRequest) error
}

func DispatchLiveFeed(ctx context.Context, sourceService string, subtopic string, env ipc.MQTTEnvelope, handler LiveFeedHandler) (bool, error) {
	normalizedSubtopic := strings.Trim(strings.TrimSpace(subtopic), "/")
	normalizedType := strings.TrimSpace(env.Type)
	switch normalizedSubtopic {
	case "command":
		switch normalizedType {
		case LiveFeedStartLiveMethod, "start":
			request, err := ParseLiveFeedLiveLayoutRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode start-live: %w", err)
			}
			return true, handler.HandleStartLive(ctx, sourceService, request)
		case LiveFeedUpdateLiveLayoutMethod:
			request, err := ParseLiveFeedLiveLayoutRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode update-live-layout: %w", err)
			}
			return true, handler.HandleUpdateLiveLayout(ctx, sourceService, request)
		case LiveFeedStopLiveMethod, "stop":
			request, err := ParseLiveFeedStopLiveRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode stop-live: %w", err)
			}
			return true, handler.HandleStopLive(ctx, sourceService, request)
		default:
			return false, nil
		}
	case "webrtc/answer":
		switch normalizedType {
		case LiveFeedSdpAnswerMethod:
			request, err := ParseLiveFeedSdpAnswerRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode sdp-answer: %w", err)
			}
			return true, handler.HandleSdpAnswer(ctx, sourceService, request)
		default:
			return false, nil
		}
	case "webrtc/ice":
		switch normalizedType {
		case LiveFeedIceCandidateMethod:
			request, err := ParseLiveFeedIceCandidateRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode ice-candidate: %w", err)
			}
			return true, handler.HandleIceCandidate(ctx, sourceService, request)
		default:
			return false, nil
		}
	default:
		return false, nil
	}
}

type LiveFeedClient struct {
	ipcClient *ipc.Client
	responseRouter *ipc.ResponseRouter
	targetService string
}

func NewLiveFeedClient(ipcClient *ipc.Client, responseRouter *ipc.ResponseRouter, targetService string) *LiveFeedClient {
	if strings.TrimSpace(targetService) == "" {
		targetService = LiveFeedService
	}
	return &LiveFeedClient{
		ipcClient: ipcClient,
		responseRouter: responseRouter,
		targetService: strings.TrimSpace(targetService),
	}
}

func (c *LiveFeedClient) StartLive(ctx context.Context, request LiveFeedLiveLayoutRequest) (LiveFeedStartLiveAckPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, LiveFeedStartLiveMethod, request)
	if err != nil {
		return LiveFeedStartLiveAckPayload{}, err
	}
	return DecodeLiveFeedStartLiveResponse(message)
}

func DecodeLiveFeedStartLiveResponse(message ipc.ServiceMessageNotification) (LiveFeedStartLiveAckPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case LiveFeedStartLiveAckMessage:
		return ParseLiveFeedStartLiveAckPayload(message.Envelope.Payload)
	default:
		return LiveFeedStartLiveAckPayload{}, fmt.Errorf("unexpected start-live response type %q", message.Envelope.Type)
	}
}

func (c *LiveFeedClient) UpdateLiveLayout(ctx context.Context, request LiveFeedLiveLayoutRequest) (LiveFeedLiveLayoutUpdatedPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, LiveFeedUpdateLiveLayoutMethod, request)
	if err != nil {
		return LiveFeedLiveLayoutUpdatedPayload{}, err
	}
	return DecodeLiveFeedUpdateLiveLayoutResponse(message)
}

func DecodeLiveFeedUpdateLiveLayoutResponse(message ipc.ServiceMessageNotification) (LiveFeedLiveLayoutUpdatedPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case LiveFeedLiveLayoutUpdatedMessage:
		return ParseLiveFeedLiveLayoutUpdatedPayload(message.Envelope.Payload)
	default:
		return LiveFeedLiveLayoutUpdatedPayload{}, fmt.Errorf("unexpected update-live-layout response type %q", message.Envelope.Type)
	}
}
