// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.

package contracts

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/trakrai/device-services/internal/ipc"
)

const (
	PtzControlService = "ptz-control"
	PtzControlGetStatusMethod = "get-status"
	PtzControlGetStatusSubtopic = "command"
	PtzControlGetPositionMethod = "get-position"
	PtzControlGetPositionSubtopic = "command"
	PtzControlStartMoveMethod = "start-move"
	PtzControlStartMoveSubtopic = "command"
	PtzControlStopMoveMethod = "stop-move"
	PtzControlStopMoveSubtopic = "command"
	PtzControlSetZoomMethod = "set-zoom"
	PtzControlSetZoomSubtopic = "command"
	PtzControlSetPositionMethod = "set-position"
	PtzControlSetPositionSubtopic = "command"
	PtzControlGoHomeMethod = "go-home"
	PtzControlGoHomeSubtopic = "command"
	PtzControlPtzStatusMessage = "ptz-status"
	PtzControlPtzPositionMessage = "ptz-position"
	PtzControlPtzCommandAckMessage = "ptz-command-ack"
	PtzControlPtzErrorMessage = "ptz-error"
)

type PtzControlPtzRange struct {
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

type PtzControlMoveStatus struct {
	PanTilt string `json:"panTilt,omitempty"`
	Zoom string `json:"zoom,omitempty"`
}

type PtzControlPtzCapabilities struct {
	CanAbsolutePanTilt bool `json:"canAbsolutePanTilt"`
	CanAbsoluteZoom bool `json:"canAbsoluteZoom"`
	CanContinuousPanTilt bool `json:"canContinuousPanTilt"`
	CanContinuousZoom bool `json:"canContinuousZoom"`
	CanGoHome bool `json:"canGoHome"`
	PanRange PtzControlPtzRange `json:"panRange,omitempty"`
	TiltRange PtzControlPtzRange `json:"tiltRange,omitempty"`
	ZoomRange PtzControlPtzRange `json:"zoomRange,omitempty"`
}

type PtzControlPositionSnapshot struct {
	Capabilities PtzControlPtzCapabilities `json:"capabilities,omitempty"`
	CameraName string `json:"cameraName"`
	MoveStatus PtzControlMoveStatus `json:"moveStatus,omitempty"`
	Pan float64 `json:"pan"`
	Tilt float64 `json:"tilt"`
	UpdatedAt string `json:"updatedAt"`
	Zoom float64 `json:"zoom"`
}

type PtzControlVelocityCommand struct {
	Pan float64 `json:"pan"`
	Tilt float64 `json:"tilt"`
	Zoom float64 `json:"zoom"`
}

type PtzControlStatusPayload struct {
	ActiveCamera string `json:"activeCamera,omitempty"`
	Capabilities PtzControlPtzCapabilities `json:"capabilities,omitempty"`
	ConfiguredCameras []string `json:"configuredCameras"`
	LastCommand string `json:"lastCommand,omitempty"`
	LastError string `json:"lastError,omitempty"`
	Position PtzControlPositionSnapshot `json:"position,omitempty"`
}

type PtzControlStatusResponsePayload struct {
	ActiveCamera string `json:"activeCamera,omitempty"`
	Capabilities PtzControlPtzCapabilities `json:"capabilities,omitempty"`
	ConfiguredCameras []string `json:"configuredCameras"`
	LastCommand string `json:"lastCommand,omitempty"`
	LastError string `json:"lastError,omitempty"`
	Position PtzControlPositionSnapshot `json:"position,omitempty"`
	RequestId string `json:"requestId,omitempty"`
}

type PtzControlCommandAckPayload struct {
	Capabilities PtzControlPtzCapabilities `json:"capabilities,omitempty"`
	CameraName string `json:"cameraName"`
	Command string `json:"command"`
	Ok bool `json:"ok"`
	Position PtzControlPositionSnapshot `json:"position,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	Velocity PtzControlVelocityCommand `json:"velocity,omitempty"`
}

type PtzControlPositionResponsePayload struct {
	Capabilities PtzControlPtzCapabilities `json:"capabilities,omitempty"`
	CameraName string `json:"cameraName"`
	MoveStatus PtzControlMoveStatus `json:"moveStatus,omitempty"`
	Pan float64 `json:"pan"`
	RequestId string `json:"requestId,omitempty"`
	Tilt float64 `json:"tilt"`
	UpdatedAt string `json:"updatedAt"`
	Zoom float64 `json:"zoom"`
}

type PtzControlErrorPayload struct {
	CameraName string `json:"cameraName,omitempty"`
	Command string `json:"command"`
	Error string `json:"error"`
	RequestId string `json:"requestId,omitempty"`
}

type PtzControlCameraCommand struct {
	CameraName string `json:"cameraName,omitempty"`
	RequestId string `json:"requestId,omitempty"`
}

type PtzControlMoveCommand struct {
	CameraName string `json:"cameraName"`
	RequestId string `json:"requestId,omitempty"`
	Velocity PtzControlVelocityCommand `json:"velocity"`
}

type PtzControlZoomCommand struct {
	CameraName string `json:"cameraName"`
	RequestId string `json:"requestId,omitempty"`
	Zoom float64 `json:"zoom"`
}

type PtzControlPositionCommand struct {
	CameraName string `json:"cameraName"`
	Pan float64 `json:"pan"`
	RequestId string `json:"requestId,omitempty"`
	Tilt float64 `json:"tilt"`
	Zoom float64 `json:"zoom"`
}

func ParsePtzControlPtzRange(payload json.RawMessage) (PtzControlPtzRange, error) {
	var decoded PtzControlPtzRange
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlMoveStatus(payload json.RawMessage) (PtzControlMoveStatus, error) {
	var decoded PtzControlMoveStatus
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlPtzCapabilities(payload json.RawMessage) (PtzControlPtzCapabilities, error) {
	var decoded PtzControlPtzCapabilities
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlPositionSnapshot(payload json.RawMessage) (PtzControlPositionSnapshot, error) {
	var decoded PtzControlPositionSnapshot
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlVelocityCommand(payload json.RawMessage) (PtzControlVelocityCommand, error) {
	var decoded PtzControlVelocityCommand
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlStatusPayload(payload json.RawMessage) (PtzControlStatusPayload, error) {
	var decoded PtzControlStatusPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlStatusResponsePayload(payload json.RawMessage) (PtzControlStatusResponsePayload, error) {
	var decoded PtzControlStatusResponsePayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlCommandAckPayload(payload json.RawMessage) (PtzControlCommandAckPayload, error) {
	var decoded PtzControlCommandAckPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlPositionResponsePayload(payload json.RawMessage) (PtzControlPositionResponsePayload, error) {
	var decoded PtzControlPositionResponsePayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlErrorPayload(payload json.RawMessage) (PtzControlErrorPayload, error) {
	var decoded PtzControlErrorPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlCameraCommand(payload json.RawMessage) (PtzControlCameraCommand, error) {
	var decoded PtzControlCameraCommand
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlMoveCommand(payload json.RawMessage) (PtzControlMoveCommand, error) {
	var decoded PtzControlMoveCommand
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlZoomCommand(payload json.RawMessage) (PtzControlZoomCommand, error) {
	var decoded PtzControlZoomCommand
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParsePtzControlPositionCommand(payload json.RawMessage) (PtzControlPositionCommand, error) {
	var decoded PtzControlPositionCommand
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

type PtzControlHandler interface {
	HandleGetStatus(ctx context.Context, sourceService string, request PtzControlCameraCommand) error
	HandleGetPosition(ctx context.Context, sourceService string, request PtzControlCameraCommand) error
	HandleStartMove(ctx context.Context, sourceService string, request PtzControlMoveCommand) error
	HandleStopMove(ctx context.Context, sourceService string, request PtzControlCameraCommand) error
	HandleSetZoom(ctx context.Context, sourceService string, request PtzControlZoomCommand) error
	HandleSetPosition(ctx context.Context, sourceService string, request PtzControlPositionCommand) error
	HandleGoHome(ctx context.Context, sourceService string, request PtzControlCameraCommand) error
}

func DispatchPtzControl(ctx context.Context, sourceService string, subtopic string, env ipc.MQTTEnvelope, handler PtzControlHandler) (bool, error) {
	normalizedSubtopic := strings.Trim(strings.TrimSpace(subtopic), "/")
	normalizedType := strings.TrimSpace(env.Type)
	switch normalizedSubtopic {
	case "command":
		switch normalizedType {
		case PtzControlGetStatusMethod:
			request, err := ParsePtzControlCameraCommand(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-status: %w", err)
			}
			return true, handler.HandleGetStatus(ctx, sourceService, request)
		case PtzControlGetPositionMethod:
			request, err := ParsePtzControlCameraCommand(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-position: %w", err)
			}
			return true, handler.HandleGetPosition(ctx, sourceService, request)
		case PtzControlStartMoveMethod:
			request, err := ParsePtzControlMoveCommand(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode start-move: %w", err)
			}
			return true, handler.HandleStartMove(ctx, sourceService, request)
		case PtzControlStopMoveMethod:
			request, err := ParsePtzControlCameraCommand(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode stop-move: %w", err)
			}
			return true, handler.HandleStopMove(ctx, sourceService, request)
		case PtzControlSetZoomMethod:
			request, err := ParsePtzControlZoomCommand(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode set-zoom: %w", err)
			}
			return true, handler.HandleSetZoom(ctx, sourceService, request)
		case PtzControlSetPositionMethod:
			request, err := ParsePtzControlPositionCommand(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode set-position: %w", err)
			}
			return true, handler.HandleSetPosition(ctx, sourceService, request)
		case PtzControlGoHomeMethod:
			request, err := ParsePtzControlCameraCommand(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode go-home: %w", err)
			}
			return true, handler.HandleGoHome(ctx, sourceService, request)
		default:
			return false, nil
		}
	default:
		return false, nil
	}
}

type PtzControlClient struct {
	ipcClient *ipc.Client
	responseRouter *ipc.ResponseRouter
	targetService string
}

func NewPtzControlClient(ipcClient *ipc.Client, responseRouter *ipc.ResponseRouter, targetService string) *PtzControlClient {
	if strings.TrimSpace(targetService) == "" {
		targetService = PtzControlService
	}
	return &PtzControlClient{
		ipcClient: ipcClient,
		responseRouter: responseRouter,
		targetService: strings.TrimSpace(targetService),
	}
}

func (c *PtzControlClient) GetStatus(ctx context.Context, request PtzControlCameraCommand) (PtzControlStatusResponsePayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, PtzControlGetStatusMethod, request)
	if err != nil {
		return PtzControlStatusResponsePayload{}, err
	}
	return DecodePtzControlGetStatusResponse(message)
}

func DecodePtzControlGetStatusResponse(message ipc.ServiceMessageNotification) (PtzControlStatusResponsePayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case PtzControlPtzStatusMessage:
		return ParsePtzControlStatusResponsePayload(message.Envelope.Payload)
	case PtzControlPtzErrorMessage:
		errorPayload, err := ParsePtzControlErrorPayload(message.Envelope.Payload)
		if err != nil {
			return PtzControlStatusResponsePayload{}, err
		}
		return PtzControlStatusResponsePayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return PtzControlStatusResponsePayload{}, fmt.Errorf("unexpected get-status response type %q", message.Envelope.Type)
	}
}

func (c *PtzControlClient) GetPosition(ctx context.Context, request PtzControlCameraCommand) (PtzControlPositionResponsePayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, PtzControlGetPositionMethod, request)
	if err != nil {
		return PtzControlPositionResponsePayload{}, err
	}
	return DecodePtzControlGetPositionResponse(message)
}

func DecodePtzControlGetPositionResponse(message ipc.ServiceMessageNotification) (PtzControlPositionResponsePayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case PtzControlPtzPositionMessage:
		return ParsePtzControlPositionResponsePayload(message.Envelope.Payload)
	case PtzControlPtzErrorMessage:
		errorPayload, err := ParsePtzControlErrorPayload(message.Envelope.Payload)
		if err != nil {
			return PtzControlPositionResponsePayload{}, err
		}
		return PtzControlPositionResponsePayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return PtzControlPositionResponsePayload{}, fmt.Errorf("unexpected get-position response type %q", message.Envelope.Type)
	}
}

func (c *PtzControlClient) StartMove(ctx context.Context, request PtzControlMoveCommand) (PtzControlCommandAckPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, PtzControlStartMoveMethod, request)
	if err != nil {
		return PtzControlCommandAckPayload{}, err
	}
	return DecodePtzControlStartMoveResponse(message)
}

func DecodePtzControlStartMoveResponse(message ipc.ServiceMessageNotification) (PtzControlCommandAckPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case PtzControlPtzCommandAckMessage:
		return ParsePtzControlCommandAckPayload(message.Envelope.Payload)
	case PtzControlPtzErrorMessage:
		errorPayload, err := ParsePtzControlErrorPayload(message.Envelope.Payload)
		if err != nil {
			return PtzControlCommandAckPayload{}, err
		}
		return PtzControlCommandAckPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return PtzControlCommandAckPayload{}, fmt.Errorf("unexpected start-move response type %q", message.Envelope.Type)
	}
}

func (c *PtzControlClient) StopMove(ctx context.Context, request PtzControlCameraCommand) (PtzControlCommandAckPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, PtzControlStopMoveMethod, request)
	if err != nil {
		return PtzControlCommandAckPayload{}, err
	}
	return DecodePtzControlStopMoveResponse(message)
}

func DecodePtzControlStopMoveResponse(message ipc.ServiceMessageNotification) (PtzControlCommandAckPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case PtzControlPtzCommandAckMessage:
		return ParsePtzControlCommandAckPayload(message.Envelope.Payload)
	case PtzControlPtzErrorMessage:
		errorPayload, err := ParsePtzControlErrorPayload(message.Envelope.Payload)
		if err != nil {
			return PtzControlCommandAckPayload{}, err
		}
		return PtzControlCommandAckPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return PtzControlCommandAckPayload{}, fmt.Errorf("unexpected stop-move response type %q", message.Envelope.Type)
	}
}

func (c *PtzControlClient) SetZoom(ctx context.Context, request PtzControlZoomCommand) (PtzControlCommandAckPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, PtzControlSetZoomMethod, request)
	if err != nil {
		return PtzControlCommandAckPayload{}, err
	}
	return DecodePtzControlSetZoomResponse(message)
}

func DecodePtzControlSetZoomResponse(message ipc.ServiceMessageNotification) (PtzControlCommandAckPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case PtzControlPtzCommandAckMessage:
		return ParsePtzControlCommandAckPayload(message.Envelope.Payload)
	case PtzControlPtzErrorMessage:
		errorPayload, err := ParsePtzControlErrorPayload(message.Envelope.Payload)
		if err != nil {
			return PtzControlCommandAckPayload{}, err
		}
		return PtzControlCommandAckPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return PtzControlCommandAckPayload{}, fmt.Errorf("unexpected set-zoom response type %q", message.Envelope.Type)
	}
}

func (c *PtzControlClient) SetPosition(ctx context.Context, request PtzControlPositionCommand) (PtzControlCommandAckPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, PtzControlSetPositionMethod, request)
	if err != nil {
		return PtzControlCommandAckPayload{}, err
	}
	return DecodePtzControlSetPositionResponse(message)
}

func DecodePtzControlSetPositionResponse(message ipc.ServiceMessageNotification) (PtzControlCommandAckPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case PtzControlPtzCommandAckMessage:
		return ParsePtzControlCommandAckPayload(message.Envelope.Payload)
	case PtzControlPtzErrorMessage:
		errorPayload, err := ParsePtzControlErrorPayload(message.Envelope.Payload)
		if err != nil {
			return PtzControlCommandAckPayload{}, err
		}
		return PtzControlCommandAckPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return PtzControlCommandAckPayload{}, fmt.Errorf("unexpected set-position response type %q", message.Envelope.Type)
	}
}

func (c *PtzControlClient) GoHome(ctx context.Context, request PtzControlCameraCommand) (PtzControlCommandAckPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, PtzControlGoHomeMethod, request)
	if err != nil {
		return PtzControlCommandAckPayload{}, err
	}
	return DecodePtzControlGoHomeResponse(message)
}

func DecodePtzControlGoHomeResponse(message ipc.ServiceMessageNotification) (PtzControlCommandAckPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case PtzControlPtzCommandAckMessage:
		return ParsePtzControlCommandAckPayload(message.Envelope.Payload)
	case PtzControlPtzErrorMessage:
		errorPayload, err := ParsePtzControlErrorPayload(message.Envelope.Payload)
		if err != nil {
			return PtzControlCommandAckPayload{}, err
		}
		return PtzControlCommandAckPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return PtzControlCommandAckPayload{}, fmt.Errorf("unexpected go-home response type %q", message.Envelope.Type)
	}
}
