// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.

package contracts

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/trakrai/device-services/internal/ipc"
)

const (
	RoiConfigService = "roi-config"
	RoiConfigGetStatusMethod = "get-status"
	RoiConfigGetStatusSubtopic = "command"
	RoiConfigGetConfigMethod = "get-config"
	RoiConfigGetConfigSubtopic = "command"
	RoiConfigSaveConfigMethod = "save-config"
	RoiConfigSaveConfigSubtopic = "command"
	RoiConfigStatusMessage = "roi-config-status"
	RoiConfigDocumentMessage = "roi-config-document"
	RoiConfigErrorMessage = "roi-config-error"
)

type RoiConfigRequestEnvelope struct {
	RequestId string `json:"requestId,omitempty"`
}

type RoiConfigROIBox struct {
	Height float64 `json:"height"`
	Width float64 `json:"width"`
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type RoiConfigPTZPosition struct {
	Pan float64 `json:"pan"`
	Tilt float64 `json:"tilt"`
	Zoom float64 `json:"zoom"`
}

type RoiConfigROIBoxSpec struct {
	Active bool `json:"active"`
	Bounds RoiConfigROIBox `json:"bounds"`
	Color string `json:"color,omitempty"`
	Id string `json:"id"`
	Name string `json:"name"`
	Tags []string `json:"tags,omitempty"`
}

type RoiConfigBaseLocation struct {
	Active bool `json:"active"`
	Id string `json:"id"`
	Name string `json:"name"`
	Ptz RoiConfigPTZPosition `json:"ptz"`
	Rois []RoiConfigROIBoxSpec `json:"rois"`
}

type RoiConfigCameraROIConfig struct {
	BaseLocations []RoiConfigBaseLocation `json:"baseLocations"`
	CameraName string `json:"cameraName"`
}

type RoiConfigDocument struct {
	Cameras []RoiConfigCameraROIConfig `json:"cameras"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	Version int `json:"version"`
}

type RoiConfigStatusPayload struct {
	BaseLocationCount int `json:"baseLocationCount"`
	CameraCount int `json:"cameraCount"`
	DocumentHash string `json:"documentHash"`
	FilePath string `json:"filePath"`
	RoiBoxCount int `json:"roiBoxCount"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}

type RoiConfigStatusResponsePayload struct {
	RequestId string `json:"requestId,omitempty"`
	BaseLocationCount int `json:"baseLocationCount"`
	CameraCount int `json:"cameraCount"`
	DocumentHash string `json:"documentHash"`
	FilePath string `json:"filePath"`
	RoiBoxCount int `json:"roiBoxCount"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}

type RoiConfigGetConfigPayload struct {
	Document RoiConfigDocument `json:"document"`
	FilePath string `json:"filePath"`
	RequestId string `json:"requestId,omitempty"`
	BaseLocationCount int `json:"baseLocationCount"`
	CameraCount int `json:"cameraCount"`
	DocumentHash string `json:"documentHash"`
	RoiBoxCount int `json:"roiBoxCount"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}

type RoiConfigSaveConfigRequest struct {
	Document RoiConfigDocument `json:"document"`
	RequestId string `json:"requestId,omitempty"`
}

type RoiConfigErrorPayload struct {
	Error string `json:"error"`
	RequestId string `json:"requestId,omitempty"`
	RequestType string `json:"requestType,omitempty"`
}

func ParseRoiConfigRequestEnvelope(payload json.RawMessage) (RoiConfigRequestEnvelope, error) {
	var decoded RoiConfigRequestEnvelope
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigROIBox(payload json.RawMessage) (RoiConfigROIBox, error) {
	var decoded RoiConfigROIBox
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigPTZPosition(payload json.RawMessage) (RoiConfigPTZPosition, error) {
	var decoded RoiConfigPTZPosition
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigROIBoxSpec(payload json.RawMessage) (RoiConfigROIBoxSpec, error) {
	var decoded RoiConfigROIBoxSpec
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigBaseLocation(payload json.RawMessage) (RoiConfigBaseLocation, error) {
	var decoded RoiConfigBaseLocation
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigCameraROIConfig(payload json.RawMessage) (RoiConfigCameraROIConfig, error) {
	var decoded RoiConfigCameraROIConfig
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigDocument(payload json.RawMessage) (RoiConfigDocument, error) {
	var decoded RoiConfigDocument
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigStatusPayload(payload json.RawMessage) (RoiConfigStatusPayload, error) {
	var decoded RoiConfigStatusPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigStatusResponsePayload(payload json.RawMessage) (RoiConfigStatusResponsePayload, error) {
	var decoded RoiConfigStatusResponsePayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigGetConfigPayload(payload json.RawMessage) (RoiConfigGetConfigPayload, error) {
	var decoded RoiConfigGetConfigPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigSaveConfigRequest(payload json.RawMessage) (RoiConfigSaveConfigRequest, error) {
	var decoded RoiConfigSaveConfigRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRoiConfigErrorPayload(payload json.RawMessage) (RoiConfigErrorPayload, error) {
	var decoded RoiConfigErrorPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

type RoiConfigHandler interface {
	HandleGetStatus(ctx context.Context, sourceService string, request RoiConfigRequestEnvelope) error
	HandleGetConfig(ctx context.Context, sourceService string, request RoiConfigRequestEnvelope) error
	HandleSaveConfig(ctx context.Context, sourceService string, request RoiConfigSaveConfigRequest) error
}

func DispatchRoiConfig(ctx context.Context, sourceService string, subtopic string, env ipc.MQTTEnvelope, handler RoiConfigHandler) (bool, error) {
	normalizedSubtopic := strings.Trim(strings.TrimSpace(subtopic), "/")
	normalizedType := strings.TrimSpace(env.Type)
	switch normalizedSubtopic {
	case "command":
		switch normalizedType {
		case RoiConfigGetStatusMethod:
			request, err := ParseRoiConfigRequestEnvelope(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-status: %w", err)
			}
			return true, handler.HandleGetStatus(ctx, sourceService, request)
		case RoiConfigGetConfigMethod:
			request, err := ParseRoiConfigRequestEnvelope(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-config: %w", err)
			}
			return true, handler.HandleGetConfig(ctx, sourceService, request)
		case RoiConfigSaveConfigMethod:
			request, err := ParseRoiConfigSaveConfigRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode save-config: %w", err)
			}
			return true, handler.HandleSaveConfig(ctx, sourceService, request)
		default:
			return false, nil
		}
	default:
		return false, nil
	}
}

type RoiConfigClient struct {
	ipcClient *ipc.Client
	responseRouter *ipc.ResponseRouter
	targetService string
}

func NewRoiConfigClient(ipcClient *ipc.Client, responseRouter *ipc.ResponseRouter, targetService string) *RoiConfigClient {
	if strings.TrimSpace(targetService) == "" {
		targetService = RoiConfigService
	}
	return &RoiConfigClient{
		ipcClient: ipcClient,
		responseRouter: responseRouter,
		targetService: strings.TrimSpace(targetService),
	}
}

func (c *RoiConfigClient) GetStatus(ctx context.Context, request RoiConfigRequestEnvelope) (RoiConfigStatusResponsePayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RoiConfigGetStatusMethod, request)
	if err != nil {
		return RoiConfigStatusResponsePayload{}, err
	}
	return DecodeRoiConfigGetStatusResponse(message)
}

func DecodeRoiConfigGetStatusResponse(message ipc.ServiceMessageNotification) (RoiConfigStatusResponsePayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RoiConfigStatusMessage:
		return ParseRoiConfigStatusResponsePayload(message.Envelope.Payload)
	case RoiConfigErrorMessage:
		errorPayload, err := ParseRoiConfigErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RoiConfigStatusResponsePayload{}, err
		}
		return RoiConfigStatusResponsePayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RoiConfigStatusResponsePayload{}, fmt.Errorf("unexpected get-status response type %q", message.Envelope.Type)
	}
}

func (c *RoiConfigClient) GetConfig(ctx context.Context, request RoiConfigRequestEnvelope) (RoiConfigGetConfigPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RoiConfigGetConfigMethod, request)
	if err != nil {
		return RoiConfigGetConfigPayload{}, err
	}
	return DecodeRoiConfigGetConfigResponse(message)
}

func DecodeRoiConfigGetConfigResponse(message ipc.ServiceMessageNotification) (RoiConfigGetConfigPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RoiConfigDocumentMessage:
		return ParseRoiConfigGetConfigPayload(message.Envelope.Payload)
	case RoiConfigErrorMessage:
		errorPayload, err := ParseRoiConfigErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RoiConfigGetConfigPayload{}, err
		}
		return RoiConfigGetConfigPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RoiConfigGetConfigPayload{}, fmt.Errorf("unexpected get-config response type %q", message.Envelope.Type)
	}
}

func (c *RoiConfigClient) SaveConfig(ctx context.Context, request RoiConfigSaveConfigRequest) (RoiConfigGetConfigPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RoiConfigSaveConfigMethod, request)
	if err != nil {
		return RoiConfigGetConfigPayload{}, err
	}
	return DecodeRoiConfigSaveConfigResponse(message)
}

func DecodeRoiConfigSaveConfigResponse(message ipc.ServiceMessageNotification) (RoiConfigGetConfigPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RoiConfigDocumentMessage:
		return ParseRoiConfigGetConfigPayload(message.Envelope.Payload)
	case RoiConfigErrorMessage:
		errorPayload, err := ParseRoiConfigErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RoiConfigGetConfigPayload{}, err
		}
		return RoiConfigGetConfigPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RoiConfigGetConfigPayload{}, fmt.Errorf("unexpected save-config response type %q", message.Envelope.Type)
	}
}
