// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.

package contracts

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/trakrai/device-services/internal/ipc"
)

const (
	RuntimeManagerService = "runtime-manager"
	RuntimeManagerGetStatusMethod = "get-status"
	RuntimeManagerGetStatusSubtopic = "command"
	RuntimeManagerGetConfigMethod = "get-config"
	RuntimeManagerGetConfigSubtopic = "command"
	RuntimeManagerListConfigsMethod = "list-configs"
	RuntimeManagerListConfigsSubtopic = "command"
	RuntimeManagerGetServiceDefinitionMethod = "get-service-definition"
	RuntimeManagerGetServiceDefinitionSubtopic = "command"
	RuntimeManagerGetServiceLogMethod = "get-service-log"
	RuntimeManagerGetServiceLogSubtopic = "command"
	RuntimeManagerPutConfigMethod = "put-config"
	RuntimeManagerPutConfigSubtopic = "command"
	RuntimeManagerPutRuntimeFileMethod = "put-runtime-file"
	RuntimeManagerPutRuntimeFileSubtopic = "command"
	RuntimeManagerRemoveServiceMethod = "remove-service"
	RuntimeManagerRemoveServiceSubtopic = "command"
	RuntimeManagerRestartServiceMethod = "restart-service"
	RuntimeManagerRestartServiceSubtopic = "command"
	RuntimeManagerStartServiceMethod = "start-service"
	RuntimeManagerStartServiceSubtopic = "command"
	RuntimeManagerStopServiceMethod = "stop-service"
	RuntimeManagerStopServiceSubtopic = "command"
	RuntimeManagerUpdateServiceMethod = "update-service"
	RuntimeManagerUpdateServiceSubtopic = "command"
	RuntimeManagerUpsertServiceMethod = "upsert-service"
	RuntimeManagerUpsertServiceSubtopic = "command"
	RuntimeManagerStatusMessage = "runtime-manager-status"
	RuntimeManagerServiceActionMessage = "runtime-manager-service-action"
	RuntimeManagerServiceDefinitionMessage = "runtime-manager-service-definition"
	RuntimeManagerLogMessage = "runtime-manager-log"
	RuntimeManagerErrorMessage = "runtime-manager-error"
	RuntimeManagerConfigListMessage = "runtime-manager-config-list"
	RuntimeManagerConfigMessage = "runtime-manager-config"
	RuntimeManagerFileMessage = "runtime-manager-file"
	RuntimeManagerUpdateMessage = "runtime-manager-update"
)

type RuntimeManagerRuntimeCPUStats struct {
	CoreCount int `json:"coreCount"`
	UsagePercent float64 `json:"usagePercent,omitempty"`
}

type RuntimeManagerRuntimeLoadStats struct {
	FifteenMinute float64 `json:"fifteenMinute,omitempty"`
	FiveMinute float64 `json:"fiveMinute,omitempty"`
	OneMinute float64 `json:"oneMinute,omitempty"`
}

type RuntimeManagerRuntimeMemoryStats struct {
	AvailableBytes int `json:"availableBytes,omitempty"`
	SwapTotalBytes int `json:"swapTotalBytes,omitempty"`
	SwapUsedBytes int `json:"swapUsedBytes,omitempty"`
	TotalBytes int `json:"totalBytes,omitempty"`
	UsedBytes int `json:"usedBytes,omitempty"`
	UsedPercent float64 `json:"usedPercent,omitempty"`
}

type RuntimeManagerRuntimeDiskStats struct {
	FreeBytes int `json:"freeBytes,omitempty"`
	Label string `json:"label"`
	Path string `json:"path"`
	TotalBytes int `json:"totalBytes,omitempty"`
	UsedBytes int `json:"usedBytes,omitempty"`
	UsedPercent float64 `json:"usedPercent,omitempty"`
}

type RuntimeManagerRuntimeNetworkInterfaceStats struct {
	Name string `json:"name"`
	RxBytes int `json:"rxBytes,omitempty"`
	RxBytesPerSecond float64 `json:"rxBytesPerSecond,omitempty"`
	TxBytes int `json:"txBytes,omitempty"`
	TxBytesPerSecond float64 `json:"txBytesPerSecond,omitempty"`
}

type RuntimeManagerRuntimeNetworkStats struct {
	Interfaces []RuntimeManagerRuntimeNetworkInterfaceStats `json:"interfaces,omitempty"`
	RxBytes int `json:"rxBytes,omitempty"`
	RxBytesPerSecond float64 `json:"rxBytesPerSecond,omitempty"`
	TxBytes int `json:"txBytes,omitempty"`
	TxBytesPerSecond float64 `json:"txBytesPerSecond,omitempty"`
}

type RuntimeManagerRuntimeGPUStats struct {
	DecoderUtilizationPercent float64 `json:"decoderUtilizationPercent,omitempty"`
	EncoderUtilizationPercent float64 `json:"encoderUtilizationPercent,omitempty"`
	MemoryTotalBytes int `json:"memoryTotalBytes,omitempty"`
	MemoryUsedBytes int `json:"memoryUsedBytes,omitempty"`
	Source string `json:"source"`
	TemperatureCelsius float64 `json:"temperatureCelsius,omitempty"`
	UtilizationPercent float64 `json:"utilizationPercent,omitempty"`
}

type RuntimeManagerRuntimeSystemSnapshot struct {
	CollectedAt string `json:"collectedAt"`
	Cpu RuntimeManagerRuntimeCPUStats `json:"cpu"`
	Disks []RuntimeManagerRuntimeDiskStats `json:"disks,omitempty"`
	Gpu RuntimeManagerRuntimeGPUStats `json:"gpu,omitempty"`
	Load RuntimeManagerRuntimeLoadStats `json:"load"`
	Memory RuntimeManagerRuntimeMemoryStats `json:"memory"`
	Network RuntimeManagerRuntimeNetworkStats `json:"network"`
	UptimeSeconds float64 `json:"uptimeSeconds,omitempty"`
}

type RuntimeManagerManagedServiceSnapshot struct {
	ActiveState string `json:"activeState,omitempty"`
	AllowControl bool `json:"allowControl"`
	AllowUpdate bool `json:"allowUpdate"`
	Core bool `json:"core"`
	CpuPercent float64 `json:"cpuPercent,omitempty"`
	Description string `json:"description,omitempty"`
	DisplayName string `json:"displayName"`
	Enabled bool `json:"enabled"`
	InstallPath string `json:"installPath,omitempty"`
	Kind string `json:"kind"`
	LoadState string `json:"loadState,omitempty"`
	LogPath string `json:"logPath,omitempty"`
	MainPid int `json:"mainPid,omitempty"`
	MemoryBytes int `json:"memoryBytes,omitempty"`
	Message string `json:"message,omitempty"`
	Name string `json:"name"`
	ProcessElapsed string `json:"processElapsed,omitempty"`
	ScriptPath string `json:"scriptPath,omitempty"`
	State string `json:"state"`
	SubState string `json:"subState,omitempty"`
	SystemdUnit string `json:"systemdUnit,omitempty"`
	UnitFileState string `json:"unitFileState,omitempty"`
	Version string `json:"version,omitempty"`
	VersionFile string `json:"versionFile,omitempty"`
	VersionSource string `json:"versionSource,omitempty"`
	VersionUpdatedAt string `json:"versionUpdatedAt,omitempty"`
	WorkingDirectory string `json:"workingDirectory,omitempty"`
}

type RuntimeManagerManagedServiceDefinition struct {
	After []string `json:"after,omitempty"`
	AllowControl bool `json:"allowControl"`
	AllowUpdate bool `json:"allowUpdate"`
	Core bool `json:"core"`
	Description string `json:"description,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Enabled bool `json:"enabled"`
	Environment map[string]string `json:"environment,omitempty"`
	EnvironmentFiles []string `json:"environmentFiles,omitempty"`
	ExecStart []string `json:"execStart,omitempty"`
	Group string `json:"group,omitempty"`
	InstallPath string `json:"installPath,omitempty"`
	Kind string `json:"kind,omitempty"`
	LogPath string `json:"logPath,omitempty"`
	Name string `json:"name"`
	Requires []string `json:"requires,omitempty"`
	Restart string `json:"restart,omitempty"`
	RestartSec int `json:"restartSec,omitempty"`
	ScriptPath string `json:"scriptPath,omitempty"`
	SetupCommand []string `json:"setupCommand,omitempty"`
	SystemdUnit string `json:"systemdUnit,omitempty"`
	User string `json:"user,omitempty"`
	VersionCommand []string `json:"versionCommand,omitempty"`
	VersionFile string `json:"versionFile,omitempty"`
	WantedBy string `json:"wantedBy,omitempty"`
	WorkingDirectory string `json:"workingDirectory,omitempty"`
}

type RuntimeManagerManagedServiceDefinitionEnvironment map[string]string

type RuntimeManagerRuntimeConfigEntry struct {
	Consumers []string `json:"consumers,omitempty"`
	Name string `json:"name"`
	Path string `json:"path"`
}

type RuntimeManagerRuntimeStatusPayload struct {
	BinaryDir string `json:"binaryDir"`
	ConfigDir string `json:"configDir"`
	CoreCount int `json:"coreCount"`
	DownloadDir string `json:"downloadDir"`
	GeneratedAt string `json:"generatedAt"`
	LastAction string `json:"lastAction,omitempty"`
	LastError string `json:"lastError,omitempty"`
	LogDir string `json:"logDir"`
	ManagedCount int `json:"managedCount"`
	RequestId string `json:"requestId,omitempty"`
	ScriptDir string `json:"scriptDir"`
	Services []RuntimeManagerManagedServiceSnapshot `json:"services"`
	SharedDir string `json:"sharedDir"`
	StateFile string `json:"stateFile"`
	System RuntimeManagerRuntimeSystemSnapshot `json:"system"`
	VersionDir string `json:"versionDir"`
}

type RuntimeManagerRuntimeActionPayload struct {
	Action string `json:"action"`
	Definition RuntimeManagerManagedServiceDefinition `json:"definition,omitempty"`
	Message string `json:"message,omitempty"`
	Removed bool `json:"removed,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	Service RuntimeManagerManagedServiceSnapshot `json:"service,omitempty"`
	ServiceName string `json:"serviceName"`
}

type RuntimeManagerRuntimeDefinitionPayload struct {
	Definition RuntimeManagerManagedServiceDefinition `json:"definition"`
	RequestId string `json:"requestId,omitempty"`
	ServiceName string `json:"serviceName"`
}

type RuntimeManagerRuntimeLogPayload struct {
	Lines []string `json:"lines"`
	LogPath string `json:"logPath,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	ServiceName string `json:"serviceName"`
	Truncated bool `json:"truncated"`
}

type RuntimeManagerRuntimeErrorPayload struct {
	Action string `json:"action,omitempty"`
	Error string `json:"error"`
	RequestId string `json:"requestId,omitempty"`
	ServiceName string `json:"serviceName,omitempty"`
}

type RuntimeManagerRuntimeConfigListPayload struct {
	Configs []RuntimeManagerRuntimeConfigEntry `json:"configs"`
	RequestId string `json:"requestId,omitempty"`
}

type RuntimeManagerRuntimeConfigPayload struct {
	Config RuntimeManagerRuntimeConfigEntry `json:"config"`
	Content map[string]interface{} `json:"content,omitempty"`
	Message string `json:"message,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	RestartedServices []string `json:"restartedServices,omitempty"`
}

type RuntimeManagerRuntimeConfigPayloadContent map[string]interface{}

type RuntimeManagerRuntimeFilePayload struct {
	Message string `json:"message,omitempty"`
	Mode int `json:"mode,omitempty"`
	Path string `json:"path"`
	RequestId string `json:"requestId,omitempty"`
}

type RuntimeManagerServiceRequest struct {
	RequestId string `json:"requestId,omitempty"`
	ServiceName string `json:"serviceName"`
}

type RuntimeManagerLogRequest struct {
	Lines int `json:"lines,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	ServiceName string `json:"serviceName"`
}

type RuntimeManagerUpdateServiceRequest struct {
	ArtifactSha256 string `json:"artifactSha256,omitempty"`
	LocalPath string `json:"localPath,omitempty"`
	RemotePath string `json:"remotePath,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	ServiceName string `json:"serviceName"`
}

type RuntimeManagerUpsertServiceRequest struct {
	Definition RuntimeManagerManagedServiceDefinition `json:"definition"`
	RequestId string `json:"requestId,omitempty"`
}

type RuntimeManagerRemoveServiceRequest struct {
	PurgeFiles bool `json:"purgeFiles,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	ServiceName string `json:"serviceName"`
}

type RuntimeManagerConfigListRequest struct {
	RequestId string `json:"requestId,omitempty"`
}

type RuntimeManagerConfigRequest struct {
	ConfigName string `json:"configName"`
	RequestId string `json:"requestId,omitempty"`
}

type RuntimeManagerPutConfigRequest struct {
	ConfigName string `json:"configName"`
	Content map[string]interface{} `json:"content"`
	CreateIfMissing bool `json:"createIfMissing,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	RestartServices []string `json:"restartServices,omitempty"`
}

type RuntimeManagerPutConfigRequestContent map[string]interface{}

type RuntimeManagerPutRuntimeFileRequest struct {
	Content string `json:"content"`
	Mode int `json:"mode,omitempty"`
	Path string `json:"path"`
	RequestId string `json:"requestId,omitempty"`
}

func ParseRuntimeManagerRuntimeCPUStats(payload json.RawMessage) (RuntimeManagerRuntimeCPUStats, error) {
	var decoded RuntimeManagerRuntimeCPUStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeLoadStats(payload json.RawMessage) (RuntimeManagerRuntimeLoadStats, error) {
	var decoded RuntimeManagerRuntimeLoadStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeMemoryStats(payload json.RawMessage) (RuntimeManagerRuntimeMemoryStats, error) {
	var decoded RuntimeManagerRuntimeMemoryStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeDiskStats(payload json.RawMessage) (RuntimeManagerRuntimeDiskStats, error) {
	var decoded RuntimeManagerRuntimeDiskStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeNetworkInterfaceStats(payload json.RawMessage) (RuntimeManagerRuntimeNetworkInterfaceStats, error) {
	var decoded RuntimeManagerRuntimeNetworkInterfaceStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeNetworkStats(payload json.RawMessage) (RuntimeManagerRuntimeNetworkStats, error) {
	var decoded RuntimeManagerRuntimeNetworkStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeGPUStats(payload json.RawMessage) (RuntimeManagerRuntimeGPUStats, error) {
	var decoded RuntimeManagerRuntimeGPUStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeSystemSnapshot(payload json.RawMessage) (RuntimeManagerRuntimeSystemSnapshot, error) {
	var decoded RuntimeManagerRuntimeSystemSnapshot
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerManagedServiceSnapshot(payload json.RawMessage) (RuntimeManagerManagedServiceSnapshot, error) {
	var decoded RuntimeManagerManagedServiceSnapshot
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerManagedServiceDefinition(payload json.RawMessage) (RuntimeManagerManagedServiceDefinition, error) {
	var decoded RuntimeManagerManagedServiceDefinition
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeConfigEntry(payload json.RawMessage) (RuntimeManagerRuntimeConfigEntry, error) {
	var decoded RuntimeManagerRuntimeConfigEntry
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeStatusPayload(payload json.RawMessage) (RuntimeManagerRuntimeStatusPayload, error) {
	var decoded RuntimeManagerRuntimeStatusPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeActionPayload(payload json.RawMessage) (RuntimeManagerRuntimeActionPayload, error) {
	var decoded RuntimeManagerRuntimeActionPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeDefinitionPayload(payload json.RawMessage) (RuntimeManagerRuntimeDefinitionPayload, error) {
	var decoded RuntimeManagerRuntimeDefinitionPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeLogPayload(payload json.RawMessage) (RuntimeManagerRuntimeLogPayload, error) {
	var decoded RuntimeManagerRuntimeLogPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeErrorPayload(payload json.RawMessage) (RuntimeManagerRuntimeErrorPayload, error) {
	var decoded RuntimeManagerRuntimeErrorPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeConfigListPayload(payload json.RawMessage) (RuntimeManagerRuntimeConfigListPayload, error) {
	var decoded RuntimeManagerRuntimeConfigListPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeConfigPayload(payload json.RawMessage) (RuntimeManagerRuntimeConfigPayload, error) {
	var decoded RuntimeManagerRuntimeConfigPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRuntimeFilePayload(payload json.RawMessage) (RuntimeManagerRuntimeFilePayload, error) {
	var decoded RuntimeManagerRuntimeFilePayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerServiceRequest(payload json.RawMessage) (RuntimeManagerServiceRequest, error) {
	var decoded RuntimeManagerServiceRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerLogRequest(payload json.RawMessage) (RuntimeManagerLogRequest, error) {
	var decoded RuntimeManagerLogRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerUpdateServiceRequest(payload json.RawMessage) (RuntimeManagerUpdateServiceRequest, error) {
	var decoded RuntimeManagerUpdateServiceRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerUpsertServiceRequest(payload json.RawMessage) (RuntimeManagerUpsertServiceRequest, error) {
	var decoded RuntimeManagerUpsertServiceRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerRemoveServiceRequest(payload json.RawMessage) (RuntimeManagerRemoveServiceRequest, error) {
	var decoded RuntimeManagerRemoveServiceRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerConfigListRequest(payload json.RawMessage) (RuntimeManagerConfigListRequest, error) {
	var decoded RuntimeManagerConfigListRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerConfigRequest(payload json.RawMessage) (RuntimeManagerConfigRequest, error) {
	var decoded RuntimeManagerConfigRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerPutConfigRequest(payload json.RawMessage) (RuntimeManagerPutConfigRequest, error) {
	var decoded RuntimeManagerPutConfigRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseRuntimeManagerPutRuntimeFileRequest(payload json.RawMessage) (RuntimeManagerPutRuntimeFileRequest, error) {
	var decoded RuntimeManagerPutRuntimeFileRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

type RuntimeManagerHandler interface {
	HandleGetStatus(ctx context.Context, sourceService string, request RuntimeManagerConfigListRequest) error
	HandleGetConfig(ctx context.Context, sourceService string, request RuntimeManagerConfigRequest) error
	HandleListConfigs(ctx context.Context, sourceService string, request RuntimeManagerConfigListRequest) error
	HandleGetServiceDefinition(ctx context.Context, sourceService string, request RuntimeManagerServiceRequest) error
	HandleGetServiceLog(ctx context.Context, sourceService string, request RuntimeManagerLogRequest) error
	HandlePutConfig(ctx context.Context, sourceService string, request RuntimeManagerPutConfigRequest) error
	HandlePutRuntimeFile(ctx context.Context, sourceService string, request RuntimeManagerPutRuntimeFileRequest) error
	HandleRemoveService(ctx context.Context, sourceService string, request RuntimeManagerRemoveServiceRequest) error
	HandleRestartService(ctx context.Context, sourceService string, request RuntimeManagerServiceRequest) error
	HandleStartService(ctx context.Context, sourceService string, request RuntimeManagerServiceRequest) error
	HandleStopService(ctx context.Context, sourceService string, request RuntimeManagerServiceRequest) error
	HandleUpdateService(ctx context.Context, sourceService string, request RuntimeManagerUpdateServiceRequest) error
	HandleUpsertService(ctx context.Context, sourceService string, request RuntimeManagerUpsertServiceRequest) error
}

func DispatchRuntimeManager(ctx context.Context, sourceService string, subtopic string, env ipc.MQTTEnvelope, handler RuntimeManagerHandler) (bool, error) {
	normalizedSubtopic := strings.Trim(strings.TrimSpace(subtopic), "/")
	normalizedType := strings.TrimSpace(env.Type)
	switch normalizedSubtopic {
	case "command":
		switch normalizedType {
		case RuntimeManagerGetStatusMethod:
			request, err := ParseRuntimeManagerConfigListRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-status: %w", err)
			}
			return true, handler.HandleGetStatus(ctx, sourceService, request)
		case RuntimeManagerGetConfigMethod:
			request, err := ParseRuntimeManagerConfigRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-config: %w", err)
			}
			return true, handler.HandleGetConfig(ctx, sourceService, request)
		case RuntimeManagerListConfigsMethod:
			request, err := ParseRuntimeManagerConfigListRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode list-configs: %w", err)
			}
			return true, handler.HandleListConfigs(ctx, sourceService, request)
		case RuntimeManagerGetServiceDefinitionMethod:
			request, err := ParseRuntimeManagerServiceRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-service-definition: %w", err)
			}
			return true, handler.HandleGetServiceDefinition(ctx, sourceService, request)
		case RuntimeManagerGetServiceLogMethod:
			request, err := ParseRuntimeManagerLogRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-service-log: %w", err)
			}
			return true, handler.HandleGetServiceLog(ctx, sourceService, request)
		case RuntimeManagerPutConfigMethod:
			request, err := ParseRuntimeManagerPutConfigRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode put-config: %w", err)
			}
			return true, handler.HandlePutConfig(ctx, sourceService, request)
		case RuntimeManagerPutRuntimeFileMethod:
			request, err := ParseRuntimeManagerPutRuntimeFileRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode put-runtime-file: %w", err)
			}
			return true, handler.HandlePutRuntimeFile(ctx, sourceService, request)
		case RuntimeManagerRemoveServiceMethod:
			request, err := ParseRuntimeManagerRemoveServiceRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode remove-service: %w", err)
			}
			return true, handler.HandleRemoveService(ctx, sourceService, request)
		case RuntimeManagerRestartServiceMethod:
			request, err := ParseRuntimeManagerServiceRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode restart-service: %w", err)
			}
			return true, handler.HandleRestartService(ctx, sourceService, request)
		case RuntimeManagerStartServiceMethod:
			request, err := ParseRuntimeManagerServiceRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode start-service: %w", err)
			}
			return true, handler.HandleStartService(ctx, sourceService, request)
		case RuntimeManagerStopServiceMethod:
			request, err := ParseRuntimeManagerServiceRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode stop-service: %w", err)
			}
			return true, handler.HandleStopService(ctx, sourceService, request)
		case RuntimeManagerUpdateServiceMethod:
			request, err := ParseRuntimeManagerUpdateServiceRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode update-service: %w", err)
			}
			return true, handler.HandleUpdateService(ctx, sourceService, request)
		case RuntimeManagerUpsertServiceMethod:
			request, err := ParseRuntimeManagerUpsertServiceRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode upsert-service: %w", err)
			}
			return true, handler.HandleUpsertService(ctx, sourceService, request)
		default:
			return false, nil
		}
	default:
		return false, nil
	}
}

type RuntimeManagerClient struct {
	ipcClient *ipc.Client
	responseRouter *ipc.ResponseRouter
	targetService string
}

func NewRuntimeManagerClient(ipcClient *ipc.Client, responseRouter *ipc.ResponseRouter, targetService string) *RuntimeManagerClient {
	if strings.TrimSpace(targetService) == "" {
		targetService = RuntimeManagerService
	}
	return &RuntimeManagerClient{
		ipcClient: ipcClient,
		responseRouter: responseRouter,
		targetService: strings.TrimSpace(targetService),
	}
}

func (c *RuntimeManagerClient) GetStatus(ctx context.Context, request RuntimeManagerConfigListRequest) (RuntimeManagerRuntimeStatusPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerGetStatusMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeStatusPayload{}, err
	}
	return DecodeRuntimeManagerGetStatusResponse(message)
}

func DecodeRuntimeManagerGetStatusResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeStatusPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerStatusMessage:
		return ParseRuntimeManagerRuntimeStatusPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeStatusPayload{}, err
		}
		return RuntimeManagerRuntimeStatusPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeStatusPayload{}, fmt.Errorf("unexpected get-status response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) GetConfig(ctx context.Context, request RuntimeManagerConfigRequest) (RuntimeManagerRuntimeConfigPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerGetConfigMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeConfigPayload{}, err
	}
	return DecodeRuntimeManagerGetConfigResponse(message)
}

func DecodeRuntimeManagerGetConfigResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeConfigPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerConfigMessage:
		return ParseRuntimeManagerRuntimeConfigPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeConfigPayload{}, err
		}
		return RuntimeManagerRuntimeConfigPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeConfigPayload{}, fmt.Errorf("unexpected get-config response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) ListConfigs(ctx context.Context, request RuntimeManagerConfigListRequest) (RuntimeManagerRuntimeConfigListPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerListConfigsMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeConfigListPayload{}, err
	}
	return DecodeRuntimeManagerListConfigsResponse(message)
}

func DecodeRuntimeManagerListConfigsResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeConfigListPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerConfigListMessage:
		return ParseRuntimeManagerRuntimeConfigListPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeConfigListPayload{}, err
		}
		return RuntimeManagerRuntimeConfigListPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeConfigListPayload{}, fmt.Errorf("unexpected list-configs response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) GetServiceDefinition(ctx context.Context, request RuntimeManagerServiceRequest) (RuntimeManagerRuntimeDefinitionPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerGetServiceDefinitionMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeDefinitionPayload{}, err
	}
	return DecodeRuntimeManagerGetServiceDefinitionResponse(message)
}

func DecodeRuntimeManagerGetServiceDefinitionResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeDefinitionPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerServiceDefinitionMessage:
		return ParseRuntimeManagerRuntimeDefinitionPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeDefinitionPayload{}, err
		}
		return RuntimeManagerRuntimeDefinitionPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeDefinitionPayload{}, fmt.Errorf("unexpected get-service-definition response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) GetServiceLog(ctx context.Context, request RuntimeManagerLogRequest) (RuntimeManagerRuntimeLogPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerGetServiceLogMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeLogPayload{}, err
	}
	return DecodeRuntimeManagerGetServiceLogResponse(message)
}

func DecodeRuntimeManagerGetServiceLogResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeLogPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerLogMessage:
		return ParseRuntimeManagerRuntimeLogPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeLogPayload{}, err
		}
		return RuntimeManagerRuntimeLogPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeLogPayload{}, fmt.Errorf("unexpected get-service-log response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) PutConfig(ctx context.Context, request RuntimeManagerPutConfigRequest) (RuntimeManagerRuntimeConfigPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerPutConfigMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeConfigPayload{}, err
	}
	return DecodeRuntimeManagerPutConfigResponse(message)
}

func DecodeRuntimeManagerPutConfigResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeConfigPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerConfigMessage:
		return ParseRuntimeManagerRuntimeConfigPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeConfigPayload{}, err
		}
		return RuntimeManagerRuntimeConfigPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeConfigPayload{}, fmt.Errorf("unexpected put-config response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) PutRuntimeFile(ctx context.Context, request RuntimeManagerPutRuntimeFileRequest) (RuntimeManagerRuntimeFilePayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerPutRuntimeFileMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeFilePayload{}, err
	}
	return DecodeRuntimeManagerPutRuntimeFileResponse(message)
}

func DecodeRuntimeManagerPutRuntimeFileResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeFilePayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerFileMessage:
		return ParseRuntimeManagerRuntimeFilePayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeFilePayload{}, err
		}
		return RuntimeManagerRuntimeFilePayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeFilePayload{}, fmt.Errorf("unexpected put-runtime-file response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) RemoveService(ctx context.Context, request RuntimeManagerRemoveServiceRequest) (RuntimeManagerRuntimeActionPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerRemoveServiceMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeActionPayload{}, err
	}
	return DecodeRuntimeManagerRemoveServiceResponse(message)
}

func DecodeRuntimeManagerRemoveServiceResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeActionPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerServiceActionMessage:
		return ParseRuntimeManagerRuntimeActionPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeActionPayload{}, err
		}
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf("unexpected remove-service response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) RestartService(ctx context.Context, request RuntimeManagerServiceRequest) (RuntimeManagerRuntimeActionPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerRestartServiceMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeActionPayload{}, err
	}
	return DecodeRuntimeManagerRestartServiceResponse(message)
}

func DecodeRuntimeManagerRestartServiceResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeActionPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerServiceActionMessage:
		return ParseRuntimeManagerRuntimeActionPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeActionPayload{}, err
		}
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf("unexpected restart-service response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) StartService(ctx context.Context, request RuntimeManagerServiceRequest) (RuntimeManagerRuntimeActionPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerStartServiceMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeActionPayload{}, err
	}
	return DecodeRuntimeManagerStartServiceResponse(message)
}

func DecodeRuntimeManagerStartServiceResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeActionPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerServiceActionMessage:
		return ParseRuntimeManagerRuntimeActionPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeActionPayload{}, err
		}
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf("unexpected start-service response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) StopService(ctx context.Context, request RuntimeManagerServiceRequest) (RuntimeManagerRuntimeActionPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerStopServiceMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeActionPayload{}, err
	}
	return DecodeRuntimeManagerStopServiceResponse(message)
}

func DecodeRuntimeManagerStopServiceResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeActionPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerServiceActionMessage:
		return ParseRuntimeManagerRuntimeActionPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeActionPayload{}, err
		}
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf("unexpected stop-service response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) UpdateService(ctx context.Context, request RuntimeManagerUpdateServiceRequest) (RuntimeManagerRuntimeActionPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerUpdateServiceMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeActionPayload{}, err
	}
	return DecodeRuntimeManagerUpdateServiceResponse(message)
}

func DecodeRuntimeManagerUpdateServiceResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeActionPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerUpdateMessage:
		return ParseRuntimeManagerRuntimeActionPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeActionPayload{}, err
		}
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf("unexpected update-service response type %q", message.Envelope.Type)
	}
}

func (c *RuntimeManagerClient) UpsertService(ctx context.Context, request RuntimeManagerUpsertServiceRequest) (RuntimeManagerRuntimeActionPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, RuntimeManagerUpsertServiceMethod, request)
	if err != nil {
		return RuntimeManagerRuntimeActionPayload{}, err
	}
	return DecodeRuntimeManagerUpsertServiceResponse(message)
}

func DecodeRuntimeManagerUpsertServiceResponse(message ipc.ServiceMessageNotification) (RuntimeManagerRuntimeActionPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case RuntimeManagerServiceActionMessage:
		return ParseRuntimeManagerRuntimeActionPayload(message.Envelope.Payload)
	case RuntimeManagerErrorMessage:
		errorPayload, err := ParseRuntimeManagerRuntimeErrorPayload(message.Envelope.Payload)
		if err != nil {
			return RuntimeManagerRuntimeActionPayload{}, err
		}
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return RuntimeManagerRuntimeActionPayload{}, fmt.Errorf("unexpected upsert-service response type %q", message.Envelope.Type)
	}
}
