// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.

package contracts

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/trakrai/device-services/internal/ipc"
)

const (
	VideoRecorderService = "video-recorder"
	VideoRecorderCapturePhotoMethod = "capture-photo"
	VideoRecorderCapturePhotoSubtopic = "command"
	VideoRecorderRecordClipMethod = "record-clip"
	VideoRecorderRecordClipSubtopic = "command"
	VideoRecorderGetJobMethod = "get-job"
	VideoRecorderGetJobSubtopic = "command"
	VideoRecorderListJobsMethod = "list-jobs"
	VideoRecorderListJobsSubtopic = "command"
	VideoRecorderGetStatusMethod = "get-status"
	VideoRecorderGetStatusSubtopic = "command"
	VideoRecorderJobMessage = "video-recorder-job"
	VideoRecorderPhotoMessage = "video-recorder-photo"
	VideoRecorderListMessage = "video-recorder-list"
	VideoRecorderStatusMessage = "video-recorder-status"
	VideoRecorderErrorMessage = "video-recorder-error"
)

type VideoRecorderRequestEnvelope struct {
	RequestId string `json:"requestId,omitempty"`
}

type VideoRecorderRecorderStats struct {
	CompletedJobs int `json:"completedJobs"`
	FailedJobs int `json:"failedJobs"`
	PendingJobs int `json:"pendingJobs"`
	RunningJobs int `json:"runningJobs"`
	TotalJobs int `json:"totalJobs"`
}

type VideoRecorderCameraBufferStatus struct {
	Bytes int `json:"bytes"`
	CameraId string `json:"cameraId"`
	CameraName string `json:"cameraName"`
	Frames int `json:"frames"`
	LatestAt string `json:"latestAt"`
	LatestImageId string `json:"latestImageId"`
	OldestAt string `json:"oldestAt"`
}

type VideoRecorderPhotoCapture struct {
	Bytes int `json:"bytes"`
	CameraId string `json:"cameraId"`
	CameraName string `json:"cameraName"`
	CapturedAt string `json:"capturedAt"`
	ImageId string `json:"imageId"`
	LocalPath string `json:"localPath"`
}

type VideoRecorderRecordingJob struct {
	CameraId string `json:"cameraId"`
	CameraName string `json:"cameraName"`
	CompletedAt string `json:"completedAt,omitempty"`
	Codec string `json:"codec,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	CreatedAt string `json:"createdAt"`
	Error string `json:"error,omitempty"`
	EventAt string `json:"eventAt"`
	FrameCount int `json:"frameCount"`
	FrameRate int `json:"frameRate"`
	Id string `json:"id"`
	ImageId string `json:"imageId"`
	LocalPath string `json:"localPath"`
	Metadata map[string]string `json:"metadata,omitempty"`
	PostSeconds float64 `json:"postSeconds"`
	PreSeconds float64 `json:"preSeconds"`
	RemotePath string `json:"remotePath"`
	Scope string `json:"scope,omitempty"`
	StartedAt string `json:"startedAt,omitempty"`
	State string `json:"state"`
	Timeout string `json:"timeout,omitempty"`
	TransferId string `json:"transferId,omitempty"`
	UpdatedAt string `json:"updatedAt"`
}

type VideoRecorderRecordingJobMetadata map[string]string

type VideoRecorderCapturePhotoRequest struct {
	CameraId string `json:"cameraId,omitempty"`
	CameraName string `json:"cameraName,omitempty"`
	ImageId string `json:"imageId,omitempty"`
	LocalPath string `json:"localPath"`
	RequestId string `json:"requestId,omitempty"`
}

type VideoRecorderRecordClipRequest struct {
	CameraId string `json:"cameraId,omitempty"`
	CameraName string `json:"cameraName,omitempty"`
	Codec string `json:"codec,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	FrameRate int `json:"frameRate,omitempty"`
	ImageId string `json:"imageId,omitempty"`
	LocalPath string `json:"localPath"`
	Metadata map[string]string `json:"metadata,omitempty"`
	PostSeconds float64 `json:"postSeconds,omitempty"`
	PreSeconds float64 `json:"preSeconds,omitempty"`
	RemotePath string `json:"remotePath"`
	RequestId string `json:"requestId,omitempty"`
	Scope string `json:"scope,omitempty"`
	Timeout string `json:"timeout,omitempty"`
}

type VideoRecorderRecordClipRequestMetadata map[string]string

type VideoRecorderGetJobRequest struct {
	JobId string `json:"jobId"`
	RequestId string `json:"requestId,omitempty"`
}

type VideoRecorderListJobsRequest struct {
	Limit int `json:"limit,omitempty"`
	RequestId string `json:"requestId,omitempty"`
}

type VideoRecorderRecorderJobPayload struct {
	Job VideoRecorderRecordingJob `json:"job"`
	RequestId string `json:"requestId,omitempty"`
}

type VideoRecorderRecorderPhotoPayload struct {
	Photo VideoRecorderPhotoCapture `json:"photo"`
	RequestId string `json:"requestId,omitempty"`
}

type VideoRecorderRecorderListPayload struct {
	Items []VideoRecorderRecordingJob `json:"items"`
	RequestId string `json:"requestId,omitempty"`
}

type VideoRecorderRecorderStatusPayload struct {
	Buffers []VideoRecorderCameraBufferStatus `json:"buffers"`
	DeviceId string `json:"deviceId"`
	Gstreamer string `json:"gstreamer"`
	RequestId string `json:"requestId,omitempty"`
	SharedDir string `json:"sharedDir"`
	Stats VideoRecorderRecorderStats `json:"stats"`
}

type VideoRecorderRecorderErrorPayload struct {
	Error string `json:"error"`
	RequestId string `json:"requestId,omitempty"`
	RequestType string `json:"requestType,omitempty"`
}

func ParseVideoRecorderRequestEnvelope(payload json.RawMessage) (VideoRecorderRequestEnvelope, error) {
	var decoded VideoRecorderRequestEnvelope
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderRecorderStats(payload json.RawMessage) (VideoRecorderRecorderStats, error) {
	var decoded VideoRecorderRecorderStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderCameraBufferStatus(payload json.RawMessage) (VideoRecorderCameraBufferStatus, error) {
	var decoded VideoRecorderCameraBufferStatus
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderPhotoCapture(payload json.RawMessage) (VideoRecorderPhotoCapture, error) {
	var decoded VideoRecorderPhotoCapture
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderRecordingJob(payload json.RawMessage) (VideoRecorderRecordingJob, error) {
	var decoded VideoRecorderRecordingJob
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderCapturePhotoRequest(payload json.RawMessage) (VideoRecorderCapturePhotoRequest, error) {
	var decoded VideoRecorderCapturePhotoRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderRecordClipRequest(payload json.RawMessage) (VideoRecorderRecordClipRequest, error) {
	var decoded VideoRecorderRecordClipRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderGetJobRequest(payload json.RawMessage) (VideoRecorderGetJobRequest, error) {
	var decoded VideoRecorderGetJobRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderListJobsRequest(payload json.RawMessage) (VideoRecorderListJobsRequest, error) {
	var decoded VideoRecorderListJobsRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderRecorderJobPayload(payload json.RawMessage) (VideoRecorderRecorderJobPayload, error) {
	var decoded VideoRecorderRecorderJobPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderRecorderPhotoPayload(payload json.RawMessage) (VideoRecorderRecorderPhotoPayload, error) {
	var decoded VideoRecorderRecorderPhotoPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderRecorderListPayload(payload json.RawMessage) (VideoRecorderRecorderListPayload, error) {
	var decoded VideoRecorderRecorderListPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderRecorderStatusPayload(payload json.RawMessage) (VideoRecorderRecorderStatusPayload, error) {
	var decoded VideoRecorderRecorderStatusPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseVideoRecorderRecorderErrorPayload(payload json.RawMessage) (VideoRecorderRecorderErrorPayload, error) {
	var decoded VideoRecorderRecorderErrorPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

type VideoRecorderHandler interface {
	HandleCapturePhoto(ctx context.Context, sourceService string, request VideoRecorderCapturePhotoRequest) error
	HandleRecordClip(ctx context.Context, sourceService string, request VideoRecorderRecordClipRequest) error
	HandleGetJob(ctx context.Context, sourceService string, request VideoRecorderGetJobRequest) error
	HandleListJobs(ctx context.Context, sourceService string, request VideoRecorderListJobsRequest) error
	HandleGetStatus(ctx context.Context, sourceService string, request VideoRecorderRequestEnvelope) error
}

func DispatchVideoRecorder(ctx context.Context, sourceService string, subtopic string, env ipc.MQTTEnvelope, handler VideoRecorderHandler) (bool, error) {
	normalizedSubtopic := strings.Trim(strings.TrimSpace(subtopic), "/")
	normalizedType := strings.TrimSpace(env.Type)
	switch normalizedSubtopic {
	case "command":
		switch normalizedType {
		case VideoRecorderCapturePhotoMethod:
			request, err := ParseVideoRecorderCapturePhotoRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode capture-photo: %w", err)
			}
			return true, handler.HandleCapturePhoto(ctx, sourceService, request)
		case VideoRecorderRecordClipMethod:
			request, err := ParseVideoRecorderRecordClipRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode record-clip: %w", err)
			}
			return true, handler.HandleRecordClip(ctx, sourceService, request)
		case VideoRecorderGetJobMethod:
			request, err := ParseVideoRecorderGetJobRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-job: %w", err)
			}
			return true, handler.HandleGetJob(ctx, sourceService, request)
		case VideoRecorderListJobsMethod:
			request, err := ParseVideoRecorderListJobsRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode list-jobs: %w", err)
			}
			return true, handler.HandleListJobs(ctx, sourceService, request)
		case VideoRecorderGetStatusMethod:
			request, err := ParseVideoRecorderRequestEnvelope(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-status: %w", err)
			}
			return true, handler.HandleGetStatus(ctx, sourceService, request)
		default:
			return false, nil
		}
	default:
		return false, nil
	}
}

type VideoRecorderClient struct {
	ipcClient *ipc.Client
	responseRouter *ipc.ResponseRouter
	targetService string
}

func NewVideoRecorderClient(ipcClient *ipc.Client, responseRouter *ipc.ResponseRouter, targetService string) *VideoRecorderClient {
	if strings.TrimSpace(targetService) == "" {
		targetService = VideoRecorderService
	}
	return &VideoRecorderClient{
		ipcClient: ipcClient,
		responseRouter: responseRouter,
		targetService: strings.TrimSpace(targetService),
	}
}

func (c *VideoRecorderClient) CapturePhoto(ctx context.Context, request VideoRecorderCapturePhotoRequest) (VideoRecorderRecorderPhotoPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, VideoRecorderCapturePhotoMethod, request)
	if err != nil {
		return VideoRecorderRecorderPhotoPayload{}, err
	}
	return DecodeVideoRecorderCapturePhotoResponse(message)
}

func DecodeVideoRecorderCapturePhotoResponse(message ipc.ServiceMessageNotification) (VideoRecorderRecorderPhotoPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case VideoRecorderPhotoMessage:
		return ParseVideoRecorderRecorderPhotoPayload(message.Envelope.Payload)
	case VideoRecorderErrorMessage:
		errorPayload, err := ParseVideoRecorderRecorderErrorPayload(message.Envelope.Payload)
		if err != nil {
			return VideoRecorderRecorderPhotoPayload{}, err
		}
		return VideoRecorderRecorderPhotoPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return VideoRecorderRecorderPhotoPayload{}, fmt.Errorf("unexpected capture-photo response type %q", message.Envelope.Type)
	}
}

func (c *VideoRecorderClient) RecordClip(ctx context.Context, request VideoRecorderRecordClipRequest) (VideoRecorderRecorderJobPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, VideoRecorderRecordClipMethod, request)
	if err != nil {
		return VideoRecorderRecorderJobPayload{}, err
	}
	return DecodeVideoRecorderRecordClipResponse(message)
}

func DecodeVideoRecorderRecordClipResponse(message ipc.ServiceMessageNotification) (VideoRecorderRecorderJobPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case VideoRecorderJobMessage:
		return ParseVideoRecorderRecorderJobPayload(message.Envelope.Payload)
	case VideoRecorderErrorMessage:
		errorPayload, err := ParseVideoRecorderRecorderErrorPayload(message.Envelope.Payload)
		if err != nil {
			return VideoRecorderRecorderJobPayload{}, err
		}
		return VideoRecorderRecorderJobPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return VideoRecorderRecorderJobPayload{}, fmt.Errorf("unexpected record-clip response type %q", message.Envelope.Type)
	}
}

func (c *VideoRecorderClient) GetJob(ctx context.Context, request VideoRecorderGetJobRequest) (VideoRecorderRecorderJobPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, VideoRecorderGetJobMethod, request)
	if err != nil {
		return VideoRecorderRecorderJobPayload{}, err
	}
	return DecodeVideoRecorderGetJobResponse(message)
}

func DecodeVideoRecorderGetJobResponse(message ipc.ServiceMessageNotification) (VideoRecorderRecorderJobPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case VideoRecorderJobMessage:
		return ParseVideoRecorderRecorderJobPayload(message.Envelope.Payload)
	case VideoRecorderErrorMessage:
		errorPayload, err := ParseVideoRecorderRecorderErrorPayload(message.Envelope.Payload)
		if err != nil {
			return VideoRecorderRecorderJobPayload{}, err
		}
		return VideoRecorderRecorderJobPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return VideoRecorderRecorderJobPayload{}, fmt.Errorf("unexpected get-job response type %q", message.Envelope.Type)
	}
}

func (c *VideoRecorderClient) ListJobs(ctx context.Context, request VideoRecorderListJobsRequest) (VideoRecorderRecorderListPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, VideoRecorderListJobsMethod, request)
	if err != nil {
		return VideoRecorderRecorderListPayload{}, err
	}
	return DecodeVideoRecorderListJobsResponse(message)
}

func DecodeVideoRecorderListJobsResponse(message ipc.ServiceMessageNotification) (VideoRecorderRecorderListPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case VideoRecorderListMessage:
		return ParseVideoRecorderRecorderListPayload(message.Envelope.Payload)
	case VideoRecorderErrorMessage:
		errorPayload, err := ParseVideoRecorderRecorderErrorPayload(message.Envelope.Payload)
		if err != nil {
			return VideoRecorderRecorderListPayload{}, err
		}
		return VideoRecorderRecorderListPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return VideoRecorderRecorderListPayload{}, fmt.Errorf("unexpected list-jobs response type %q", message.Envelope.Type)
	}
}

func (c *VideoRecorderClient) GetStatus(ctx context.Context, request VideoRecorderRequestEnvelope) (VideoRecorderRecorderStatusPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, VideoRecorderGetStatusMethod, request)
	if err != nil {
		return VideoRecorderRecorderStatusPayload{}, err
	}
	return DecodeVideoRecorderGetStatusResponse(message)
}

func DecodeVideoRecorderGetStatusResponse(message ipc.ServiceMessageNotification) (VideoRecorderRecorderStatusPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case VideoRecorderStatusMessage:
		return ParseVideoRecorderRecorderStatusPayload(message.Envelope.Payload)
	case VideoRecorderErrorMessage:
		errorPayload, err := ParseVideoRecorderRecorderErrorPayload(message.Envelope.Payload)
		if err != nil {
			return VideoRecorderRecorderStatusPayload{}, err
		}
		return VideoRecorderRecorderStatusPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return VideoRecorderRecorderStatusPayload{}, fmt.Errorf("unexpected get-status response type %q", message.Envelope.Type)
	}
}
