// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.

package contracts

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/trakrai/device-services/internal/ipc"
)

const (
	WorkflowEngineService = "workflow-engine"
	WorkflowEngineEnqueueDetectionMethod = "enqueue-detection"
	WorkflowEngineEnqueueDetectionSubtopic = "command"
	WorkflowEngineGetStatusMethod = "get-status"
	WorkflowEngineGetStatusSubtopic = "command"
	WorkflowEngineResultMessage = "workflow-engine-result"
	WorkflowEngineStatusMessage = "workflow-engine-status"
	WorkflowEngineErrorMessage = "workflow-engine-error"
)

type WorkflowEngineDetection struct {
	Bbox []float64 `json:"bbox,omitempty"`
	ClassName string `json:"class_name,omitempty"`
	Conf float64 `json:"conf,omitempty"`
	Confidence float64 `json:"confidence,omitempty"`
	Detections []WorkflowEngineDetection `json:"detections,omitempty"`
	Label string `json:"label,omitempty"`
	RawBboxes []float64 `json:"raw_bboxes,omitempty"`
	X1 float64 `json:"x1,omitempty"`
	X2 float64 `json:"x2,omitempty"`
	Xyxy []float64 `json:"xyxy,omitempty"`
	Y1 float64 `json:"y1,omitempty"`
	Y2 float64 `json:"y2,omitempty"`
}

type WorkflowEngineWorkflowPayload struct {
	DetectionPerClass map[string]int `json:"DetectionPerClass,omitempty"`
	Bbox []WorkflowEngineDetection `json:"bbox,omitempty"`
	CamId string `json:"cam_id,omitempty"`
	CamName string `json:"cam_name,omitempty"`
	CameraId string `json:"cameraId,omitempty"`
	CameraName string `json:"cameraName,omitempty"`
	FrameId string `json:"frame_id,omitempty"`
	ImageId string `json:"imageId,omitempty"`
	ImgID string `json:"imgID,omitempty"`
}

type WorkflowEngineWorkflowPayloadDetectionPerClass map[string]int

type WorkflowEngineEnqueueDetectionRequest struct {
	DetectionPerClass map[string]int `json:"DetectionPerClass,omitempty"`
	Bbox []WorkflowEngineDetection `json:"bbox,omitempty"`
	CameraId string `json:"cameraId,omitempty"`
	CameraName string `json:"cameraName,omitempty"`
	DetectionData WorkflowEngineWorkflowPayload `json:"detectionData,omitempty"`
	Detections []WorkflowEngineDetection `json:"detections,omitempty"`
	FrameId string `json:"frameId,omitempty"`
	ImageId string `json:"imageId,omitempty"`
	ImgID string `json:"imgID,omitempty"`
	RequestId string `json:"requestId,omitempty"`
}

type WorkflowEngineEnqueueDetectionRequestDetectionPerClass map[string]int

type WorkflowEngineNodeResult struct {
	DurationMs float64 `json:"durationMs"`
	Error string `json:"error"`
	Outputs map[string]interface{} `json:"outputs"`
	Status string `json:"status"`
}

type WorkflowEngineNodeResultOutputs map[string]interface{}

type WorkflowEngineWorkflowRun struct {
	CameraId string `json:"cameraId"`
	CameraName string `json:"cameraName"`
	DurationMs float64 `json:"durationMs"`
	Errors []string `json:"errors"`
	ExecutionId string `json:"executionId"`
	FrameId string `json:"frameId"`
	NodeResults map[string]WorkflowEngineNodeResult `json:"nodeResults"`
	Outputs map[string]interface{} `json:"outputs"`
	Success bool `json:"success"`
	WorkflowGeneration int `json:"workflowGeneration"`
	WorkflowHash string `json:"workflowHash"`
}

type WorkflowEngineWorkflowRunNodeResults map[string]WorkflowEngineNodeResult

type WorkflowEngineWorkflowRunOutputs map[string]interface{}

type WorkflowEngineWorkflowResultPayload struct {
	RequestId string `json:"requestId"`
	Run WorkflowEngineWorkflowRun `json:"run"`
}

type WorkflowEngineWorkflowStatusState struct {
	Error string `json:"error"`
	FilePath string `json:"filePath"`
	Generation int `json:"generation"`
	Hash string `json:"hash"`
	Loaded bool `json:"loaded"`
	LoadedAt string `json:"loadedAt"`
	Name string `json:"name"`
}

type WorkflowEngineWorkflowQueueState struct {
	ActiveRequestId string `json:"activeRequestId"`
	MaxPending int `json:"maxPending"`
	Pending int `json:"pending"`
}

type WorkflowEngineWorkflowStats struct {
	DroppedRuns int `json:"droppedRuns"`
	FailedRuns int `json:"failedRuns"`
	ProcessedRuns int `json:"processedRuns"`
	ReloadCount int `json:"reloadCount"`
}

type WorkflowEngineWorkflowStatusPayload struct {
	DeviceId string `json:"deviceId"`
	Queue WorkflowEngineWorkflowQueueState `json:"queue"`
	RecentRuns []WorkflowEngineWorkflowRun `json:"recentRuns"`
	RequestId string `json:"requestId"`
	Service string `json:"service"`
	Stats WorkflowEngineWorkflowStats `json:"stats"`
	Workflow WorkflowEngineWorkflowStatusState `json:"workflow"`
}

type WorkflowEngineWorkflowErrorPayload struct {
	Error string `json:"error"`
	RequestId string `json:"requestId,omitempty"`
	RequestType string `json:"requestType,omitempty"`
}

type WorkflowEngineStatusRequest struct {
	RequestId string `json:"requestId,omitempty"`
}

func ParseWorkflowEngineDetection(payload json.RawMessage) (WorkflowEngineDetection, error) {
	var decoded WorkflowEngineDetection
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineWorkflowPayload(payload json.RawMessage) (WorkflowEngineWorkflowPayload, error) {
	var decoded WorkflowEngineWorkflowPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineEnqueueDetectionRequest(payload json.RawMessage) (WorkflowEngineEnqueueDetectionRequest, error) {
	var decoded WorkflowEngineEnqueueDetectionRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineNodeResult(payload json.RawMessage) (WorkflowEngineNodeResult, error) {
	var decoded WorkflowEngineNodeResult
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineWorkflowRun(payload json.RawMessage) (WorkflowEngineWorkflowRun, error) {
	var decoded WorkflowEngineWorkflowRun
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineWorkflowResultPayload(payload json.RawMessage) (WorkflowEngineWorkflowResultPayload, error) {
	var decoded WorkflowEngineWorkflowResultPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineWorkflowStatusState(payload json.RawMessage) (WorkflowEngineWorkflowStatusState, error) {
	var decoded WorkflowEngineWorkflowStatusState
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineWorkflowQueueState(payload json.RawMessage) (WorkflowEngineWorkflowQueueState, error) {
	var decoded WorkflowEngineWorkflowQueueState
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineWorkflowStats(payload json.RawMessage) (WorkflowEngineWorkflowStats, error) {
	var decoded WorkflowEngineWorkflowStats
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineWorkflowStatusPayload(payload json.RawMessage) (WorkflowEngineWorkflowStatusPayload, error) {
	var decoded WorkflowEngineWorkflowStatusPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineWorkflowErrorPayload(payload json.RawMessage) (WorkflowEngineWorkflowErrorPayload, error) {
	var decoded WorkflowEngineWorkflowErrorPayload
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

func ParseWorkflowEngineStatusRequest(payload json.RawMessage) (WorkflowEngineStatusRequest, error) {
	var decoded WorkflowEngineStatusRequest
	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return decoded, fmt.Errorf("decode payload: %w", err)
	}
	return decoded, nil
}

type WorkflowEngineHandler interface {
	HandleEnqueueDetection(ctx context.Context, sourceService string, request WorkflowEngineEnqueueDetectionRequest) error
	HandleGetStatus(ctx context.Context, sourceService string, request WorkflowEngineStatusRequest) error
}

func DispatchWorkflowEngine(ctx context.Context, sourceService string, subtopic string, env ipc.MQTTEnvelope, handler WorkflowEngineHandler) (bool, error) {
	normalizedSubtopic := strings.Trim(strings.TrimSpace(subtopic), "/")
	normalizedType := strings.TrimSpace(env.Type)
	switch normalizedSubtopic {
	case "command":
		switch normalizedType {
		case WorkflowEngineEnqueueDetectionMethod:
			request, err := ParseWorkflowEngineEnqueueDetectionRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode enqueue-detection: %w", err)
			}
			return true, handler.HandleEnqueueDetection(ctx, sourceService, request)
		case WorkflowEngineGetStatusMethod:
			request, err := ParseWorkflowEngineStatusRequest(env.Payload)
			if err != nil {
				return true, fmt.Errorf("decode get-status: %w", err)
			}
			return true, handler.HandleGetStatus(ctx, sourceService, request)
		default:
			return false, nil
		}
	default:
		return false, nil
	}
}

type WorkflowEngineClient struct {
	ipcClient *ipc.Client
	responseRouter *ipc.ResponseRouter
	targetService string
}

func NewWorkflowEngineClient(ipcClient *ipc.Client, responseRouter *ipc.ResponseRouter, targetService string) *WorkflowEngineClient {
	if strings.TrimSpace(targetService) == "" {
		targetService = WorkflowEngineService
	}
	return &WorkflowEngineClient{
		ipcClient: ipcClient,
		responseRouter: responseRouter,
		targetService: strings.TrimSpace(targetService),
	}
}

func (c *WorkflowEngineClient) EnqueueDetection(ctx context.Context, request WorkflowEngineEnqueueDetectionRequest) (WorkflowEngineWorkflowResultPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, WorkflowEngineEnqueueDetectionMethod, request)
	if err != nil {
		return WorkflowEngineWorkflowResultPayload{}, err
	}
	return DecodeWorkflowEngineEnqueueDetectionResponse(message)
}

func DecodeWorkflowEngineEnqueueDetectionResponse(message ipc.ServiceMessageNotification) (WorkflowEngineWorkflowResultPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case WorkflowEngineResultMessage:
		return ParseWorkflowEngineWorkflowResultPayload(message.Envelope.Payload)
	case WorkflowEngineErrorMessage:
		errorPayload, err := ParseWorkflowEngineWorkflowErrorPayload(message.Envelope.Payload)
		if err != nil {
			return WorkflowEngineWorkflowResultPayload{}, err
		}
		return WorkflowEngineWorkflowResultPayload{}, fmt.Errorf(strings.TrimSpace(errorPayload.Error))
	default:
		return WorkflowEngineWorkflowResultPayload{}, fmt.Errorf("unexpected enqueue-detection response type %q", message.Envelope.Type)
	}
}

func (c *WorkflowEngineClient) GetStatus(ctx context.Context, request WorkflowEngineStatusRequest) (WorkflowEngineWorkflowStatusPayload, error) {
	message, err := c.responseRouter.Request(ctx, c.ipcClient, c.targetService, WorkflowEngineGetStatusMethod, request)
	if err != nil {
		return WorkflowEngineWorkflowStatusPayload{}, err
	}
	return DecodeWorkflowEngineGetStatusResponse(message)
}

func DecodeWorkflowEngineGetStatusResponse(message ipc.ServiceMessageNotification) (WorkflowEngineWorkflowStatusPayload, error) {
	switch strings.TrimSpace(message.Envelope.Type) {
	case WorkflowEngineStatusMessage:
		return ParseWorkflowEngineWorkflowStatusPayload(message.Envelope.Payload)
	default:
		return WorkflowEngineWorkflowStatusPayload{}, fmt.Errorf("unexpected get-status response type %q", message.Envelope.Type)
	}
}
