export const systemAppDefinitions = [
  {
    key: 'cloud-admin',
    name: 'Cloud Admin',
    description: 'Primary operator console for hierarchy, users, fleet control, and service posture.',
    category: 'operations',
    isSystem: true,
    metadata: {
      route: '/admin',
      surface: 'cloud',
      adminOnly: true,
    },
  },
  {
    key: 'live-workspace',
    name: 'Live Workspace',
    description: 'Shared live view, transport bridge, and future talkback workspace.',
    category: 'operations',
    isSystem: true,
    metadata: {
      route: '/live',
      surface: 'cloud',
      defaultAccessLevel: 'view',
    },
  },
  {
    key: 'workflow-studio',
    name: 'Workflow Studio',
    description: 'Cloud and device workflow authoring, validation, and rollout surface.',
    category: 'workflows',
    isSystem: true,
    metadata: {
      route: '/workflows',
      surface: 'cloud',
      defaultAccessLevel: 'view',
    },
  },
  {
    key: 'event-operations',
    name: 'Event Operations',
    description: 'Violation, tilt, media transfer, and external event inspection lane.',
    category: 'events',
    isSystem: true,
    metadata: {
      route: '/events',
      surface: 'cloud',
      defaultAccessLevel: 'view',
    },
  },
  {
    key: 'device-live-feed',
    name: 'Live Feed',
    description: 'Operator live view for a device camera feed.',
    category: 'device',
    isSystem: true,
    metadata: {
      panelKey: 'live-feed',
      surface: 'device',
      defaultAccessLevel: 'view',
    },
  },
  {
    key: 'device-ptz-control',
    name: 'PTZ Controls',
    description: 'Pan, tilt, and zoom controls for supported devices.',
    category: 'device',
    isSystem: true,
    metadata: {
      panelKey: 'ptz-controls',
      surface: 'device',
      defaultAccessLevel: 'operate',
    },
  },
  {
    key: 'device-workflow-designer',
    name: 'Workflow Designer',
    description: 'Device-side workflow authoring and rollout controls.',
    category: 'device',
    isSystem: true,
    metadata: {
      panelKey: 'workflow-designer',
      surface: 'device',
      defaultAccessLevel: 'view',
    },
  },
  {
    key: 'device-tilt-viewer',
    name: 'Tilt Viewer',
    description: 'Tilt events and current orientation history for a device.',
    category: 'device',
    isSystem: true,
    metadata: {
      panelKey: 'tilt-viewer',
      surface: 'device',
      defaultAccessLevel: 'view',
    },
  },
  {
    key: 'device-violation-viewer',
    name: 'Violation Viewer',
    description: 'Violation events, evidence links, and review state for a device.',
    category: 'device',
    isSystem: true,
    metadata: {
      panelKey: 'violation-viewer',
      surface: 'device',
      defaultAccessLevel: 'view',
    },
  },
  {
    key: 'device-charts',
    name: 'Charts',
    description: 'Trend charts for device detections, violations, and health telemetry.',
    category: 'device',
    isSystem: true,
    metadata: {
      panelKey: 'charts',
      surface: 'device',
      defaultAccessLevel: 'view',
    },
  },
  {
    key: 'device-stats',
    name: 'Stats',
    description: 'Operational statistics and quick counters for device activity.',
    category: 'device',
    isSystem: true,
    metadata: {
      panelKey: 'stats',
      surface: 'device',
      defaultAccessLevel: 'view',
    },
  },
  {
    key: 'device-runtime-control',
    name: 'Runtime Control',
    description: 'Runtime manager, service health, and on-device control surfaces.',
    category: 'device-admin',
    isSystem: true,
    metadata: {
      panelKey: 'runtime-control',
      surface: 'device',
      adminOnly: true,
    },
  },
];
