// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
'use client';

import {
  defineServiceContract,
  defineServiceContractMethod,
  defineServiceContractOutput,
  type ServiceContractOutput,
} from '../lib/service-contract-runtime';

export const AUDIO_MANAGER_SERVICE = 'audio-manager';
export const AUDIO_MANAGER_PLAY_AUDIO_METHOD = 'play-audio';
export const AUDIO_MANAGER_PLAY_AUDIO_SUBTOPIC = 'command';
export const AUDIO_MANAGER_GET_JOB_METHOD = 'get-job';
export const AUDIO_MANAGER_GET_JOB_SUBTOPIC = 'command';
export const AUDIO_MANAGER_LIST_JOBS_METHOD = 'list-jobs';
export const AUDIO_MANAGER_LIST_JOBS_SUBTOPIC = 'command';
export const AUDIO_MANAGER_GET_STATUS_METHOD = 'get-status';
export const AUDIO_MANAGER_GET_STATUS_SUBTOPIC = 'command';
export const AUDIO_MANAGER_JOB_MESSAGE = 'audio-manager-job';
export const AUDIO_MANAGER_RESULT_MESSAGE = 'audio-manager-result';
export const AUDIO_MANAGER_LIST_MESSAGE = 'audio-manager-list';
export const AUDIO_MANAGER_STATUS_MESSAGE = 'audio-manager-status';
export const AUDIO_MANAGER_ERROR_MESSAGE = 'audio-manager-error';

export type AudioManager_AudioStats = Readonly<{
  completed: number;
  deduped: number;
  failed: number;
  processing: number;
  queued: number;
  total: number;
}>;

export type AudioManager_AudioJob = Readonly<{
  id: string;
  requestId: string;
  sourceService: string;
  text: string;
  language: string;
  playLocal: boolean;
  playSpeaker: boolean;
  speakerAddress: string;
  speakerMessageId: string;
  speakerCode: string;
  cameraId: string;
  cameraName: string;
  dedupeKey: string;
  state: string;
  localState: string;
  speakerState: string;
  speakerPayload: string;
  audioPath: string;
  attempts: number;
  error: string;
  createdAt: string;
  updatedAt: string;
  completedAt: string;
}>;

export type AudioManager_AudioRequest = Readonly<{
  cameraId?: string;
  cameraName?: string;
  dedupeKey?: string;
  language?: string;
  message?: string;
  playLocal?: boolean;
  playSpeaker?: boolean;
  requestId?: string;
  speakerAddress?: string;
  speakerCode?: string;
  speakerMessageId?: string;
  text?: string;
}>;

export type AudioManager_GetJobRequest = Readonly<{
  jobId: string;
  requestId?: string;
}>;

export type AudioManager_ListJobsRequest = Readonly<{
  limit?: number;
  requestId?: string;
}>;

export type AudioManager_StatusRequest = Readonly<{
  requestId?: string;
}>;

export type AudioManager_AudioJobPayload = Readonly<{
  job: AudioManager_AudioJob;
  requestId?: string;
}>;

export type AudioManagerAudioJob = Readonly<{
  id: string;
  requestId: string;
  sourceService: string;
  text: string;
  language: string;
  playLocal: boolean;
  playSpeaker: boolean;
  speakerAddress: string;
  speakerMessageId: string;
  speakerCode: string;
  cameraId: string;
  cameraName: string;
  dedupeKey: string;
  state: string;
  localState: string;
  speakerState: string;
  speakerPayload: string;
  audioPath: string;
  attempts: number;
  error: string;
  createdAt: string;
  updatedAt: string;
  completedAt: string;
}>;

export type AudioManager_AudioListPayload = Readonly<{
  jobs: Array<AudioManager_AudioJob>;
  requestId?: string;
  stats: AudioManager_AudioStats;
}>;

export type AudioManagerAudioStats = Readonly<{
  completed: number;
  deduped: number;
  failed: number;
  processing: number;
  queued: number;
  total: number;
}>;

export type AudioManager_AudioStatusPayload = Readonly<{
  cacheDir: string;
  deviceId: string;
  eventLogPath: string;
  pendingQueueDepth: number;
  playbackBackend: string;
  requestId?: string;
  speakerEnabled: boolean;
  speakerTransport: string;
  stateDbPath: string;
  stats: AudioManager_AudioStats;
  ttsBackend: string;
}>;

export type AudioManager_AudioErrorPayload = Readonly<{
  error: string;
  requestId?: string;
  requestType?: string;
}>;

export type AudioManager_Job_Message = AudioManager_AudioJobPayload;
export type AudioManager_Result_Message = AudioManager_AudioJobPayload;
export type AudioManager_List_Message = AudioManager_AudioListPayload;
export type AudioManager_Status_Message = AudioManager_AudioStatusPayload;
export type AudioManager_Error_Message = AudioManager_AudioErrorPayload;

export type AudioManager_PlayAudio_Input = AudioManager_AudioRequest;
export type AudioManager_PlayAudio_Output = AudioManager_AudioJobPayload;
export type AudioManager_PlayAudio_Error = AudioManager_AudioErrorPayload;
export type AudioManager_GetJob_Input = AudioManager_GetJobRequest;
export type AudioManager_GetJob_Output = AudioManager_AudioJobPayload;
export type AudioManager_GetJob_Error = AudioManager_AudioErrorPayload;
export type AudioManager_ListJobs_Input = AudioManager_ListJobsRequest;
export type AudioManager_ListJobs_Output = AudioManager_AudioListPayload;
export type AudioManager_ListJobs_Error = never;
export type AudioManager_GetStatus_Input = AudioManager_StatusRequest;
export type AudioManager_GetStatus_Output = AudioManager_AudioStatusPayload;
export type AudioManager_GetStatus_Error = never;

export const audio_managerContract = defineServiceContract({
  name: AUDIO_MANAGER_SERVICE,
  methods: {
    'play-audio': defineServiceContractMethod<
      AudioManager_PlayAudio_Input,
      readonly [
        ServiceContractOutput<
          AudioManager_AudioJobPayload,
          'success',
          typeof AUDIO_MANAGER_JOB_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          AudioManager_AudioJobPayload,
          'event',
          typeof AUDIO_MANAGER_RESULT_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          AudioManager_AudioErrorPayload,
          'error',
          typeof AUDIO_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          AudioManager_AudioJobPayload,
          'success',
          typeof AUDIO_MANAGER_JOB_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: AUDIO_MANAGER_JOB_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          AudioManager_AudioJobPayload,
          'event',
          typeof AUDIO_MANAGER_RESULT_MESSAGE,
          'response'
        >({
          kind: 'event',
          messageType: AUDIO_MANAGER_RESULT_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          AudioManager_AudioErrorPayload,
          'error',
          typeof AUDIO_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: AUDIO_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: AUDIO_MANAGER_PLAY_AUDIO_SUBTOPIC,
    }),
    'get-job': defineServiceContractMethod<
      AudioManager_GetJob_Input,
      readonly [
        ServiceContractOutput<
          AudioManager_AudioJobPayload,
          'success',
          typeof AUDIO_MANAGER_JOB_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          AudioManager_AudioErrorPayload,
          'error',
          typeof AUDIO_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          AudioManager_AudioJobPayload,
          'success',
          typeof AUDIO_MANAGER_JOB_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: AUDIO_MANAGER_JOB_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          AudioManager_AudioErrorPayload,
          'error',
          typeof AUDIO_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: AUDIO_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: AUDIO_MANAGER_GET_JOB_SUBTOPIC,
    }),
    'list-jobs': defineServiceContractMethod<
      AudioManager_ListJobs_Input,
      readonly [
        ServiceContractOutput<
          AudioManager_AudioListPayload,
          'success',
          typeof AUDIO_MANAGER_LIST_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          AudioManager_AudioListPayload,
          'success',
          typeof AUDIO_MANAGER_LIST_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: AUDIO_MANAGER_LIST_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: AUDIO_MANAGER_LIST_JOBS_SUBTOPIC,
    }),
    'get-status': defineServiceContractMethod<
      AudioManager_GetStatus_Input,
      readonly [
        ServiceContractOutput<
          AudioManager_AudioStatusPayload,
          'success',
          typeof AUDIO_MANAGER_STATUS_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          AudioManager_AudioStatusPayload,
          'success',
          typeof AUDIO_MANAGER_STATUS_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: AUDIO_MANAGER_STATUS_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: AUDIO_MANAGER_GET_STATUS_SUBTOPIC,
    }),
  },
});

export type AudioManagerContract = typeof audio_managerContract;
