// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
'use client';

import {
  defineServiceContract,
  defineServiceContractMethod,
  defineServiceContractOutput,
  type ServiceContractOutput,
} from '../lib/service-contract-runtime';

export const LIVE_FEED_SERVICE = 'live-feed';
export const LIVE_FEED_START_LIVE_METHOD = 'start-live';
export const LIVE_FEED_START_LIVE_SUBTOPIC = 'command';
export const LIVE_FEED_UPDATE_LIVE_LAYOUT_METHOD = 'update-live-layout';
export const LIVE_FEED_UPDATE_LIVE_LAYOUT_SUBTOPIC = 'command';
export const LIVE_FEED_STOP_LIVE_METHOD = 'stop-live';
export const LIVE_FEED_STOP_LIVE_SUBTOPIC = 'command';
export const LIVE_FEED_SDP_ANSWER_METHOD = 'sdp-answer';
export const LIVE_FEED_SDP_ANSWER_SUBTOPIC = 'webrtc/answer';
export const LIVE_FEED_ICE_CANDIDATE_METHOD = 'ice-candidate';
export const LIVE_FEED_ICE_CANDIDATE_SUBTOPIC = 'webrtc/ice';
export const LIVE_FEED_START_LIVE_ACK_MESSAGE = 'start-live-ack';
export const LIVE_FEED_SDP_OFFER_MESSAGE = 'sdp-offer';
export const LIVE_FEED_LIVE_LAYOUT_UPDATED_MESSAGE = 'live-layout-updated';
export const LIVE_FEED_ICE_CANDIDATE_MESSAGE = 'ice-candidate';

export type LiveFeed_LiveLayoutRequest = Readonly<{
  camera?: string;
  cameraName?: string;
  cameraNames?: Array<string>;
  frameSource?: string;
  layoutMode?: string;
  requestId?: string;
  sessionId?: string;
}>;

export type LiveFeed_StopLiveRequest = Readonly<{
  requestId?: string;
  sessionId?: string;
}>;

export type LiveFeed_SdpAnswerRequest = Readonly<{
  requestId?: string;
  sdp: string;
  sessionId: string;
}>;

export type LiveFeed_IceCandidateBody = Readonly<Record<string, unknown>>;

export type LiveFeed_IceCandidateRequest = Readonly<{
  candidate: LiveFeed_IceCandidateBody;
  requestId?: string;
  sessionId: string;
}>;

export type LiveFeedIceCandidateBody = Readonly<Record<string, unknown>>;

export type LiveFeed_StartLiveAckPayload = Readonly<{
  cameraName: string;
  error?: string;
  frameSource: string;
  ok: boolean;
  requestId?: string;
  sessionId: string;
}>;

export type LiveFeed_SdpOfferPayload = Readonly<{
  cameraName: string;
  frameSource: string;
  requestId?: string;
  sdp: string;
  sessionId: string;
}>;

export type LiveFeed_LiveLayoutUpdatedPayload = Readonly<{
  cameraName: string;
  cameraNames: Array<string>;
  frameSource: string;
  layoutMode: string;
  requestId: string;
  sessionId: string;
}>;

export type LiveFeed_IceCandidateEventPayload = Readonly<{
  candidate: LiveFeed_IceCandidateBody;
  origin: string;
  requestId?: string;
  sessionId: string;
}>;

export type LiveFeed_StartLiveAck_Message = LiveFeed_StartLiveAckPayload;
export type LiveFeed_SdpOffer_Message = LiveFeed_SdpOfferPayload;
export type LiveFeed_LiveLayoutUpdated_Message = LiveFeed_LiveLayoutUpdatedPayload;
export type LiveFeed_IceCandidate_Message = LiveFeed_IceCandidateEventPayload;

export type LiveFeed_StartLive_Input = LiveFeed_LiveLayoutRequest;
export type LiveFeed_StartLive_Output = LiveFeed_StartLiveAckPayload;
export type LiveFeed_StartLive_Error = never;
export type LiveFeed_UpdateLiveLayout_Input = LiveFeed_LiveLayoutRequest;
export type LiveFeed_UpdateLiveLayout_Output = LiveFeed_LiveLayoutUpdatedPayload;
export type LiveFeed_UpdateLiveLayout_Error = never;
export type LiveFeed_StopLive_Input = LiveFeed_StopLiveRequest;
export type LiveFeed_StopLive_Output = void;
export type LiveFeed_StopLive_Error = never;
export type LiveFeed_SdpAnswer_Input = LiveFeed_SdpAnswerRequest;
export type LiveFeed_SdpAnswer_Output = void;
export type LiveFeed_SdpAnswer_Error = never;
export type LiveFeed_IceCandidate_Input = LiveFeed_IceCandidateRequest;
export type LiveFeed_IceCandidate_Output = void;
export type LiveFeed_IceCandidate_Error = never;

export const live_feedContract = defineServiceContract({
  name: LIVE_FEED_SERVICE,
  methods: {
    'start-live': defineServiceContractMethod<
      LiveFeed_StartLive_Input,
      readonly [
        ServiceContractOutput<
          LiveFeed_StartLiveAckPayload,
          'success',
          typeof LIVE_FEED_START_LIVE_ACK_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          LiveFeed_SdpOfferPayload,
          'event',
          typeof LIVE_FEED_SDP_OFFER_MESSAGE,
          'webrtc/offer'
        >,
        ServiceContractOutput<
          LiveFeed_IceCandidateEventPayload,
          'event',
          typeof LIVE_FEED_ICE_CANDIDATE_MESSAGE,
          'webrtc/ice'
        >,
      ]
    >({
      aliases: ['start'] as const,
      outputs: [
        defineServiceContractOutput<
          LiveFeed_StartLiveAckPayload,
          'success',
          typeof LIVE_FEED_START_LIVE_ACK_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: LIVE_FEED_START_LIVE_ACK_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          LiveFeed_SdpOfferPayload,
          'event',
          typeof LIVE_FEED_SDP_OFFER_MESSAGE,
          'webrtc/offer'
        >({
          kind: 'event',
          messageType: LIVE_FEED_SDP_OFFER_MESSAGE,
          subtopic: 'webrtc/offer',
        }),
        defineServiceContractOutput<
          LiveFeed_IceCandidateEventPayload,
          'event',
          typeof LIVE_FEED_ICE_CANDIDATE_MESSAGE,
          'webrtc/ice'
        >({
          kind: 'event',
          messageType: LIVE_FEED_ICE_CANDIDATE_MESSAGE,
          subtopic: 'webrtc/ice',
        }),
      ] as const,
      subtopic: LIVE_FEED_START_LIVE_SUBTOPIC,
    }),
    'update-live-layout': defineServiceContractMethod<
      LiveFeed_UpdateLiveLayout_Input,
      readonly [
        ServiceContractOutput<
          LiveFeed_LiveLayoutUpdatedPayload,
          'success',
          typeof LIVE_FEED_LIVE_LAYOUT_UPDATED_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          LiveFeed_LiveLayoutUpdatedPayload,
          'success',
          typeof LIVE_FEED_LIVE_LAYOUT_UPDATED_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: LIVE_FEED_LIVE_LAYOUT_UPDATED_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: LIVE_FEED_UPDATE_LIVE_LAYOUT_SUBTOPIC,
    }),
    'stop-live': defineServiceContractMethod<LiveFeed_StopLive_Input, readonly []>({
      aliases: ['stop'] as const,
      outputs: [] as const,
      subtopic: LIVE_FEED_STOP_LIVE_SUBTOPIC,
    }),
    'sdp-answer': defineServiceContractMethod<LiveFeed_SdpAnswer_Input, readonly []>({
      outputs: [] as const,
      subtopic: LIVE_FEED_SDP_ANSWER_SUBTOPIC,
    }),
    'ice-candidate': defineServiceContractMethod<LiveFeed_IceCandidate_Input, readonly []>({
      outputs: [] as const,
      subtopic: LIVE_FEED_ICE_CANDIDATE_SUBTOPIC,
    }),
  },
});

export type LiveFeedContract = typeof live_feedContract;
