// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
'use client';

import {
  defineServiceContract,
  defineServiceContractMethod,
  defineServiceContractOutput,
  type ServiceContractOutput,
} from '../lib/service-contract-runtime';

export const RUNTIME_MANAGER_SERVICE = 'runtime-manager';
export const RUNTIME_MANAGER_GET_STATUS_METHOD = 'get-status';
export const RUNTIME_MANAGER_GET_STATUS_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_GET_CONFIG_METHOD = 'get-config';
export const RUNTIME_MANAGER_GET_CONFIG_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_LIST_CONFIGS_METHOD = 'list-configs';
export const RUNTIME_MANAGER_LIST_CONFIGS_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_GET_SERVICE_DEFINITION_METHOD = 'get-service-definition';
export const RUNTIME_MANAGER_GET_SERVICE_DEFINITION_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_GET_SERVICE_LOG_METHOD = 'get-service-log';
export const RUNTIME_MANAGER_GET_SERVICE_LOG_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_PUT_CONFIG_METHOD = 'put-config';
export const RUNTIME_MANAGER_PUT_CONFIG_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_PUT_RUNTIME_FILE_METHOD = 'put-runtime-file';
export const RUNTIME_MANAGER_PUT_RUNTIME_FILE_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_REMOVE_SERVICE_METHOD = 'remove-service';
export const RUNTIME_MANAGER_REMOVE_SERVICE_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_RESTART_SERVICE_METHOD = 'restart-service';
export const RUNTIME_MANAGER_RESTART_SERVICE_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_START_SERVICE_METHOD = 'start-service';
export const RUNTIME_MANAGER_START_SERVICE_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_STOP_SERVICE_METHOD = 'stop-service';
export const RUNTIME_MANAGER_STOP_SERVICE_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_UPDATE_SERVICE_METHOD = 'update-service';
export const RUNTIME_MANAGER_UPDATE_SERVICE_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_UPSERT_SERVICE_METHOD = 'upsert-service';
export const RUNTIME_MANAGER_UPSERT_SERVICE_SUBTOPIC = 'command';
export const RUNTIME_MANAGER_STATUS_MESSAGE = 'runtime-manager-status';
export const RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE = 'runtime-manager-service-action';
export const RUNTIME_MANAGER_SERVICE_DEFINITION_MESSAGE = 'runtime-manager-service-definition';
export const RUNTIME_MANAGER_LOG_MESSAGE = 'runtime-manager-log';
export const RUNTIME_MANAGER_ERROR_MESSAGE = 'runtime-manager-error';
export const RUNTIME_MANAGER_CONFIG_LIST_MESSAGE = 'runtime-manager-config-list';
export const RUNTIME_MANAGER_CONFIG_MESSAGE = 'runtime-manager-config';
export const RUNTIME_MANAGER_FILE_MESSAGE = 'runtime-manager-file';
export const RUNTIME_MANAGER_UPDATE_MESSAGE = 'runtime-manager-update';

export type RuntimeManager_RuntimeCPUStats = Readonly<{
  coreCount: number;
  usagePercent?: number;
}>;

export type RuntimeManager_RuntimeLoadStats = Readonly<{
  fifteenMinute?: number;
  fiveMinute?: number;
  oneMinute?: number;
}>;

export type RuntimeManager_RuntimeMemoryStats = Readonly<{
  availableBytes?: number;
  swapTotalBytes?: number;
  swapUsedBytes?: number;
  totalBytes?: number;
  usedBytes?: number;
  usedPercent?: number;
}>;

export type RuntimeManager_RuntimeDiskStats = Readonly<{
  freeBytes?: number;
  label: string;
  path: string;
  totalBytes?: number;
  usedBytes?: number;
  usedPercent?: number;
}>;

export type RuntimeManager_RuntimeNetworkInterfaceStats = Readonly<{
  name: string;
  rxBytes?: number;
  rxBytesPerSecond?: number;
  txBytes?: number;
  txBytesPerSecond?: number;
}>;

export type RuntimeManager_RuntimeNetworkStats = Readonly<{
  interfaces?: Array<RuntimeManager_RuntimeNetworkInterfaceStats>;
  rxBytes?: number;
  rxBytesPerSecond?: number;
  txBytes?: number;
  txBytesPerSecond?: number;
}>;

export type RuntimeManagerRuntimeNetworkInterfaceStats = Readonly<{
  name: string;
  rxBytes?: number;
  rxBytesPerSecond?: number;
  txBytes?: number;
  txBytesPerSecond?: number;
}>;

export type RuntimeManager_RuntimeGPUStats = Readonly<{
  decoderUtilizationPercent?: number;
  encoderUtilizationPercent?: number;
  memoryTotalBytes?: number;
  memoryUsedBytes?: number;
  source: string;
  temperatureCelsius?: number;
  utilizationPercent?: number;
}>;

export type RuntimeManager_RuntimeSystemSnapshot = Readonly<{
  collectedAt: string;
  cpu: RuntimeManager_RuntimeCPUStats;
  disks?: Array<RuntimeManager_RuntimeDiskStats>;
  gpu?: RuntimeManager_RuntimeGPUStats;
  load: RuntimeManager_RuntimeLoadStats;
  memory: RuntimeManager_RuntimeMemoryStats;
  network: RuntimeManager_RuntimeNetworkStats;
  uptimeSeconds?: number;
}>;

export type RuntimeManagerRuntimeCPUStats = Readonly<{
  coreCount: number;
  usagePercent?: number;
}>;

export type RuntimeManagerRuntimeDiskStats = Readonly<{
  freeBytes?: number;
  label: string;
  path: string;
  totalBytes?: number;
  usedBytes?: number;
  usedPercent?: number;
}>;

export type RuntimeManagerRuntimeGPUStats = Readonly<{
  decoderUtilizationPercent?: number;
  encoderUtilizationPercent?: number;
  memoryTotalBytes?: number;
  memoryUsedBytes?: number;
  source: string;
  temperatureCelsius?: number;
  utilizationPercent?: number;
}>;

export type RuntimeManagerRuntimeLoadStats = Readonly<{
  fifteenMinute?: number;
  fiveMinute?: number;
  oneMinute?: number;
}>;

export type RuntimeManagerRuntimeMemoryStats = Readonly<{
  availableBytes?: number;
  swapTotalBytes?: number;
  swapUsedBytes?: number;
  totalBytes?: number;
  usedBytes?: number;
  usedPercent?: number;
}>;

export type RuntimeManagerRuntimeNetworkStats = Readonly<{
  interfaces?: Array<RuntimeManager_RuntimeNetworkInterfaceStats>;
  rxBytes?: number;
  rxBytesPerSecond?: number;
  txBytes?: number;
  txBytesPerSecond?: number;
}>;

export type RuntimeManager_ManagedServiceSnapshot = Readonly<{
  activeState?: string;
  allowControl: boolean;
  allowUpdate: boolean;
  core: boolean;
  cpuPercent?: number;
  description?: string;
  displayName: string;
  enabled: boolean;
  installPath?: string;
  kind: string;
  loadState?: string;
  logPath?: string;
  mainPid?: number;
  memoryBytes?: number;
  message?: string;
  name: string;
  processElapsed?: string;
  scriptPath?: string;
  state: string;
  subState?: string;
  systemdUnit?: string;
  unitFileState?: string;
  version?: string;
  versionFile?: string;
  versionSource?: string;
  versionUpdatedAt?: string;
  workingDirectory?: string;
}>;

export type RuntimeManager_ManagedServiceDefinition = Readonly<{
  after?: Array<string>;
  allowControl: boolean;
  allowUpdate: boolean;
  core: boolean;
  description?: string;
  displayName?: string;
  enabled: boolean;
  environment?: Record<string, string>;
  environmentFiles?: Array<string>;
  execStart?: Array<string>;
  group?: string;
  installPath?: string;
  kind?: string;
  logPath?: string;
  name: string;
  requires?: Array<string>;
  restart?: string;
  restartSec?: number;
  scriptPath?: string;
  setupCommand?: Array<string>;
  systemdUnit?: string;
  user?: string;
  versionCommand?: Array<string>;
  versionFile?: string;
  wantedBy?: string;
  workingDirectory?: string;
}>;

export type RuntimeManager_ManagedServiceDefinitionEnvironment = Readonly<Record<string, string>>;

export type RuntimeManager_RuntimeConfigEntry = Readonly<{
  consumers?: Array<string>;
  name: string;
  path: string;
}>;

export type RuntimeManager_RuntimeStatusPayload = Readonly<{
  binaryDir: string;
  configDir: string;
  coreCount: number;
  downloadDir: string;
  generatedAt: string;
  lastAction?: string;
  lastError?: string;
  logDir: string;
  managedCount: number;
  requestId?: string;
  scriptDir: string;
  services: Array<RuntimeManager_ManagedServiceSnapshot>;
  sharedDir: string;
  stateFile: string;
  system: RuntimeManager_RuntimeSystemSnapshot;
  versionDir: string;
}>;

export type RuntimeManagerManagedServiceSnapshot = Readonly<{
  activeState?: string;
  allowControl: boolean;
  allowUpdate: boolean;
  core: boolean;
  cpuPercent?: number;
  description?: string;
  displayName: string;
  enabled: boolean;
  installPath?: string;
  kind: string;
  loadState?: string;
  logPath?: string;
  mainPid?: number;
  memoryBytes?: number;
  message?: string;
  name: string;
  processElapsed?: string;
  scriptPath?: string;
  state: string;
  subState?: string;
  systemdUnit?: string;
  unitFileState?: string;
  version?: string;
  versionFile?: string;
  versionSource?: string;
  versionUpdatedAt?: string;
  workingDirectory?: string;
}>;

export type RuntimeManagerRuntimeSystemSnapshot = Readonly<{
  collectedAt: string;
  cpu: RuntimeManager_RuntimeCPUStats;
  disks?: Array<RuntimeManager_RuntimeDiskStats>;
  gpu?: RuntimeManager_RuntimeGPUStats;
  load: RuntimeManager_RuntimeLoadStats;
  memory: RuntimeManager_RuntimeMemoryStats;
  network: RuntimeManager_RuntimeNetworkStats;
  uptimeSeconds?: number;
}>;

export type RuntimeManager_RuntimeActionPayload = Readonly<{
  action: string;
  definition?: RuntimeManager_ManagedServiceDefinition;
  message?: string;
  removed?: boolean;
  requestId?: string;
  service?: RuntimeManager_ManagedServiceSnapshot;
  serviceName: string;
}>;

export type RuntimeManagerManagedServiceDefinition = Readonly<{
  after?: Array<string>;
  allowControl: boolean;
  allowUpdate: boolean;
  core: boolean;
  description?: string;
  displayName?: string;
  enabled: boolean;
  environment?: Record<string, string>;
  environmentFiles?: Array<string>;
  execStart?: Array<string>;
  group?: string;
  installPath?: string;
  kind?: string;
  logPath?: string;
  name: string;
  requires?: Array<string>;
  restart?: string;
  restartSec?: number;
  scriptPath?: string;
  setupCommand?: Array<string>;
  systemdUnit?: string;
  user?: string;
  versionCommand?: Array<string>;
  versionFile?: string;
  wantedBy?: string;
  workingDirectory?: string;
}>;

export type RuntimeManagerManagedServiceDefinitionEnvironment = Readonly<Record<string, string>>;

export type RuntimeManager_RuntimeDefinitionPayload = Readonly<{
  definition: RuntimeManager_ManagedServiceDefinition;
  requestId?: string;
  serviceName: string;
}>;

export type RuntimeManager_RuntimeLogPayload = Readonly<{
  lines: Array<string>;
  logPath?: string;
  requestId?: string;
  serviceName: string;
  truncated: boolean;
}>;

export type RuntimeManager_RuntimeErrorPayload = Readonly<{
  action?: string;
  error: string;
  requestId?: string;
  serviceName?: string;
}>;

export type RuntimeManager_RuntimeConfigListPayload = Readonly<{
  configs: Array<RuntimeManager_RuntimeConfigEntry>;
  requestId?: string;
}>;

export type RuntimeManagerRuntimeConfigEntry = Readonly<{
  consumers?: Array<string>;
  name: string;
  path: string;
}>;

export type RuntimeManager_RuntimeConfigPayload = Readonly<{
  config: RuntimeManager_RuntimeConfigEntry;
  content?: Record<string, unknown>;
  message?: string;
  requestId?: string;
  restartedServices?: Array<string>;
}>;

export type RuntimeManager_RuntimeConfigPayloadContent = Readonly<Record<string, unknown>>;

export type RuntimeManager_RuntimeFilePayload = Readonly<{
  message?: string;
  mode?: number;
  path: string;
  requestId?: string;
}>;

export type RuntimeManager_ServiceRequest = Readonly<{
  requestId?: string;
  serviceName: string;
}>;

export type RuntimeManager_LogRequest = Readonly<{
  lines?: number;
  requestId?: string;
  serviceName: string;
}>;

export type RuntimeManager_UpdateServiceRequest = Readonly<{
  artifactSha256?: string;
  localPath?: string;
  remotePath?: string;
  requestId?: string;
  serviceName: string;
}>;

export type RuntimeManager_UpsertServiceRequest = Readonly<{
  definition: RuntimeManager_ManagedServiceDefinition;
  requestId?: string;
}>;

export type RuntimeManager_RemoveServiceRequest = Readonly<{
  purgeFiles?: boolean;
  requestId?: string;
  serviceName: string;
}>;

export type RuntimeManager_ConfigListRequest = Readonly<{
  requestId?: string;
}>;

export type RuntimeManager_ConfigRequest = Readonly<{
  configName: string;
  requestId?: string;
}>;

export type RuntimeManager_PutConfigRequest = Readonly<{
  configName: string;
  content: Record<string, unknown>;
  createIfMissing?: boolean;
  requestId?: string;
  restartServices?: Array<string>;
}>;

export type RuntimeManager_PutConfigRequestContent = Readonly<Record<string, unknown>>;

export type RuntimeManager_PutRuntimeFileRequest = Readonly<{
  content: string;
  mode?: number;
  path: string;
  requestId?: string;
}>;

export type RuntimeManager_Status_Message = RuntimeManager_RuntimeStatusPayload;
export type RuntimeManager_ServiceAction_Message = RuntimeManager_RuntimeActionPayload;
export type RuntimeManager_ServiceDefinition_Message = RuntimeManager_RuntimeDefinitionPayload;
export type RuntimeManager_Log_Message = RuntimeManager_RuntimeLogPayload;
export type RuntimeManager_Error_Message = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_ConfigList_Message = RuntimeManager_RuntimeConfigListPayload;
export type RuntimeManager_Config_Message = RuntimeManager_RuntimeConfigPayload;
export type RuntimeManager_File_Message = RuntimeManager_RuntimeFilePayload;
export type RuntimeManager_Update_Message = RuntimeManager_RuntimeActionPayload;

export type RuntimeManager_GetStatus_Input = RuntimeManager_ConfigListRequest;
export type RuntimeManager_GetStatus_Output = RuntimeManager_RuntimeStatusPayload;
export type RuntimeManager_GetStatus_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_GetConfig_Input = RuntimeManager_ConfigRequest;
export type RuntimeManager_GetConfig_Output = RuntimeManager_RuntimeConfigPayload;
export type RuntimeManager_GetConfig_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_ListConfigs_Input = RuntimeManager_ConfigListRequest;
export type RuntimeManager_ListConfigs_Output = RuntimeManager_RuntimeConfigListPayload;
export type RuntimeManager_ListConfigs_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_GetServiceDefinition_Input = RuntimeManager_ServiceRequest;
export type RuntimeManager_GetServiceDefinition_Output = RuntimeManager_RuntimeDefinitionPayload;
export type RuntimeManager_GetServiceDefinition_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_GetServiceLog_Input = RuntimeManager_LogRequest;
export type RuntimeManager_GetServiceLog_Output = RuntimeManager_RuntimeLogPayload;
export type RuntimeManager_GetServiceLog_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_PutConfig_Input = RuntimeManager_PutConfigRequest;
export type RuntimeManager_PutConfig_Output = RuntimeManager_RuntimeConfigPayload;
export type RuntimeManager_PutConfig_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_PutRuntimeFile_Input = RuntimeManager_PutRuntimeFileRequest;
export type RuntimeManager_PutRuntimeFile_Output = RuntimeManager_RuntimeFilePayload;
export type RuntimeManager_PutRuntimeFile_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_RemoveService_Input = RuntimeManager_RemoveServiceRequest;
export type RuntimeManager_RemoveService_Output = RuntimeManager_RuntimeActionPayload;
export type RuntimeManager_RemoveService_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_RestartService_Input = RuntimeManager_ServiceRequest;
export type RuntimeManager_RestartService_Output = RuntimeManager_RuntimeActionPayload;
export type RuntimeManager_RestartService_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_StartService_Input = RuntimeManager_ServiceRequest;
export type RuntimeManager_StartService_Output = RuntimeManager_RuntimeActionPayload;
export type RuntimeManager_StartService_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_StopService_Input = RuntimeManager_ServiceRequest;
export type RuntimeManager_StopService_Output = RuntimeManager_RuntimeActionPayload;
export type RuntimeManager_StopService_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_UpdateService_Input = RuntimeManager_UpdateServiceRequest;
export type RuntimeManager_UpdateService_Output = RuntimeManager_RuntimeActionPayload;
export type RuntimeManager_UpdateService_Error = RuntimeManager_RuntimeErrorPayload;
export type RuntimeManager_UpsertService_Input = RuntimeManager_UpsertServiceRequest;
export type RuntimeManager_UpsertService_Output = RuntimeManager_RuntimeActionPayload;
export type RuntimeManager_UpsertService_Error = RuntimeManager_RuntimeErrorPayload;

export const runtime_managerContract = defineServiceContract({
  name: RUNTIME_MANAGER_SERVICE,
  methods: {
    'get-status': defineServiceContractMethod<
      RuntimeManager_GetStatus_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeStatusPayload,
          'success',
          typeof RUNTIME_MANAGER_STATUS_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeStatusPayload,
          'success',
          typeof RUNTIME_MANAGER_STATUS_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_STATUS_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_GET_STATUS_SUBTOPIC,
    }),
    'get-config': defineServiceContractMethod<
      RuntimeManager_GetConfig_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeConfigPayload,
          'success',
          typeof RUNTIME_MANAGER_CONFIG_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeConfigPayload,
          'success',
          typeof RUNTIME_MANAGER_CONFIG_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_CONFIG_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_GET_CONFIG_SUBTOPIC,
    }),
    'list-configs': defineServiceContractMethod<
      RuntimeManager_ListConfigs_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeConfigListPayload,
          'success',
          typeof RUNTIME_MANAGER_CONFIG_LIST_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeConfigListPayload,
          'success',
          typeof RUNTIME_MANAGER_CONFIG_LIST_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_CONFIG_LIST_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_LIST_CONFIGS_SUBTOPIC,
    }),
    'get-service-definition': defineServiceContractMethod<
      RuntimeManager_GetServiceDefinition_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeDefinitionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_DEFINITION_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeDefinitionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_DEFINITION_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_SERVICE_DEFINITION_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_GET_SERVICE_DEFINITION_SUBTOPIC,
    }),
    'get-service-log': defineServiceContractMethod<
      RuntimeManager_GetServiceLog_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeLogPayload,
          'success',
          typeof RUNTIME_MANAGER_LOG_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeLogPayload,
          'success',
          typeof RUNTIME_MANAGER_LOG_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_LOG_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_GET_SERVICE_LOG_SUBTOPIC,
    }),
    'put-config': defineServiceContractMethod<
      RuntimeManager_PutConfig_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeConfigPayload,
          'success',
          typeof RUNTIME_MANAGER_CONFIG_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeConfigPayload,
          'success',
          typeof RUNTIME_MANAGER_CONFIG_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_CONFIG_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_PUT_CONFIG_SUBTOPIC,
    }),
    'put-runtime-file': defineServiceContractMethod<
      RuntimeManager_PutRuntimeFile_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeFilePayload,
          'success',
          typeof RUNTIME_MANAGER_FILE_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeFilePayload,
          'success',
          typeof RUNTIME_MANAGER_FILE_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_FILE_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_PUT_RUNTIME_FILE_SUBTOPIC,
    }),
    'remove-service': defineServiceContractMethod<
      RuntimeManager_RemoveService_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_REMOVE_SERVICE_SUBTOPIC,
    }),
    'restart-service': defineServiceContractMethod<
      RuntimeManager_RestartService_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_RESTART_SERVICE_SUBTOPIC,
    }),
    'start-service': defineServiceContractMethod<
      RuntimeManager_StartService_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_START_SERVICE_SUBTOPIC,
    }),
    'stop-service': defineServiceContractMethod<
      RuntimeManager_StopService_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_STOP_SERVICE_SUBTOPIC,
    }),
    'update-service': defineServiceContractMethod<
      RuntimeManager_UpdateService_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_UPDATE_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_UPDATE_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_UPDATE_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_UPDATE_SERVICE_SUBTOPIC,
    }),
    'upsert-service': defineServiceContractMethod<
      RuntimeManager_UpsertService_Input,
      readonly [
        ServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RuntimeManager_RuntimeActionPayload,
          'success',
          typeof RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RuntimeManager_RuntimeErrorPayload,
          'error',
          typeof RUNTIME_MANAGER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: RUNTIME_MANAGER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: RUNTIME_MANAGER_UPSERT_SERVICE_SUBTOPIC,
    }),
  },
});

export type RuntimeManagerContract = typeof runtime_managerContract;
