// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
'use client';

import {
  defineServiceContract,
  defineServiceContractMethod,
  defineServiceContractOutput,
  type ServiceContractOutput,
} from '../lib/service-contract-runtime';

export const VIDEO_RECORDER_SERVICE = 'video-recorder';
export const VIDEO_RECORDER_CAPTURE_PHOTO_METHOD = 'capture-photo';
export const VIDEO_RECORDER_CAPTURE_PHOTO_SUBTOPIC = 'command';
export const VIDEO_RECORDER_RECORD_CLIP_METHOD = 'record-clip';
export const VIDEO_RECORDER_RECORD_CLIP_SUBTOPIC = 'command';
export const VIDEO_RECORDER_GET_JOB_METHOD = 'get-job';
export const VIDEO_RECORDER_GET_JOB_SUBTOPIC = 'command';
export const VIDEO_RECORDER_LIST_JOBS_METHOD = 'list-jobs';
export const VIDEO_RECORDER_LIST_JOBS_SUBTOPIC = 'command';
export const VIDEO_RECORDER_GET_STATUS_METHOD = 'get-status';
export const VIDEO_RECORDER_GET_STATUS_SUBTOPIC = 'command';
export const VIDEO_RECORDER_JOB_MESSAGE = 'video-recorder-job';
export const VIDEO_RECORDER_PHOTO_MESSAGE = 'video-recorder-photo';
export const VIDEO_RECORDER_LIST_MESSAGE = 'video-recorder-list';
export const VIDEO_RECORDER_STATUS_MESSAGE = 'video-recorder-status';
export const VIDEO_RECORDER_ERROR_MESSAGE = 'video-recorder-error';

export type VideoRecorder_RequestEnvelope = Readonly<{
  requestId?: string;
}>;

export type VideoRecorder_RecorderStats = Readonly<{
  completedJobs: number;
  failedJobs: number;
  pendingJobs: number;
  runningJobs: number;
  totalJobs: number;
}>;

export type VideoRecorder_CameraBufferStatus = Readonly<{
  bytes: number;
  cameraId: string;
  cameraName: string;
  frames: number;
  latestAt: string;
  latestImageId: string;
  oldestAt: string;
}>;

export type VideoRecorder_PhotoCapture = Readonly<{
  bytes: number;
  cameraId: string;
  cameraName: string;
  capturedAt: string;
  imageId: string;
  localPath: string;
}>;

export type VideoRecorder_RecordingJob = Readonly<{
  cameraId: string;
  cameraName: string;
  completedAt?: string;
  codec?: string;
  contentType?: string;
  createdAt: string;
  error?: string;
  eventAt: string;
  frameCount: number;
  frameRate: number;
  id: string;
  imageId: string;
  localPath: string;
  metadata?: Record<string, string>;
  postSeconds: number;
  preSeconds: number;
  remotePath: string;
  scope?: 'device' | 'package';
  startedAt?: string;
  state: 'completed' | 'encoding' | 'failed' | 'queued' | 'uploading' | 'waiting_buffer';
  timeout?: string;
  transferId?: string;
  updatedAt: string;
}>;

export type VideoRecorder_RecordingJobMetadata = Readonly<Record<string, string>>;

export type VideoRecorder_CapturePhotoRequest = Readonly<{
  cameraId?: string;
  cameraName?: string;
  imageId?: string;
  localPath: string;
  requestId?: string;
}>;

export type VideoRecorder_RecordClipRequest = Readonly<{
  cameraId?: string;
  cameraName?: string;
  codec?: string;
  contentType?: string;
  frameRate?: number;
  imageId?: string;
  localPath: string;
  metadata?: Record<string, string>;
  postSeconds?: number;
  preSeconds?: number;
  remotePath: string;
  requestId?: string;
  scope?: 'device' | 'package';
  timeout?: string;
}>;

export type VideoRecorder_RecordClipRequestMetadata = Readonly<Record<string, string>>;

export type VideoRecorder_GetJobRequest = Readonly<{
  jobId: string;
  requestId?: string;
}>;

export type VideoRecorder_ListJobsRequest = Readonly<{
  limit?: number;
  requestId?: string;
}>;

export type VideoRecorder_RecorderJobPayload = Readonly<{
  job: VideoRecorder_RecordingJob;
  requestId?: string;
}>;

export type VideoRecorderRecordingJob = Readonly<{
  cameraId: string;
  cameraName: string;
  completedAt?: string;
  codec?: string;
  contentType?: string;
  createdAt: string;
  error?: string;
  eventAt: string;
  frameCount: number;
  frameRate: number;
  id: string;
  imageId: string;
  localPath: string;
  metadata?: Record<string, string>;
  postSeconds: number;
  preSeconds: number;
  remotePath: string;
  scope?: 'device' | 'package';
  startedAt?: string;
  state: 'completed' | 'encoding' | 'failed' | 'queued' | 'uploading' | 'waiting_buffer';
  timeout?: string;
  transferId?: string;
  updatedAt: string;
}>;

export type VideoRecorderRecordingJobMetadata = Readonly<Record<string, string>>;

export type VideoRecorder_RecorderPhotoPayload = Readonly<{
  photo: VideoRecorder_PhotoCapture;
  requestId?: string;
}>;

export type VideoRecorderPhotoCapture = Readonly<{
  bytes: number;
  cameraId: string;
  cameraName: string;
  capturedAt: string;
  imageId: string;
  localPath: string;
}>;

export type VideoRecorder_RecorderListPayload = Readonly<{
  items: Array<VideoRecorder_RecordingJob>;
  requestId?: string;
}>;

export type VideoRecorder_RecorderStatusPayload = Readonly<{
  buffers: Array<VideoRecorder_CameraBufferStatus>;
  deviceId: string;
  gstreamer: string;
  requestId?: string;
  sharedDir: string;
  stats: VideoRecorder_RecorderStats;
}>;

export type VideoRecorderCameraBufferStatus = Readonly<{
  bytes: number;
  cameraId: string;
  cameraName: string;
  frames: number;
  latestAt: string;
  latestImageId: string;
  oldestAt: string;
}>;

export type VideoRecorderRecorderStats = Readonly<{
  completedJobs: number;
  failedJobs: number;
  pendingJobs: number;
  runningJobs: number;
  totalJobs: number;
}>;

export type VideoRecorder_RecorderErrorPayload = Readonly<{
  error: string;
  requestId?: string;
  requestType?: string;
}>;

export type VideoRecorder_Job_Message = VideoRecorder_RecorderJobPayload;
export type VideoRecorder_Photo_Message = VideoRecorder_RecorderPhotoPayload;
export type VideoRecorder_List_Message = VideoRecorder_RecorderListPayload;
export type VideoRecorder_Status_Message = VideoRecorder_RecorderStatusPayload;
export type VideoRecorder_Error_Message = VideoRecorder_RecorderErrorPayload;

export type VideoRecorder_CapturePhoto_Input = VideoRecorder_CapturePhotoRequest;
export type VideoRecorder_CapturePhoto_Output = VideoRecorder_RecorderPhotoPayload;
export type VideoRecorder_CapturePhoto_Error = VideoRecorder_RecorderErrorPayload;
export type VideoRecorder_RecordClip_Input = VideoRecorder_RecordClipRequest;
export type VideoRecorder_RecordClip_Output = VideoRecorder_RecorderJobPayload;
export type VideoRecorder_RecordClip_Error = VideoRecorder_RecorderErrorPayload;
export type VideoRecorder_GetJob_Input = VideoRecorder_GetJobRequest;
export type VideoRecorder_GetJob_Output = VideoRecorder_RecorderJobPayload;
export type VideoRecorder_GetJob_Error = VideoRecorder_RecorderErrorPayload;
export type VideoRecorder_ListJobs_Input = VideoRecorder_ListJobsRequest;
export type VideoRecorder_ListJobs_Output = VideoRecorder_RecorderListPayload;
export type VideoRecorder_ListJobs_Error = VideoRecorder_RecorderErrorPayload;
export type VideoRecorder_GetStatus_Input = VideoRecorder_RequestEnvelope;
export type VideoRecorder_GetStatus_Output = VideoRecorder_RecorderStatusPayload;
export type VideoRecorder_GetStatus_Error = VideoRecorder_RecorderErrorPayload;

export const video_recorderContract = defineServiceContract({
  name: VIDEO_RECORDER_SERVICE,
  methods: {
    'capture-photo': defineServiceContractMethod<
      VideoRecorder_CapturePhoto_Input,
      readonly [
        ServiceContractOutput<
          VideoRecorder_RecorderPhotoPayload,
          'success',
          typeof VIDEO_RECORDER_PHOTO_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          VideoRecorder_RecorderErrorPayload,
          'error',
          typeof VIDEO_RECORDER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          VideoRecorder_RecorderPhotoPayload,
          'success',
          typeof VIDEO_RECORDER_PHOTO_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: VIDEO_RECORDER_PHOTO_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          VideoRecorder_RecorderErrorPayload,
          'error',
          typeof VIDEO_RECORDER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: VIDEO_RECORDER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: VIDEO_RECORDER_CAPTURE_PHOTO_SUBTOPIC,
    }),
    'record-clip': defineServiceContractMethod<
      VideoRecorder_RecordClip_Input,
      readonly [
        ServiceContractOutput<
          VideoRecorder_RecorderJobPayload,
          'success',
          typeof VIDEO_RECORDER_JOB_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          VideoRecorder_RecorderErrorPayload,
          'error',
          typeof VIDEO_RECORDER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          VideoRecorder_RecorderJobPayload,
          'success',
          typeof VIDEO_RECORDER_JOB_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: VIDEO_RECORDER_JOB_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          VideoRecorder_RecorderErrorPayload,
          'error',
          typeof VIDEO_RECORDER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: VIDEO_RECORDER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: VIDEO_RECORDER_RECORD_CLIP_SUBTOPIC,
    }),
    'get-job': defineServiceContractMethod<
      VideoRecorder_GetJob_Input,
      readonly [
        ServiceContractOutput<
          VideoRecorder_RecorderJobPayload,
          'success',
          typeof VIDEO_RECORDER_JOB_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          VideoRecorder_RecorderErrorPayload,
          'error',
          typeof VIDEO_RECORDER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          VideoRecorder_RecorderJobPayload,
          'success',
          typeof VIDEO_RECORDER_JOB_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: VIDEO_RECORDER_JOB_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          VideoRecorder_RecorderErrorPayload,
          'error',
          typeof VIDEO_RECORDER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: VIDEO_RECORDER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: VIDEO_RECORDER_GET_JOB_SUBTOPIC,
    }),
    'list-jobs': defineServiceContractMethod<
      VideoRecorder_ListJobs_Input,
      readonly [
        ServiceContractOutput<
          VideoRecorder_RecorderListPayload,
          'success',
          typeof VIDEO_RECORDER_LIST_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          VideoRecorder_RecorderErrorPayload,
          'error',
          typeof VIDEO_RECORDER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          VideoRecorder_RecorderListPayload,
          'success',
          typeof VIDEO_RECORDER_LIST_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: VIDEO_RECORDER_LIST_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          VideoRecorder_RecorderErrorPayload,
          'error',
          typeof VIDEO_RECORDER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: VIDEO_RECORDER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: VIDEO_RECORDER_LIST_JOBS_SUBTOPIC,
    }),
    'get-status': defineServiceContractMethod<
      VideoRecorder_GetStatus_Input,
      readonly [
        ServiceContractOutput<
          VideoRecorder_RecorderStatusPayload,
          'success',
          typeof VIDEO_RECORDER_STATUS_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          VideoRecorder_RecorderErrorPayload,
          'error',
          typeof VIDEO_RECORDER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          VideoRecorder_RecorderStatusPayload,
          'success',
          typeof VIDEO_RECORDER_STATUS_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: VIDEO_RECORDER_STATUS_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          VideoRecorder_RecorderErrorPayload,
          'error',
          typeof VIDEO_RECORDER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: VIDEO_RECORDER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: VIDEO_RECORDER_GET_STATUS_SUBTOPIC,
    }),
  },
});

export type VideoRecorderContract = typeof video_recorderContract;
