import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

import { DEFAULT_PORT } from '@/lib/constants';

export const env = createEnv({
  server: {
    DATABASE_URL: z.url(),
    STORAGE_PROVIDER: z.enum(['AZURE', 'MINIO', 'S3']).default('MINIO'),
    AWS_ACCESS_KEY_ID: z.string().optional(),
    AWS_REGION: z.string().optional(),
    AWS_SECRET_ACCESS_KEY: z.string().optional(),
    S3_BUCKET_NAME: z.string().optional(),
    AZURE_STORAGE_ACCOUNT_NAME: z.string().optional(),
    AZURE_STORAGE_ACCOUNT_KEY: z.string().optional(),
    AZURE_STORAGE_CONTAINER_NAME: z.string().optional(),
    MINIO_ACCESS_KEY: z.string().optional(),
    MINIO_BUCKET_NAME: z.string().optional(),
    MINIO_DEVICE_ENDPOINT: z.string().url().optional(),
    MINIO_ENDPOINT: z.string().url().optional(),
    MINIO_REGION: z.string().optional(),
    MINIO_SECRET_KEY: z.string().optional(),
    TRAKRAI_CLOUD_API_ALLOWED_ORIGINS: z.string().optional(),
    TRAKRAI_DEVICE_STORAGE_PREFIX: z.string().default('devices'),
    TRAKRAI_PACKAGE_RELEASE_TOKEN: z.string().optional(),
    TRAKRAI_PACKAGE_STORAGE_PREFIX: z.string().default('device-packages'),
    TRAKRAI_STORAGE_SERVICE_TOKEN: z.string().optional(),
    BETTER_AUTH_SECRET: z.string(),
    BETTER_AUTH_URL: z.string(),
    MICROSOFT_CLIENT_ID: z.string(),
    MICROSOFT_CLIENT_SECRET: z.string(),
    MICROSOFT_TENANT_ID: z.string().default('common'),
    SMTP_SERVER: z.string(),
    SMTP_USER: z.string(),
    SMTP_PASSWORD: z.string(),
    EMAIL_SENDER_ADDRESS: z.string(),
    VERCEL_URL: z.string().optional(),
  },
  shared: {
    NODE_ENV: z.enum(['development', 'test', 'production']),
    PORT: z.coerce.number().int().positive().default(DEFAULT_PORT),
  },
  client: {
    NEXT_PUBLIC_BASE_URL: z.string().optional(),
    NEXT_PUBLIC_LIVE_FEEDER_HTTP_URL: z.string().optional(),
    NEXT_PUBLIC_LIVE_FEEDER_WS_URL: z.string().optional(),
    NEXT_PUBLIC_LIVE_GATEWAY_HTTP_URL: z.string().optional(),
    NEXT_PUBLIC_LIVE_GATEWAY_ICE_TRANSPORT_POLICY: z.enum(['all', 'relay']).optional(),
    NEXT_PUBLIC_LIVE_GATEWAY_WS_URL: z.string().optional(),
    NEXT_PUBLIC_MEDIATOR_HTTP_URL: z.string().optional(),
    NEXT_PUBLIC_MEDIATOR_WS_URL: z.string().optional(),
    NEXT_PUBLIC_TRAKRAI_MANAGEMENT_SERVICE: z.string().optional(),
    NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL: z.string().optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    NODE_ENV: process.env['NODE_ENV'],
    STORAGE_PROVIDER: process.env['STORAGE_PROVIDER'],
    AWS_ACCESS_KEY_ID: process.env['AWS_ACCESS_KEY_ID'],
    AWS_REGION: process.env['AWS_REGION'],
    AWS_SECRET_ACCESS_KEY: process.env['AWS_SECRET_ACCESS_KEY'],
    S3_BUCKET_NAME: process.env['S3_BUCKET_NAME'],
    AZURE_STORAGE_ACCOUNT_NAME: process.env['AZURE_STORAGE_ACCOUNT_NAME'],
    AZURE_STORAGE_ACCOUNT_KEY: process.env['AZURE_STORAGE_ACCOUNT_KEY'],
    AZURE_STORAGE_CONTAINER_NAME: process.env['AZURE_STORAGE_CONTAINER_NAME'],
    MINIO_ACCESS_KEY: process.env['MINIO_ACCESS_KEY'],
    MINIO_BUCKET_NAME: process.env['MINIO_BUCKET_NAME'],
    MINIO_DEVICE_ENDPOINT: process.env['MINIO_DEVICE_ENDPOINT'],
    MINIO_ENDPOINT: process.env['MINIO_ENDPOINT'],
    MINIO_REGION: process.env['MINIO_REGION'],
    MINIO_SECRET_KEY: process.env['MINIO_SECRET_KEY'],
    TRAKRAI_CLOUD_API_ALLOWED_ORIGINS: process.env['TRAKRAI_CLOUD_API_ALLOWED_ORIGINS'],
    TRAKRAI_DEVICE_STORAGE_PREFIX: process.env['TRAKRAI_DEVICE_STORAGE_PREFIX'],
    TRAKRAI_PACKAGE_RELEASE_TOKEN: process.env['TRAKRAI_PACKAGE_RELEASE_TOKEN'],
    TRAKRAI_PACKAGE_STORAGE_PREFIX: process.env['TRAKRAI_PACKAGE_STORAGE_PREFIX'],
    TRAKRAI_STORAGE_SERVICE_TOKEN: process.env['TRAKRAI_STORAGE_SERVICE_TOKEN'],
    BETTER_AUTH_SECRET: process.env['BETTER_AUTH_SECRET'],
    BETTER_AUTH_URL: process.env['BETTER_AUTH_URL'],
    MICROSOFT_CLIENT_ID: process.env['MICROSOFT_CLIENT_ID'],
    MICROSOFT_CLIENT_SECRET: process.env['MICROSOFT_CLIENT_SECRET'],
    MICROSOFT_TENANT_ID: process.env['MICROSOFT_TENANT_ID'],
    SMTP_SERVER: process.env.SMTP_SERVER,
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASSWORD: process.env.SMTP_PASSWORD,
    EMAIL_SENDER_ADDRESS: process.env['EMAIL_SENDER_ADDRESS'],
    PORT: process.env['PORT'],
    NEXT_PUBLIC_BASE_URL: process.env['NEXT_PUBLIC_BASE_URL'],
    NEXT_PUBLIC_LIVE_FEEDER_HTTP_URL: process.env['NEXT_PUBLIC_LIVE_FEEDER_HTTP_URL'],
    NEXT_PUBLIC_LIVE_FEEDER_WS_URL: process.env['NEXT_PUBLIC_LIVE_FEEDER_WS_URL'],
    NEXT_PUBLIC_LIVE_GATEWAY_HTTP_URL: process.env['NEXT_PUBLIC_LIVE_GATEWAY_HTTP_URL'],
    NEXT_PUBLIC_LIVE_GATEWAY_ICE_TRANSPORT_POLICY:
      process.env['NEXT_PUBLIC_LIVE_GATEWAY_ICE_TRANSPORT_POLICY'],
    NEXT_PUBLIC_LIVE_GATEWAY_WS_URL: process.env['NEXT_PUBLIC_LIVE_GATEWAY_WS_URL'],
    NEXT_PUBLIC_MEDIATOR_HTTP_URL: process.env['NEXT_PUBLIC_MEDIATOR_HTTP_URL'],
    NEXT_PUBLIC_MEDIATOR_WS_URL: process.env['NEXT_PUBLIC_MEDIATOR_WS_URL'],
    NEXT_PUBLIC_TRAKRAI_MANAGEMENT_SERVICE: process.env['NEXT_PUBLIC_TRAKRAI_MANAGEMENT_SERVICE'],
    NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL:
      process.env['NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL'],
    VERCEL_URL: process.env['VERCEL_URL'],
  },
  skipValidation:
    process.env['SKIP_ENV_VALIDATION'] !== undefined &&
    process.env['SKIP_ENV_VALIDATION'] === 'true',
  emptyStringAsUndefined: true,
});
