# Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Protocol

from trakrai_service_runtime import ServiceRequestBridge

from ._runtime import convert_value, to_wire_value

AUDIO_MANAGER_SERVICE = "audio-manager"
AUDIO_MANAGER_PLAY_AUDIO_METHOD = "play-audio"
AUDIO_MANAGER_PLAY_AUDIO_SUBTOPIC = "command"
AUDIO_MANAGER_GET_JOB_METHOD = "get-job"
AUDIO_MANAGER_GET_JOB_SUBTOPIC = "command"
AUDIO_MANAGER_LIST_JOBS_METHOD = "list-jobs"
AUDIO_MANAGER_LIST_JOBS_SUBTOPIC = "command"
AUDIO_MANAGER_GET_STATUS_METHOD = "get-status"
AUDIO_MANAGER_GET_STATUS_SUBTOPIC = "command"
AUDIO_MANAGER_JOB_MESSAGE = "audio-manager-job"
AUDIO_MANAGER_RESULT_MESSAGE = "audio-manager-result"
AUDIO_MANAGER_LIST_MESSAGE = "audio-manager-list"
AUDIO_MANAGER_STATUS_MESSAGE = "audio-manager-status"
AUDIO_MANAGER_ERROR_MESSAGE = "audio-manager-error"


@dataclass(frozen=True)
class AudioManagerAudioStats:
    completed: int = field(metadata={"wire_name": "completed"})
    deduped: int = field(metadata={"wire_name": "deduped"})
    failed: int = field(metadata={"wire_name": "failed"})
    processing: int = field(metadata={"wire_name": "processing"})
    queued: int = field(metadata={"wire_name": "queued"})
    total: int = field(metadata={"wire_name": "total"})

@dataclass(frozen=True)
class AudioManagerAudioJob:
    id: str = field(metadata={"wire_name": "id"})
    request_id: str = field(metadata={"wire_name": "requestId"})
    source_service: str = field(metadata={"wire_name": "sourceService"})
    text: str = field(metadata={"wire_name": "text"})
    language: str = field(metadata={"wire_name": "language"})
    play_local: bool = field(metadata={"wire_name": "playLocal"})
    play_speaker: bool = field(metadata={"wire_name": "playSpeaker"})
    speaker_address: str = field(metadata={"wire_name": "speakerAddress"})
    speaker_message_id: str = field(metadata={"wire_name": "speakerMessageId"})
    speaker_code: str = field(metadata={"wire_name": "speakerCode"})
    camera_id: str = field(metadata={"wire_name": "cameraId"})
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    dedupe_key: str = field(metadata={"wire_name": "dedupeKey"})
    state: str = field(metadata={"wire_name": "state"})
    local_state: str = field(metadata={"wire_name": "localState"})
    speaker_state: str = field(metadata={"wire_name": "speakerState"})
    speaker_payload: str = field(metadata={"wire_name": "speakerPayload"})
    audio_path: str = field(metadata={"wire_name": "audioPath"})
    attempts: int = field(metadata={"wire_name": "attempts"})
    error: str = field(metadata={"wire_name": "error"})
    created_at: str = field(metadata={"wire_name": "createdAt"})
    updated_at: str = field(metadata={"wire_name": "updatedAt"})
    completed_at: str = field(metadata={"wire_name": "completedAt"})

@dataclass(frozen=True)
class AudioManagerAudioRequest:
    camera_id: Optional[str] = field(default=None, metadata={"wire_name": "cameraId"})
    camera_name: Optional[str] = field(default=None, metadata={"wire_name": "cameraName"})
    dedupe_key: Optional[str] = field(default=None, metadata={"wire_name": "dedupeKey"})
    language: Optional[str] = field(default=None, metadata={"wire_name": "language"})
    message: Optional[str] = field(default=None, metadata={"wire_name": "message"})
    play_local: Optional[bool] = field(default=None, metadata={"wire_name": "playLocal"})
    play_speaker: Optional[bool] = field(default=None, metadata={"wire_name": "playSpeaker"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    speaker_address: Optional[str] = field(default=None, metadata={"wire_name": "speakerAddress"})
    speaker_code: Optional[str] = field(default=None, metadata={"wire_name": "speakerCode"})
    speaker_message_id: Optional[str] = field(default=None, metadata={"wire_name": "speakerMessageId"})
    text: Optional[str] = field(default=None, metadata={"wire_name": "text"})

@dataclass(frozen=True)
class AudioManagerGetJobRequest:
    job_id: str = field(metadata={"wire_name": "jobId"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class AudioManagerListJobsRequest:
    limit: Optional[int] = field(default=None, metadata={"wire_name": "limit"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class AudioManagerStatusRequest:
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class AudioManagerAudioJobPayload:
    job: AudioManagerAudioJob = field(metadata={"wire_name": "job"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class AudioManagerAudioListPayload:
    jobs: List[AudioManagerAudioJob] = field(metadata={"wire_name": "jobs"})
    stats: AudioManagerAudioStats = field(metadata={"wire_name": "stats"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class AudioManagerAudioStatusPayload:
    cache_dir: str = field(metadata={"wire_name": "cacheDir"})
    device_id: str = field(metadata={"wire_name": "deviceId"})
    event_log_path: str = field(metadata={"wire_name": "eventLogPath"})
    pending_queue_depth: int = field(metadata={"wire_name": "pendingQueueDepth"})
    playback_backend: str = field(metadata={"wire_name": "playbackBackend"})
    speaker_enabled: bool = field(metadata={"wire_name": "speakerEnabled"})
    speaker_transport: str = field(metadata={"wire_name": "speakerTransport"})
    state_db_path: str = field(metadata={"wire_name": "stateDbPath"})
    stats: AudioManagerAudioStats = field(metadata={"wire_name": "stats"})
    tts_backend: str = field(metadata={"wire_name": "ttsBackend"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class AudioManagerAudioErrorPayload:
    error: str = field(metadata={"wire_name": "error"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    request_type: Optional[str] = field(default=None, metadata={"wire_name": "requestType"})

def parse_audio_manager_audio_stats(payload: Optional[Mapping[str, Any]]) -> AudioManagerAudioStats:
    return convert_value(dict(payload or {}), AudioManagerAudioStats)

def parse_audio_manager_audio_job(payload: Optional[Mapping[str, Any]]) -> AudioManagerAudioJob:
    return convert_value(dict(payload or {}), AudioManagerAudioJob)

def parse_audio_manager_audio_request(payload: Optional[Mapping[str, Any]]) -> AudioManagerAudioRequest:
    return convert_value(dict(payload or {}), AudioManagerAudioRequest)

def parse_audio_manager_get_job_request(payload: Optional[Mapping[str, Any]]) -> AudioManagerGetJobRequest:
    return convert_value(dict(payload or {}), AudioManagerGetJobRequest)

def parse_audio_manager_list_jobs_request(payload: Optional[Mapping[str, Any]]) -> AudioManagerListJobsRequest:
    return convert_value(dict(payload or {}), AudioManagerListJobsRequest)

def parse_audio_manager_status_request(payload: Optional[Mapping[str, Any]]) -> AudioManagerStatusRequest:
    return convert_value(dict(payload or {}), AudioManagerStatusRequest)

def parse_audio_manager_audio_job_payload(payload: Optional[Mapping[str, Any]]) -> AudioManagerAudioJobPayload:
    return convert_value(dict(payload or {}), AudioManagerAudioJobPayload)

def parse_audio_manager_audio_list_payload(payload: Optional[Mapping[str, Any]]) -> AudioManagerAudioListPayload:
    return convert_value(dict(payload or {}), AudioManagerAudioListPayload)

def parse_audio_manager_audio_status_payload(payload: Optional[Mapping[str, Any]]) -> AudioManagerAudioStatusPayload:
    return convert_value(dict(payload or {}), AudioManagerAudioStatusPayload)

def parse_audio_manager_audio_error_payload(payload: Optional[Mapping[str, Any]]) -> AudioManagerAudioErrorPayload:
    return convert_value(dict(payload or {}), AudioManagerAudioErrorPayload)

class AudioManagerHandler(Protocol):
    def handle_play_audio(self, source_service: str, request: AudioManagerAudioRequest) -> None: ...
    def handle_get_job(self, source_service: str, request: AudioManagerGetJobRequest) -> None: ...
    def handle_list_jobs(self, source_service: str, request: AudioManagerListJobsRequest) -> None: ...
    def handle_get_status(self, source_service: str, request: AudioManagerStatusRequest) -> None: ...

def dispatch_audio_manager(source_service: str, subtopic: str, envelope: Mapping[str, Any], handler: AudioManagerHandler) -> bool:
    normalized_subtopic = str(subtopic or "").strip().strip("/")
    message_type = str(envelope.get("type", "")).strip()
    payload = envelope.get("payload", {})
    if not isinstance(payload, Mapping):
        payload = {}
    if normalized_subtopic == "command" and message_type == AUDIO_MANAGER_PLAY_AUDIO_METHOD:
        handler.handle_play_audio(source_service, parse_audio_manager_audio_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == AUDIO_MANAGER_GET_JOB_METHOD:
        handler.handle_get_job(source_service, parse_audio_manager_get_job_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == AUDIO_MANAGER_LIST_JOBS_METHOD:
        handler.handle_list_jobs(source_service, parse_audio_manager_list_jobs_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == AUDIO_MANAGER_GET_STATUS_METHOD:
        handler.handle_get_status(source_service, parse_audio_manager_status_request(payload))
        return True
    return False

class AudioManagerClient:
    def __init__(self, bridge: ServiceRequestBridge, target_service: str = "") -> None:
        self._bridge = bridge
        self._target_service = target_service.strip() or AUDIO_MANAGER_SERVICE

    def play_audio(self, request: AudioManagerAudioRequest, timeout_sec: float = 5.0) -> AudioManagerAudioJobPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=AUDIO_MANAGER_PLAY_AUDIO_METHOD,
            payload=to_wire_value(request),
            expected_types={AUDIO_MANAGER_JOB_MESSAGE, AUDIO_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == AUDIO_MANAGER_ERROR_MESSAGE:
            error_payload = parse_audio_manager_audio_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_audio_manager_audio_job_payload(response['payload'])

    def get_job(self, request: AudioManagerGetJobRequest, timeout_sec: float = 5.0) -> AudioManagerAudioJobPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=AUDIO_MANAGER_GET_JOB_METHOD,
            payload=to_wire_value(request),
            expected_types={AUDIO_MANAGER_JOB_MESSAGE, AUDIO_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == AUDIO_MANAGER_ERROR_MESSAGE:
            error_payload = parse_audio_manager_audio_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_audio_manager_audio_job_payload(response['payload'])

    def list_jobs(self, request: AudioManagerListJobsRequest, timeout_sec: float = 5.0) -> AudioManagerAudioListPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=AUDIO_MANAGER_LIST_JOBS_METHOD,
            payload=to_wire_value(request),
            expected_types={AUDIO_MANAGER_LIST_MESSAGE},
            timeout_sec=timeout_sec,
        )
        return parse_audio_manager_audio_list_payload(response['payload'])

    def get_status(self, request: AudioManagerStatusRequest, timeout_sec: float = 5.0) -> AudioManagerAudioStatusPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=AUDIO_MANAGER_GET_STATUS_METHOD,
            payload=to_wire_value(request),
            expected_types={AUDIO_MANAGER_STATUS_MESSAGE},
            timeout_sec=timeout_sec,
        )
        return parse_audio_manager_audio_status_payload(response['payload'])
