# Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Protocol

from trakrai_service_runtime import ServiceRequestBridge

from ._runtime import convert_value, to_wire_value

CLOUD_TRANSFER_SERVICE = "cloud-transfer"
CLOUD_TRANSFER_ENQUEUE_UPLOAD_METHOD = "enqueue-upload"
CLOUD_TRANSFER_ENQUEUE_UPLOAD_SUBTOPIC = "command"
CLOUD_TRANSFER_ENQUEUE_DOWNLOAD_METHOD = "enqueue-download"
CLOUD_TRANSFER_ENQUEUE_DOWNLOAD_SUBTOPIC = "command"
CLOUD_TRANSFER_GET_TRANSFER_METHOD = "get-transfer"
CLOUD_TRANSFER_GET_TRANSFER_SUBTOPIC = "command"
CLOUD_TRANSFER_LIST_TRANSFERS_METHOD = "list-transfers"
CLOUD_TRANSFER_LIST_TRANSFERS_SUBTOPIC = "command"
CLOUD_TRANSFER_GET_STATS_METHOD = "get-stats"
CLOUD_TRANSFER_GET_STATS_SUBTOPIC = "command"
CLOUD_TRANSFER_GET_STATUS_METHOD = "get-status"
CLOUD_TRANSFER_GET_STATUS_SUBTOPIC = "command"
CLOUD_TRANSFER_TRANSFER_MESSAGE = "cloud-transfer-transfer"
CLOUD_TRANSFER_LIST_MESSAGE = "cloud-transfer-list"
CLOUD_TRANSFER_STATS_MESSAGE = "cloud-transfer-stats"
CLOUD_TRANSFER_STATUS_MESSAGE = "cloud-transfer-status"
CLOUD_TRANSFER_ERROR_MESSAGE = "cloud-transfer-error"


@dataclass(frozen=True)
class CloudTransferQueueStats:
    completed: int = field(metadata={"wire_name": "completed"})
    download_queued: int = field(metadata={"wire_name": "downloadQueued"})
    downloads_completed: int = field(metadata={"wire_name": "downloadsCompleted"})
    downloads_failed: int = field(metadata={"wire_name": "downloadsFailed"})
    failed: int = field(metadata={"wire_name": "failed"})
    pending: int = field(metadata={"wire_name": "pending"})
    running: int = field(metadata={"wire_name": "running"})
    total: int = field(metadata={"wire_name": "total"})
    upload_queued: int = field(metadata={"wire_name": "uploadQueued"})
    uploads_completed: int = field(metadata={"wire_name": "uploadsCompleted"})
    uploads_failed: int = field(metadata={"wire_name": "uploadsFailed"})
    next_attempt_at: Optional[str] = field(default=None, metadata={"wire_name": "nextAttemptAt"})

@dataclass(frozen=True)
class CloudTransferTransfer:
    attempts: int = field(metadata={"wire_name": "attempts"})
    created_at: str = field(metadata={"wire_name": "createdAt"})
    device_id: str = field(metadata={"wire_name": "deviceId"})
    direction: str = field(metadata={"wire_name": "direction"})
    id: str = field(metadata={"wire_name": "id"})
    local_path: str = field(metadata={"wire_name": "localPath"})
    remote_path: str = field(metadata={"wire_name": "remotePath"})
    state: str = field(metadata={"wire_name": "state"})
    updated_at: str = field(metadata={"wire_name": "updatedAt"})
    completed_at: Optional[str] = field(default=None, metadata={"wire_name": "completedAt"})
    content_type: Optional[str] = field(default=None, metadata={"wire_name": "contentType"})
    deadline_at: Optional[str] = field(default=None, metadata={"wire_name": "deadlineAt"})
    last_error: Optional[str] = field(default=None, metadata={"wire_name": "lastError"})
    metadata: Optional[Dict[str, str]] = field(default=None, metadata={"wire_name": "metadata"})
    next_attempt_at: Optional[str] = field(default=None, metadata={"wire_name": "nextAttemptAt"})
    object_key: Optional[str] = field(default=None, metadata={"wire_name": "objectKey"})
    scope: Optional[str] = field(default=None, metadata={"wire_name": "scope"})
    started_at: Optional[str] = field(default=None, metadata={"wire_name": "startedAt"})

CloudTransferTransferMetadata = Dict[str, str]

@dataclass(frozen=True)
class CloudTransferEnqueueUploadRequest:
    local_path: str = field(metadata={"wire_name": "localPath"})
    remote_path: str = field(metadata={"wire_name": "remotePath"})
    content_type: Optional[str] = field(default=None, metadata={"wire_name": "contentType"})
    metadata: Optional[Dict[str, str]] = field(default=None, metadata={"wire_name": "metadata"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    scope: Optional[str] = field(default=None, metadata={"wire_name": "scope"})
    timeout: Optional[str] = field(default=None, metadata={"wire_name": "timeout"})

CloudTransferEnqueueUploadRequestMetadata = Dict[str, str]

@dataclass(frozen=True)
class CloudTransferEnqueueDownloadRequest:
    local_path: str = field(metadata={"wire_name": "localPath"})
    remote_path: str = field(metadata={"wire_name": "remotePath"})
    metadata: Optional[Dict[str, str]] = field(default=None, metadata={"wire_name": "metadata"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    scope: Optional[str] = field(default=None, metadata={"wire_name": "scope"})
    timeout: Optional[str] = field(default=None, metadata={"wire_name": "timeout"})

CloudTransferEnqueueDownloadRequestMetadata = Dict[str, str]

@dataclass(frozen=True)
class CloudTransferGetTransferRequest:
    transfer_id: str = field(metadata={"wire_name": "transferId"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class CloudTransferListTransfersRequest:
    direction: Optional[str] = field(default=None, metadata={"wire_name": "direction"})
    limit: Optional[int] = field(default=None, metadata={"wire_name": "limit"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    state: Optional[str] = field(default=None, metadata={"wire_name": "state"})

@dataclass(frozen=True)
class CloudTransferStatsRequest:
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class CloudTransferTransferPayload:
    transfer: CloudTransferTransfer = field(metadata={"wire_name": "transfer"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class CloudTransferTransferListPayload:
    items: List[CloudTransferTransfer] = field(metadata={"wire_name": "items"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class CloudTransferTransferStatsPayload:
    stats: CloudTransferQueueStats = field(metadata={"wire_name": "stats"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class CloudTransferTransferStatusPayload:
    database_path: str = field(metadata={"wire_name": "databasePath"})
    device_id: str = field(metadata={"wire_name": "deviceId"})
    shared_dir: str = field(metadata={"wire_name": "sharedDir"})
    stats: CloudTransferQueueStats = field(metadata={"wire_name": "stats"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class CloudTransferTransferErrorPayload:
    error: str = field(metadata={"wire_name": "error"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    request_type: Optional[str] = field(default=None, metadata={"wire_name": "requestType"})

def parse_cloud_transfer_queue_stats(payload: Optional[Mapping[str, Any]]) -> CloudTransferQueueStats:
    return convert_value(dict(payload or {}), CloudTransferQueueStats)

def parse_cloud_transfer_transfer(payload: Optional[Mapping[str, Any]]) -> CloudTransferTransfer:
    return convert_value(dict(payload or {}), CloudTransferTransfer)

def parse_cloud_transfer_enqueue_upload_request(payload: Optional[Mapping[str, Any]]) -> CloudTransferEnqueueUploadRequest:
    return convert_value(dict(payload or {}), CloudTransferEnqueueUploadRequest)

def parse_cloud_transfer_enqueue_download_request(payload: Optional[Mapping[str, Any]]) -> CloudTransferEnqueueDownloadRequest:
    return convert_value(dict(payload or {}), CloudTransferEnqueueDownloadRequest)

def parse_cloud_transfer_get_transfer_request(payload: Optional[Mapping[str, Any]]) -> CloudTransferGetTransferRequest:
    return convert_value(dict(payload or {}), CloudTransferGetTransferRequest)

def parse_cloud_transfer_list_transfers_request(payload: Optional[Mapping[str, Any]]) -> CloudTransferListTransfersRequest:
    return convert_value(dict(payload or {}), CloudTransferListTransfersRequest)

def parse_cloud_transfer_stats_request(payload: Optional[Mapping[str, Any]]) -> CloudTransferStatsRequest:
    return convert_value(dict(payload or {}), CloudTransferStatsRequest)

def parse_cloud_transfer_transfer_payload(payload: Optional[Mapping[str, Any]]) -> CloudTransferTransferPayload:
    return convert_value(dict(payload or {}), CloudTransferTransferPayload)

def parse_cloud_transfer_transfer_list_payload(payload: Optional[Mapping[str, Any]]) -> CloudTransferTransferListPayload:
    return convert_value(dict(payload or {}), CloudTransferTransferListPayload)

def parse_cloud_transfer_transfer_stats_payload(payload: Optional[Mapping[str, Any]]) -> CloudTransferTransferStatsPayload:
    return convert_value(dict(payload or {}), CloudTransferTransferStatsPayload)

def parse_cloud_transfer_transfer_status_payload(payload: Optional[Mapping[str, Any]]) -> CloudTransferTransferStatusPayload:
    return convert_value(dict(payload or {}), CloudTransferTransferStatusPayload)

def parse_cloud_transfer_transfer_error_payload(payload: Optional[Mapping[str, Any]]) -> CloudTransferTransferErrorPayload:
    return convert_value(dict(payload or {}), CloudTransferTransferErrorPayload)

class CloudTransferHandler(Protocol):
    def handle_enqueue_upload(self, source_service: str, request: CloudTransferEnqueueUploadRequest) -> None: ...
    def handle_enqueue_download(self, source_service: str, request: CloudTransferEnqueueDownloadRequest) -> None: ...
    def handle_get_transfer(self, source_service: str, request: CloudTransferGetTransferRequest) -> None: ...
    def handle_list_transfers(self, source_service: str, request: CloudTransferListTransfersRequest) -> None: ...
    def handle_get_stats(self, source_service: str, request: CloudTransferStatsRequest) -> None: ...
    def handle_get_status(self, source_service: str, request: CloudTransferStatsRequest) -> None: ...

def dispatch_cloud_transfer(source_service: str, subtopic: str, envelope: Mapping[str, Any], handler: CloudTransferHandler) -> bool:
    normalized_subtopic = str(subtopic or "").strip().strip("/")
    message_type = str(envelope.get("type", "")).strip()
    payload = envelope.get("payload", {})
    if not isinstance(payload, Mapping):
        payload = {}
    if normalized_subtopic == "command" and message_type == CLOUD_TRANSFER_ENQUEUE_UPLOAD_METHOD:
        handler.handle_enqueue_upload(source_service, parse_cloud_transfer_enqueue_upload_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == CLOUD_TRANSFER_ENQUEUE_DOWNLOAD_METHOD:
        handler.handle_enqueue_download(source_service, parse_cloud_transfer_enqueue_download_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == CLOUD_TRANSFER_GET_TRANSFER_METHOD:
        handler.handle_get_transfer(source_service, parse_cloud_transfer_get_transfer_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == CLOUD_TRANSFER_LIST_TRANSFERS_METHOD:
        handler.handle_list_transfers(source_service, parse_cloud_transfer_list_transfers_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == CLOUD_TRANSFER_GET_STATS_METHOD:
        handler.handle_get_stats(source_service, parse_cloud_transfer_stats_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == CLOUD_TRANSFER_GET_STATUS_METHOD:
        handler.handle_get_status(source_service, parse_cloud_transfer_stats_request(payload))
        return True
    return False

class CloudTransferClient:
    def __init__(self, bridge: ServiceRequestBridge, target_service: str = "") -> None:
        self._bridge = bridge
        self._target_service = target_service.strip() or CLOUD_TRANSFER_SERVICE

    def enqueue_upload(self, request: CloudTransferEnqueueUploadRequest, timeout_sec: float = 5.0) -> CloudTransferTransferPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=CLOUD_TRANSFER_ENQUEUE_UPLOAD_METHOD,
            payload=to_wire_value(request),
            expected_types={CLOUD_TRANSFER_TRANSFER_MESSAGE, CLOUD_TRANSFER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == CLOUD_TRANSFER_ERROR_MESSAGE:
            error_payload = parse_cloud_transfer_transfer_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_cloud_transfer_transfer_payload(response['payload'])

    def enqueue_download(self, request: CloudTransferEnqueueDownloadRequest, timeout_sec: float = 5.0) -> CloudTransferTransferPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=CLOUD_TRANSFER_ENQUEUE_DOWNLOAD_METHOD,
            payload=to_wire_value(request),
            expected_types={CLOUD_TRANSFER_TRANSFER_MESSAGE, CLOUD_TRANSFER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == CLOUD_TRANSFER_ERROR_MESSAGE:
            error_payload = parse_cloud_transfer_transfer_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_cloud_transfer_transfer_payload(response['payload'])

    def get_transfer(self, request: CloudTransferGetTransferRequest, timeout_sec: float = 5.0) -> CloudTransferTransferPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=CLOUD_TRANSFER_GET_TRANSFER_METHOD,
            payload=to_wire_value(request),
            expected_types={CLOUD_TRANSFER_TRANSFER_MESSAGE, CLOUD_TRANSFER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == CLOUD_TRANSFER_ERROR_MESSAGE:
            error_payload = parse_cloud_transfer_transfer_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_cloud_transfer_transfer_payload(response['payload'])

    def list_transfers(self, request: CloudTransferListTransfersRequest, timeout_sec: float = 5.0) -> CloudTransferTransferListPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=CLOUD_TRANSFER_LIST_TRANSFERS_METHOD,
            payload=to_wire_value(request),
            expected_types={CLOUD_TRANSFER_LIST_MESSAGE, CLOUD_TRANSFER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == CLOUD_TRANSFER_ERROR_MESSAGE:
            error_payload = parse_cloud_transfer_transfer_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_cloud_transfer_transfer_list_payload(response['payload'])

    def get_stats(self, request: CloudTransferStatsRequest, timeout_sec: float = 5.0) -> CloudTransferTransferStatsPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=CLOUD_TRANSFER_GET_STATS_METHOD,
            payload=to_wire_value(request),
            expected_types={CLOUD_TRANSFER_STATS_MESSAGE, CLOUD_TRANSFER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == CLOUD_TRANSFER_ERROR_MESSAGE:
            error_payload = parse_cloud_transfer_transfer_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_cloud_transfer_transfer_stats_payload(response['payload'])

    def get_status(self, request: CloudTransferStatsRequest, timeout_sec: float = 5.0) -> CloudTransferTransferStatusPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=CLOUD_TRANSFER_GET_STATUS_METHOD,
            payload=to_wire_value(request),
            expected_types={CLOUD_TRANSFER_STATUS_MESSAGE, CLOUD_TRANSFER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == CLOUD_TRANSFER_ERROR_MESSAGE:
            error_payload = parse_cloud_transfer_transfer_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_cloud_transfer_transfer_status_payload(response['payload'])
