# Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Protocol

from trakrai_service_runtime import ServiceRequestBridge

from ._runtime import convert_value, to_wire_value

LIVE_FEED_SERVICE = "live-feed"
LIVE_FEED_START_LIVE_METHOD = "start-live"
LIVE_FEED_START_LIVE_SUBTOPIC = "command"
LIVE_FEED_UPDATE_LIVE_LAYOUT_METHOD = "update-live-layout"
LIVE_FEED_UPDATE_LIVE_LAYOUT_SUBTOPIC = "command"
LIVE_FEED_STOP_LIVE_METHOD = "stop-live"
LIVE_FEED_STOP_LIVE_SUBTOPIC = "command"
LIVE_FEED_SDP_ANSWER_METHOD = "sdp-answer"
LIVE_FEED_SDP_ANSWER_SUBTOPIC = "webrtc/answer"
LIVE_FEED_ICE_CANDIDATE_METHOD = "ice-candidate"
LIVE_FEED_ICE_CANDIDATE_SUBTOPIC = "webrtc/ice"
LIVE_FEED_START_LIVE_ACK_MESSAGE = "start-live-ack"
LIVE_FEED_SDP_OFFER_MESSAGE = "sdp-offer"
LIVE_FEED_LIVE_LAYOUT_UPDATED_MESSAGE = "live-layout-updated"
LIVE_FEED_ICE_CANDIDATE_MESSAGE = "ice-candidate"


@dataclass(frozen=True)
class LiveFeedLiveLayoutRequest:
    camera: Optional[str] = field(default=None, metadata={"wire_name": "camera"})
    camera_name: Optional[str] = field(default=None, metadata={"wire_name": "cameraName"})
    camera_names: Optional[List[str]] = field(default=None, metadata={"wire_name": "cameraNames"})
    frame_source: Optional[str] = field(default=None, metadata={"wire_name": "frameSource"})
    layout_mode: Optional[str] = field(default=None, metadata={"wire_name": "layoutMode"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    session_id: Optional[str] = field(default=None, metadata={"wire_name": "sessionId"})

@dataclass(frozen=True)
class LiveFeedStopLiveRequest:
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    session_id: Optional[str] = field(default=None, metadata={"wire_name": "sessionId"})

@dataclass(frozen=True)
class LiveFeedSdpAnswerRequest:
    sdp: str = field(metadata={"wire_name": "sdp"})
    session_id: str = field(metadata={"wire_name": "sessionId"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

LiveFeedIceCandidateBody = Dict[str, Any]

@dataclass(frozen=True)
class LiveFeedIceCandidateRequest:
    candidate: LiveFeedIceCandidateBody = field(metadata={"wire_name": "candidate"})
    session_id: str = field(metadata={"wire_name": "sessionId"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class LiveFeedStartLiveAckPayload:
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    frame_source: str = field(metadata={"wire_name": "frameSource"})
    ok: bool = field(metadata={"wire_name": "ok"})
    session_id: str = field(metadata={"wire_name": "sessionId"})
    error: Optional[str] = field(default=None, metadata={"wire_name": "error"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class LiveFeedSdpOfferPayload:
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    frame_source: str = field(metadata={"wire_name": "frameSource"})
    sdp: str = field(metadata={"wire_name": "sdp"})
    session_id: str = field(metadata={"wire_name": "sessionId"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class LiveFeedLiveLayoutUpdatedPayload:
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    camera_names: List[str] = field(metadata={"wire_name": "cameraNames"})
    frame_source: str = field(metadata={"wire_name": "frameSource"})
    layout_mode: str = field(metadata={"wire_name": "layoutMode"})
    request_id: str = field(metadata={"wire_name": "requestId"})
    session_id: str = field(metadata={"wire_name": "sessionId"})

@dataclass(frozen=True)
class LiveFeedIceCandidateEventPayload:
    candidate: LiveFeedIceCandidateBody = field(metadata={"wire_name": "candidate"})
    origin: str = field(metadata={"wire_name": "origin"})
    session_id: str = field(metadata={"wire_name": "sessionId"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

def parse_live_feed_live_layout_request(payload: Optional[Mapping[str, Any]]) -> LiveFeedLiveLayoutRequest:
    return convert_value(dict(payload or {}), LiveFeedLiveLayoutRequest)

def parse_live_feed_stop_live_request(payload: Optional[Mapping[str, Any]]) -> LiveFeedStopLiveRequest:
    return convert_value(dict(payload or {}), LiveFeedStopLiveRequest)

def parse_live_feed_sdp_answer_request(payload: Optional[Mapping[str, Any]]) -> LiveFeedSdpAnswerRequest:
    return convert_value(dict(payload or {}), LiveFeedSdpAnswerRequest)

def parse_live_feed_ice_candidate_body(payload: Optional[Mapping[str, Any]]) -> LiveFeedIceCandidateBody:
    return convert_value(dict(payload or {}), LiveFeedIceCandidateBody)

def parse_live_feed_ice_candidate_request(payload: Optional[Mapping[str, Any]]) -> LiveFeedIceCandidateRequest:
    return convert_value(dict(payload or {}), LiveFeedIceCandidateRequest)

def parse_live_feed_start_live_ack_payload(payload: Optional[Mapping[str, Any]]) -> LiveFeedStartLiveAckPayload:
    return convert_value(dict(payload or {}), LiveFeedStartLiveAckPayload)

def parse_live_feed_sdp_offer_payload(payload: Optional[Mapping[str, Any]]) -> LiveFeedSdpOfferPayload:
    return convert_value(dict(payload or {}), LiveFeedSdpOfferPayload)

def parse_live_feed_live_layout_updated_payload(payload: Optional[Mapping[str, Any]]) -> LiveFeedLiveLayoutUpdatedPayload:
    return convert_value(dict(payload or {}), LiveFeedLiveLayoutUpdatedPayload)

def parse_live_feed_ice_candidate_event_payload(payload: Optional[Mapping[str, Any]]) -> LiveFeedIceCandidateEventPayload:
    return convert_value(dict(payload or {}), LiveFeedIceCandidateEventPayload)

class LiveFeedHandler(Protocol):
    def handle_start_live(self, source_service: str, request: LiveFeedLiveLayoutRequest) -> None: ...
    def handle_update_live_layout(self, source_service: str, request: LiveFeedLiveLayoutRequest) -> None: ...
    def handle_stop_live(self, source_service: str, request: LiveFeedStopLiveRequest) -> None: ...
    def handle_sdp_answer(self, source_service: str, request: LiveFeedSdpAnswerRequest) -> None: ...
    def handle_ice_candidate(self, source_service: str, request: LiveFeedIceCandidateRequest) -> None: ...

def dispatch_live_feed(source_service: str, subtopic: str, envelope: Mapping[str, Any], handler: LiveFeedHandler) -> bool:
    normalized_subtopic = str(subtopic or "").strip().strip("/")
    message_type = str(envelope.get("type", "")).strip()
    payload = envelope.get("payload", {})
    if not isinstance(payload, Mapping):
        payload = {}
    if normalized_subtopic == "command" and message_type == LIVE_FEED_START_LIVE_METHOD and message_type == "start":
        handler.handle_start_live(source_service, parse_live_feed_live_layout_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == LIVE_FEED_UPDATE_LIVE_LAYOUT_METHOD:
        handler.handle_update_live_layout(source_service, parse_live_feed_live_layout_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == LIVE_FEED_STOP_LIVE_METHOD and message_type == "stop":
        handler.handle_stop_live(source_service, parse_live_feed_stop_live_request(payload))
        return True
    elif normalized_subtopic == "webrtc/answer" and message_type == LIVE_FEED_SDP_ANSWER_METHOD:
        handler.handle_sdp_answer(source_service, parse_live_feed_sdp_answer_request(payload))
        return True
    elif normalized_subtopic == "webrtc/ice" and message_type == LIVE_FEED_ICE_CANDIDATE_METHOD:
        handler.handle_ice_candidate(source_service, parse_live_feed_ice_candidate_request(payload))
        return True
    return False

class LiveFeedClient:
    def __init__(self, bridge: ServiceRequestBridge, target_service: str = "") -> None:
        self._bridge = bridge
        self._target_service = target_service.strip() or LIVE_FEED_SERVICE

    def start_live(self, request: LiveFeedLiveLayoutRequest, timeout_sec: float = 5.0) -> LiveFeedStartLiveAckPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=LIVE_FEED_START_LIVE_METHOD,
            payload=to_wire_value(request),
            expected_types={LIVE_FEED_START_LIVE_ACK_MESSAGE},
            timeout_sec=timeout_sec,
        )
        return parse_live_feed_start_live_ack_payload(response['payload'])

    def update_live_layout(self, request: LiveFeedLiveLayoutRequest, timeout_sec: float = 5.0) -> LiveFeedLiveLayoutUpdatedPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=LIVE_FEED_UPDATE_LIVE_LAYOUT_METHOD,
            payload=to_wire_value(request),
            expected_types={LIVE_FEED_LIVE_LAYOUT_UPDATED_MESSAGE},
            timeout_sec=timeout_sec,
        )
        return parse_live_feed_live_layout_updated_payload(response['payload'])
