# Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Protocol

from trakrai_service_runtime import ServiceRequestBridge

from ._runtime import convert_value, to_wire_value

PTZ_CONTROL_SERVICE = "ptz-control"
PTZ_CONTROL_GET_STATUS_METHOD = "get-status"
PTZ_CONTROL_GET_STATUS_SUBTOPIC = "command"
PTZ_CONTROL_GET_POSITION_METHOD = "get-position"
PTZ_CONTROL_GET_POSITION_SUBTOPIC = "command"
PTZ_CONTROL_START_MOVE_METHOD = "start-move"
PTZ_CONTROL_START_MOVE_SUBTOPIC = "command"
PTZ_CONTROL_STOP_MOVE_METHOD = "stop-move"
PTZ_CONTROL_STOP_MOVE_SUBTOPIC = "command"
PTZ_CONTROL_SET_ZOOM_METHOD = "set-zoom"
PTZ_CONTROL_SET_ZOOM_SUBTOPIC = "command"
PTZ_CONTROL_SET_POSITION_METHOD = "set-position"
PTZ_CONTROL_SET_POSITION_SUBTOPIC = "command"
PTZ_CONTROL_GO_HOME_METHOD = "go-home"
PTZ_CONTROL_GO_HOME_SUBTOPIC = "command"
PTZ_CONTROL_PTZ_STATUS_MESSAGE = "ptz-status"
PTZ_CONTROL_PTZ_POSITION_MESSAGE = "ptz-position"
PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE = "ptz-command-ack"
PTZ_CONTROL_PTZ_ERROR_MESSAGE = "ptz-error"


@dataclass(frozen=True)
class PtzControlPtzRange:
    max: float = field(metadata={"wire_name": "max"})
    min: float = field(metadata={"wire_name": "min"})

@dataclass(frozen=True)
class PtzControlMoveStatus:
    pan_tilt: Optional[str] = field(default=None, metadata={"wire_name": "panTilt"})
    zoom: Optional[str] = field(default=None, metadata={"wire_name": "zoom"})

@dataclass(frozen=True)
class PtzControlPtzCapabilities:
    can_absolute_pan_tilt: bool = field(metadata={"wire_name": "canAbsolutePanTilt"})
    can_absolute_zoom: bool = field(metadata={"wire_name": "canAbsoluteZoom"})
    can_continuous_pan_tilt: bool = field(metadata={"wire_name": "canContinuousPanTilt"})
    can_continuous_zoom: bool = field(metadata={"wire_name": "canContinuousZoom"})
    can_go_home: bool = field(metadata={"wire_name": "canGoHome"})
    pan_range: Optional[PtzControlPtzRange] = field(default=None, metadata={"wire_name": "panRange"})
    tilt_range: Optional[PtzControlPtzRange] = field(default=None, metadata={"wire_name": "tiltRange"})
    zoom_range: Optional[PtzControlPtzRange] = field(default=None, metadata={"wire_name": "zoomRange"})

@dataclass(frozen=True)
class PtzControlPositionSnapshot:
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    pan: float = field(metadata={"wire_name": "pan"})
    tilt: float = field(metadata={"wire_name": "tilt"})
    updated_at: str = field(metadata={"wire_name": "updatedAt"})
    zoom: float = field(metadata={"wire_name": "zoom"})
    capabilities: Optional[PtzControlPtzCapabilities] = field(default=None, metadata={"wire_name": "capabilities"})
    move_status: Optional[PtzControlMoveStatus] = field(default=None, metadata={"wire_name": "moveStatus"})

@dataclass(frozen=True)
class PtzControlVelocityCommand:
    pan: float = field(metadata={"wire_name": "pan"})
    tilt: float = field(metadata={"wire_name": "tilt"})
    zoom: float = field(metadata={"wire_name": "zoom"})

@dataclass(frozen=True)
class PtzControlStatusPayload:
    configured_cameras: List[str] = field(metadata={"wire_name": "configuredCameras"})
    active_camera: Optional[str] = field(default=None, metadata={"wire_name": "activeCamera"})
    capabilities: Optional[PtzControlPtzCapabilities] = field(default=None, metadata={"wire_name": "capabilities"})
    last_command: Optional[str] = field(default=None, metadata={"wire_name": "lastCommand"})
    last_error: Optional[str] = field(default=None, metadata={"wire_name": "lastError"})
    position: Optional[PtzControlPositionSnapshot] = field(default=None, metadata={"wire_name": "position"})

@dataclass(frozen=True)
class PtzControlStatusResponsePayload:
    configured_cameras: List[str] = field(metadata={"wire_name": "configuredCameras"})
    active_camera: Optional[str] = field(default=None, metadata={"wire_name": "activeCamera"})
    capabilities: Optional[PtzControlPtzCapabilities] = field(default=None, metadata={"wire_name": "capabilities"})
    last_command: Optional[str] = field(default=None, metadata={"wire_name": "lastCommand"})
    last_error: Optional[str] = field(default=None, metadata={"wire_name": "lastError"})
    position: Optional[PtzControlPositionSnapshot] = field(default=None, metadata={"wire_name": "position"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class PtzControlCommandAckPayload:
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    command: str = field(metadata={"wire_name": "command"})
    ok: bool = field(metadata={"wire_name": "ok"})
    capabilities: Optional[PtzControlPtzCapabilities] = field(default=None, metadata={"wire_name": "capabilities"})
    position: Optional[PtzControlPositionSnapshot] = field(default=None, metadata={"wire_name": "position"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    velocity: Optional[PtzControlVelocityCommand] = field(default=None, metadata={"wire_name": "velocity"})

@dataclass(frozen=True)
class PtzControlPositionResponsePayload:
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    pan: float = field(metadata={"wire_name": "pan"})
    tilt: float = field(metadata={"wire_name": "tilt"})
    updated_at: str = field(metadata={"wire_name": "updatedAt"})
    zoom: float = field(metadata={"wire_name": "zoom"})
    capabilities: Optional[PtzControlPtzCapabilities] = field(default=None, metadata={"wire_name": "capabilities"})
    move_status: Optional[PtzControlMoveStatus] = field(default=None, metadata={"wire_name": "moveStatus"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class PtzControlErrorPayload:
    command: str = field(metadata={"wire_name": "command"})
    error: str = field(metadata={"wire_name": "error"})
    camera_name: Optional[str] = field(default=None, metadata={"wire_name": "cameraName"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class PtzControlCameraCommand:
    camera_name: Optional[str] = field(default=None, metadata={"wire_name": "cameraName"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class PtzControlMoveCommand:
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    velocity: PtzControlVelocityCommand = field(metadata={"wire_name": "velocity"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class PtzControlZoomCommand:
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    zoom: float = field(metadata={"wire_name": "zoom"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class PtzControlPositionCommand:
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    pan: float = field(metadata={"wire_name": "pan"})
    tilt: float = field(metadata={"wire_name": "tilt"})
    zoom: float = field(metadata={"wire_name": "zoom"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

def parse_ptz_control_ptz_range(payload: Optional[Mapping[str, Any]]) -> PtzControlPtzRange:
    return convert_value(dict(payload or {}), PtzControlPtzRange)

def parse_ptz_control_move_status(payload: Optional[Mapping[str, Any]]) -> PtzControlMoveStatus:
    return convert_value(dict(payload or {}), PtzControlMoveStatus)

def parse_ptz_control_ptz_capabilities(payload: Optional[Mapping[str, Any]]) -> PtzControlPtzCapabilities:
    return convert_value(dict(payload or {}), PtzControlPtzCapabilities)

def parse_ptz_control_position_snapshot(payload: Optional[Mapping[str, Any]]) -> PtzControlPositionSnapshot:
    return convert_value(dict(payload or {}), PtzControlPositionSnapshot)

def parse_ptz_control_velocity_command(payload: Optional[Mapping[str, Any]]) -> PtzControlVelocityCommand:
    return convert_value(dict(payload or {}), PtzControlVelocityCommand)

def parse_ptz_control_status_payload(payload: Optional[Mapping[str, Any]]) -> PtzControlStatusPayload:
    return convert_value(dict(payload or {}), PtzControlStatusPayload)

def parse_ptz_control_status_response_payload(payload: Optional[Mapping[str, Any]]) -> PtzControlStatusResponsePayload:
    return convert_value(dict(payload or {}), PtzControlStatusResponsePayload)

def parse_ptz_control_command_ack_payload(payload: Optional[Mapping[str, Any]]) -> PtzControlCommandAckPayload:
    return convert_value(dict(payload or {}), PtzControlCommandAckPayload)

def parse_ptz_control_position_response_payload(payload: Optional[Mapping[str, Any]]) -> PtzControlPositionResponsePayload:
    return convert_value(dict(payload or {}), PtzControlPositionResponsePayload)

def parse_ptz_control_error_payload(payload: Optional[Mapping[str, Any]]) -> PtzControlErrorPayload:
    return convert_value(dict(payload or {}), PtzControlErrorPayload)

def parse_ptz_control_camera_command(payload: Optional[Mapping[str, Any]]) -> PtzControlCameraCommand:
    return convert_value(dict(payload or {}), PtzControlCameraCommand)

def parse_ptz_control_move_command(payload: Optional[Mapping[str, Any]]) -> PtzControlMoveCommand:
    return convert_value(dict(payload or {}), PtzControlMoveCommand)

def parse_ptz_control_zoom_command(payload: Optional[Mapping[str, Any]]) -> PtzControlZoomCommand:
    return convert_value(dict(payload or {}), PtzControlZoomCommand)

def parse_ptz_control_position_command(payload: Optional[Mapping[str, Any]]) -> PtzControlPositionCommand:
    return convert_value(dict(payload or {}), PtzControlPositionCommand)

class PtzControlHandler(Protocol):
    def handle_get_status(self, source_service: str, request: PtzControlCameraCommand) -> None: ...
    def handle_get_position(self, source_service: str, request: PtzControlCameraCommand) -> None: ...
    def handle_start_move(self, source_service: str, request: PtzControlMoveCommand) -> None: ...
    def handle_stop_move(self, source_service: str, request: PtzControlCameraCommand) -> None: ...
    def handle_set_zoom(self, source_service: str, request: PtzControlZoomCommand) -> None: ...
    def handle_set_position(self, source_service: str, request: PtzControlPositionCommand) -> None: ...
    def handle_go_home(self, source_service: str, request: PtzControlCameraCommand) -> None: ...

def dispatch_ptz_control(source_service: str, subtopic: str, envelope: Mapping[str, Any], handler: PtzControlHandler) -> bool:
    normalized_subtopic = str(subtopic or "").strip().strip("/")
    message_type = str(envelope.get("type", "")).strip()
    payload = envelope.get("payload", {})
    if not isinstance(payload, Mapping):
        payload = {}
    if normalized_subtopic == "command" and message_type == PTZ_CONTROL_GET_STATUS_METHOD:
        handler.handle_get_status(source_service, parse_ptz_control_camera_command(payload))
        return True
    elif normalized_subtopic == "command" and message_type == PTZ_CONTROL_GET_POSITION_METHOD:
        handler.handle_get_position(source_service, parse_ptz_control_camera_command(payload))
        return True
    elif normalized_subtopic == "command" and message_type == PTZ_CONTROL_START_MOVE_METHOD:
        handler.handle_start_move(source_service, parse_ptz_control_move_command(payload))
        return True
    elif normalized_subtopic == "command" and message_type == PTZ_CONTROL_STOP_MOVE_METHOD:
        handler.handle_stop_move(source_service, parse_ptz_control_camera_command(payload))
        return True
    elif normalized_subtopic == "command" and message_type == PTZ_CONTROL_SET_ZOOM_METHOD:
        handler.handle_set_zoom(source_service, parse_ptz_control_zoom_command(payload))
        return True
    elif normalized_subtopic == "command" and message_type == PTZ_CONTROL_SET_POSITION_METHOD:
        handler.handle_set_position(source_service, parse_ptz_control_position_command(payload))
        return True
    elif normalized_subtopic == "command" and message_type == PTZ_CONTROL_GO_HOME_METHOD:
        handler.handle_go_home(source_service, parse_ptz_control_camera_command(payload))
        return True
    return False

class PtzControlClient:
    def __init__(self, bridge: ServiceRequestBridge, target_service: str = "") -> None:
        self._bridge = bridge
        self._target_service = target_service.strip() or PTZ_CONTROL_SERVICE

    def get_status(self, request: PtzControlCameraCommand, timeout_sec: float = 5.0) -> PtzControlStatusResponsePayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=PTZ_CONTROL_GET_STATUS_METHOD,
            payload=to_wire_value(request),
            expected_types={PTZ_CONTROL_PTZ_STATUS_MESSAGE, PTZ_CONTROL_PTZ_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == PTZ_CONTROL_PTZ_ERROR_MESSAGE:
            error_payload = parse_ptz_control_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_ptz_control_status_response_payload(response['payload'])

    def get_position(self, request: PtzControlCameraCommand, timeout_sec: float = 5.0) -> PtzControlPositionResponsePayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=PTZ_CONTROL_GET_POSITION_METHOD,
            payload=to_wire_value(request),
            expected_types={PTZ_CONTROL_PTZ_POSITION_MESSAGE, PTZ_CONTROL_PTZ_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == PTZ_CONTROL_PTZ_ERROR_MESSAGE:
            error_payload = parse_ptz_control_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_ptz_control_position_response_payload(response['payload'])

    def start_move(self, request: PtzControlMoveCommand, timeout_sec: float = 5.0) -> PtzControlCommandAckPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=PTZ_CONTROL_START_MOVE_METHOD,
            payload=to_wire_value(request),
            expected_types={PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE, PTZ_CONTROL_PTZ_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == PTZ_CONTROL_PTZ_ERROR_MESSAGE:
            error_payload = parse_ptz_control_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_ptz_control_command_ack_payload(response['payload'])

    def stop_move(self, request: PtzControlCameraCommand, timeout_sec: float = 5.0) -> PtzControlCommandAckPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=PTZ_CONTROL_STOP_MOVE_METHOD,
            payload=to_wire_value(request),
            expected_types={PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE, PTZ_CONTROL_PTZ_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == PTZ_CONTROL_PTZ_ERROR_MESSAGE:
            error_payload = parse_ptz_control_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_ptz_control_command_ack_payload(response['payload'])

    def set_zoom(self, request: PtzControlZoomCommand, timeout_sec: float = 5.0) -> PtzControlCommandAckPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=PTZ_CONTROL_SET_ZOOM_METHOD,
            payload=to_wire_value(request),
            expected_types={PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE, PTZ_CONTROL_PTZ_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == PTZ_CONTROL_PTZ_ERROR_MESSAGE:
            error_payload = parse_ptz_control_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_ptz_control_command_ack_payload(response['payload'])

    def set_position(self, request: PtzControlPositionCommand, timeout_sec: float = 5.0) -> PtzControlCommandAckPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=PTZ_CONTROL_SET_POSITION_METHOD,
            payload=to_wire_value(request),
            expected_types={PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE, PTZ_CONTROL_PTZ_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == PTZ_CONTROL_PTZ_ERROR_MESSAGE:
            error_payload = parse_ptz_control_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_ptz_control_command_ack_payload(response['payload'])

    def go_home(self, request: PtzControlCameraCommand, timeout_sec: float = 5.0) -> PtzControlCommandAckPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=PTZ_CONTROL_GO_HOME_METHOD,
            payload=to_wire_value(request),
            expected_types={PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE, PTZ_CONTROL_PTZ_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == PTZ_CONTROL_PTZ_ERROR_MESSAGE:
            error_payload = parse_ptz_control_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_ptz_control_command_ack_payload(response['payload'])
