# Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Protocol

from trakrai_service_runtime import ServiceRequestBridge

from ._runtime import convert_value, to_wire_value

ROI_CONFIG_SERVICE = "roi-config"
ROI_CONFIG_GET_STATUS_METHOD = "get-status"
ROI_CONFIG_GET_STATUS_SUBTOPIC = "command"
ROI_CONFIG_GET_CONFIG_METHOD = "get-config"
ROI_CONFIG_GET_CONFIG_SUBTOPIC = "command"
ROI_CONFIG_SAVE_CONFIG_METHOD = "save-config"
ROI_CONFIG_SAVE_CONFIG_SUBTOPIC = "command"
ROI_CONFIG_STATUS_MESSAGE = "roi-config-status"
ROI_CONFIG_DOCUMENT_MESSAGE = "roi-config-document"
ROI_CONFIG_ERROR_MESSAGE = "roi-config-error"


@dataclass(frozen=True)
class RoiConfigRequestEnvelope:
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RoiConfigROIBox:
    height: float = field(metadata={"wire_name": "height"})
    width: float = field(metadata={"wire_name": "width"})
    x: float = field(metadata={"wire_name": "x"})
    y: float = field(metadata={"wire_name": "y"})

@dataclass(frozen=True)
class RoiConfigPTZPosition:
    pan: float = field(metadata={"wire_name": "pan"})
    tilt: float = field(metadata={"wire_name": "tilt"})
    zoom: float = field(metadata={"wire_name": "zoom"})

@dataclass(frozen=True)
class RoiConfigROIBoxSpec:
    active: bool = field(metadata={"wire_name": "active"})
    bounds: RoiConfigROIBox = field(metadata={"wire_name": "bounds"})
    id: str = field(metadata={"wire_name": "id"})
    name: str = field(metadata={"wire_name": "name"})
    color: Optional[str] = field(default=None, metadata={"wire_name": "color"})
    tags: Optional[List[str]] = field(default=None, metadata={"wire_name": "tags"})

@dataclass(frozen=True)
class RoiConfigBaseLocation:
    active: bool = field(metadata={"wire_name": "active"})
    id: str = field(metadata={"wire_name": "id"})
    name: str = field(metadata={"wire_name": "name"})
    ptz: RoiConfigPTZPosition = field(metadata={"wire_name": "ptz"})
    rois: List[RoiConfigROIBoxSpec] = field(metadata={"wire_name": "rois"})

@dataclass(frozen=True)
class RoiConfigCameraROIConfig:
    base_locations: List[RoiConfigBaseLocation] = field(metadata={"wire_name": "baseLocations"})
    camera_name: str = field(metadata={"wire_name": "cameraName"})

@dataclass(frozen=True)
class RoiConfigDocument:
    cameras: List[RoiConfigCameraROIConfig] = field(metadata={"wire_name": "cameras"})
    version: int = field(metadata={"wire_name": "version"})
    updated_at: Optional[str] = field(default=None, metadata={"wire_name": "updatedAt"})

@dataclass(frozen=True)
class RoiConfigStatusPayload:
    base_location_count: int = field(metadata={"wire_name": "baseLocationCount"})
    camera_count: int = field(metadata={"wire_name": "cameraCount"})
    document_hash: str = field(metadata={"wire_name": "documentHash"})
    file_path: str = field(metadata={"wire_name": "filePath"})
    roi_box_count: int = field(metadata={"wire_name": "roiBoxCount"})
    updated_at: Optional[str] = field(default=None, metadata={"wire_name": "updatedAt"})

@dataclass(frozen=True)
class RoiConfigStatusResponsePayload:
    base_location_count: int = field(metadata={"wire_name": "baseLocationCount"})
    camera_count: int = field(metadata={"wire_name": "cameraCount"})
    document_hash: str = field(metadata={"wire_name": "documentHash"})
    file_path: str = field(metadata={"wire_name": "filePath"})
    roi_box_count: int = field(metadata={"wire_name": "roiBoxCount"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    updated_at: Optional[str] = field(default=None, metadata={"wire_name": "updatedAt"})

@dataclass(frozen=True)
class RoiConfigGetConfigPayload:
    document: RoiConfigDocument = field(metadata={"wire_name": "document"})
    file_path: str = field(metadata={"wire_name": "filePath"})
    base_location_count: int = field(metadata={"wire_name": "baseLocationCount"})
    camera_count: int = field(metadata={"wire_name": "cameraCount"})
    document_hash: str = field(metadata={"wire_name": "documentHash"})
    roi_box_count: int = field(metadata={"wire_name": "roiBoxCount"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    updated_at: Optional[str] = field(default=None, metadata={"wire_name": "updatedAt"})

@dataclass(frozen=True)
class RoiConfigSaveConfigRequest:
    document: RoiConfigDocument = field(metadata={"wire_name": "document"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RoiConfigErrorPayload:
    error: str = field(metadata={"wire_name": "error"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    request_type: Optional[str] = field(default=None, metadata={"wire_name": "requestType"})

def parse_roi_config_request_envelope(payload: Optional[Mapping[str, Any]]) -> RoiConfigRequestEnvelope:
    return convert_value(dict(payload or {}), RoiConfigRequestEnvelope)

def parse_roi_config_roibox(payload: Optional[Mapping[str, Any]]) -> RoiConfigROIBox:
    return convert_value(dict(payload or {}), RoiConfigROIBox)

def parse_roi_config_ptzposition(payload: Optional[Mapping[str, Any]]) -> RoiConfigPTZPosition:
    return convert_value(dict(payload or {}), RoiConfigPTZPosition)

def parse_roi_config_roibox_spec(payload: Optional[Mapping[str, Any]]) -> RoiConfigROIBoxSpec:
    return convert_value(dict(payload or {}), RoiConfigROIBoxSpec)

def parse_roi_config_base_location(payload: Optional[Mapping[str, Any]]) -> RoiConfigBaseLocation:
    return convert_value(dict(payload or {}), RoiConfigBaseLocation)

def parse_roi_config_camera_roiconfig(payload: Optional[Mapping[str, Any]]) -> RoiConfigCameraROIConfig:
    return convert_value(dict(payload or {}), RoiConfigCameraROIConfig)

def parse_roi_config_document(payload: Optional[Mapping[str, Any]]) -> RoiConfigDocument:
    return convert_value(dict(payload or {}), RoiConfigDocument)

def parse_roi_config_status_payload(payload: Optional[Mapping[str, Any]]) -> RoiConfigStatusPayload:
    return convert_value(dict(payload or {}), RoiConfigStatusPayload)

def parse_roi_config_status_response_payload(payload: Optional[Mapping[str, Any]]) -> RoiConfigStatusResponsePayload:
    return convert_value(dict(payload or {}), RoiConfigStatusResponsePayload)

def parse_roi_config_get_config_payload(payload: Optional[Mapping[str, Any]]) -> RoiConfigGetConfigPayload:
    return convert_value(dict(payload or {}), RoiConfigGetConfigPayload)

def parse_roi_config_save_config_request(payload: Optional[Mapping[str, Any]]) -> RoiConfigSaveConfigRequest:
    return convert_value(dict(payload or {}), RoiConfigSaveConfigRequest)

def parse_roi_config_error_payload(payload: Optional[Mapping[str, Any]]) -> RoiConfigErrorPayload:
    return convert_value(dict(payload or {}), RoiConfigErrorPayload)

class RoiConfigHandler(Protocol):
    def handle_get_status(self, source_service: str, request: RoiConfigRequestEnvelope) -> None: ...
    def handle_get_config(self, source_service: str, request: RoiConfigRequestEnvelope) -> None: ...
    def handle_save_config(self, source_service: str, request: RoiConfigSaveConfigRequest) -> None: ...

def dispatch_roi_config(source_service: str, subtopic: str, envelope: Mapping[str, Any], handler: RoiConfigHandler) -> bool:
    normalized_subtopic = str(subtopic or "").strip().strip("/")
    message_type = str(envelope.get("type", "")).strip()
    payload = envelope.get("payload", {})
    if not isinstance(payload, Mapping):
        payload = {}
    if normalized_subtopic == "command" and message_type == ROI_CONFIG_GET_STATUS_METHOD:
        handler.handle_get_status(source_service, parse_roi_config_request_envelope(payload))
        return True
    elif normalized_subtopic == "command" and message_type == ROI_CONFIG_GET_CONFIG_METHOD:
        handler.handle_get_config(source_service, parse_roi_config_request_envelope(payload))
        return True
    elif normalized_subtopic == "command" and message_type == ROI_CONFIG_SAVE_CONFIG_METHOD:
        handler.handle_save_config(source_service, parse_roi_config_save_config_request(payload))
        return True
    return False

class RoiConfigClient:
    def __init__(self, bridge: ServiceRequestBridge, target_service: str = "") -> None:
        self._bridge = bridge
        self._target_service = target_service.strip() or ROI_CONFIG_SERVICE

    def get_status(self, request: RoiConfigRequestEnvelope, timeout_sec: float = 5.0) -> RoiConfigStatusResponsePayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=ROI_CONFIG_GET_STATUS_METHOD,
            payload=to_wire_value(request),
            expected_types={ROI_CONFIG_STATUS_MESSAGE, ROI_CONFIG_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == ROI_CONFIG_ERROR_MESSAGE:
            error_payload = parse_roi_config_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_roi_config_status_response_payload(response['payload'])

    def get_config(self, request: RoiConfigRequestEnvelope, timeout_sec: float = 5.0) -> RoiConfigGetConfigPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=ROI_CONFIG_GET_CONFIG_METHOD,
            payload=to_wire_value(request),
            expected_types={ROI_CONFIG_DOCUMENT_MESSAGE, ROI_CONFIG_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == ROI_CONFIG_ERROR_MESSAGE:
            error_payload = parse_roi_config_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_roi_config_get_config_payload(response['payload'])

    def save_config(self, request: RoiConfigSaveConfigRequest, timeout_sec: float = 5.0) -> RoiConfigGetConfigPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=ROI_CONFIG_SAVE_CONFIG_METHOD,
            payload=to_wire_value(request),
            expected_types={ROI_CONFIG_DOCUMENT_MESSAGE, ROI_CONFIG_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == ROI_CONFIG_ERROR_MESSAGE:
            error_payload = parse_roi_config_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_roi_config_get_config_payload(response['payload'])
