# Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Protocol

from trakrai_service_runtime import ServiceRequestBridge

from ._runtime import convert_value, to_wire_value

RUNTIME_MANAGER_SERVICE = "runtime-manager"
RUNTIME_MANAGER_GET_STATUS_METHOD = "get-status"
RUNTIME_MANAGER_GET_STATUS_SUBTOPIC = "command"
RUNTIME_MANAGER_GET_CONFIG_METHOD = "get-config"
RUNTIME_MANAGER_GET_CONFIG_SUBTOPIC = "command"
RUNTIME_MANAGER_LIST_CONFIGS_METHOD = "list-configs"
RUNTIME_MANAGER_LIST_CONFIGS_SUBTOPIC = "command"
RUNTIME_MANAGER_GET_SERVICE_DEFINITION_METHOD = "get-service-definition"
RUNTIME_MANAGER_GET_SERVICE_DEFINITION_SUBTOPIC = "command"
RUNTIME_MANAGER_GET_SERVICE_LOG_METHOD = "get-service-log"
RUNTIME_MANAGER_GET_SERVICE_LOG_SUBTOPIC = "command"
RUNTIME_MANAGER_PUT_CONFIG_METHOD = "put-config"
RUNTIME_MANAGER_PUT_CONFIG_SUBTOPIC = "command"
RUNTIME_MANAGER_PUT_RUNTIME_FILE_METHOD = "put-runtime-file"
RUNTIME_MANAGER_PUT_RUNTIME_FILE_SUBTOPIC = "command"
RUNTIME_MANAGER_REMOVE_SERVICE_METHOD = "remove-service"
RUNTIME_MANAGER_REMOVE_SERVICE_SUBTOPIC = "command"
RUNTIME_MANAGER_RESTART_SERVICE_METHOD = "restart-service"
RUNTIME_MANAGER_RESTART_SERVICE_SUBTOPIC = "command"
RUNTIME_MANAGER_START_SERVICE_METHOD = "start-service"
RUNTIME_MANAGER_START_SERVICE_SUBTOPIC = "command"
RUNTIME_MANAGER_STOP_SERVICE_METHOD = "stop-service"
RUNTIME_MANAGER_STOP_SERVICE_SUBTOPIC = "command"
RUNTIME_MANAGER_UPDATE_SERVICE_METHOD = "update-service"
RUNTIME_MANAGER_UPDATE_SERVICE_SUBTOPIC = "command"
RUNTIME_MANAGER_UPSERT_SERVICE_METHOD = "upsert-service"
RUNTIME_MANAGER_UPSERT_SERVICE_SUBTOPIC = "command"
RUNTIME_MANAGER_STATUS_MESSAGE = "runtime-manager-status"
RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE = "runtime-manager-service-action"
RUNTIME_MANAGER_SERVICE_DEFINITION_MESSAGE = "runtime-manager-service-definition"
RUNTIME_MANAGER_LOG_MESSAGE = "runtime-manager-log"
RUNTIME_MANAGER_ERROR_MESSAGE = "runtime-manager-error"
RUNTIME_MANAGER_CONFIG_LIST_MESSAGE = "runtime-manager-config-list"
RUNTIME_MANAGER_CONFIG_MESSAGE = "runtime-manager-config"
RUNTIME_MANAGER_FILE_MESSAGE = "runtime-manager-file"
RUNTIME_MANAGER_UPDATE_MESSAGE = "runtime-manager-update"


@dataclass(frozen=True)
class RuntimeManagerRuntimeCPUStats:
    core_count: int = field(metadata={"wire_name": "coreCount"})
    usage_percent: Optional[float] = field(default=None, metadata={"wire_name": "usagePercent"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeLoadStats:
    fifteen_minute: Optional[float] = field(default=None, metadata={"wire_name": "fifteenMinute"})
    five_minute: Optional[float] = field(default=None, metadata={"wire_name": "fiveMinute"})
    one_minute: Optional[float] = field(default=None, metadata={"wire_name": "oneMinute"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeMemoryStats:
    available_bytes: Optional[int] = field(default=None, metadata={"wire_name": "availableBytes"})
    swap_total_bytes: Optional[int] = field(default=None, metadata={"wire_name": "swapTotalBytes"})
    swap_used_bytes: Optional[int] = field(default=None, metadata={"wire_name": "swapUsedBytes"})
    total_bytes: Optional[int] = field(default=None, metadata={"wire_name": "totalBytes"})
    used_bytes: Optional[int] = field(default=None, metadata={"wire_name": "usedBytes"})
    used_percent: Optional[float] = field(default=None, metadata={"wire_name": "usedPercent"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeDiskStats:
    label: str = field(metadata={"wire_name": "label"})
    path: str = field(metadata={"wire_name": "path"})
    free_bytes: Optional[int] = field(default=None, metadata={"wire_name": "freeBytes"})
    total_bytes: Optional[int] = field(default=None, metadata={"wire_name": "totalBytes"})
    used_bytes: Optional[int] = field(default=None, metadata={"wire_name": "usedBytes"})
    used_percent: Optional[float] = field(default=None, metadata={"wire_name": "usedPercent"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeNetworkInterfaceStats:
    name: str = field(metadata={"wire_name": "name"})
    rx_bytes: Optional[int] = field(default=None, metadata={"wire_name": "rxBytes"})
    rx_bytes_per_second: Optional[float] = field(default=None, metadata={"wire_name": "rxBytesPerSecond"})
    tx_bytes: Optional[int] = field(default=None, metadata={"wire_name": "txBytes"})
    tx_bytes_per_second: Optional[float] = field(default=None, metadata={"wire_name": "txBytesPerSecond"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeNetworkStats:
    interfaces: Optional[List[RuntimeManagerRuntimeNetworkInterfaceStats]] = field(default=None, metadata={"wire_name": "interfaces"})
    rx_bytes: Optional[int] = field(default=None, metadata={"wire_name": "rxBytes"})
    rx_bytes_per_second: Optional[float] = field(default=None, metadata={"wire_name": "rxBytesPerSecond"})
    tx_bytes: Optional[int] = field(default=None, metadata={"wire_name": "txBytes"})
    tx_bytes_per_second: Optional[float] = field(default=None, metadata={"wire_name": "txBytesPerSecond"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeGPUStats:
    source: str = field(metadata={"wire_name": "source"})
    decoder_utilization_percent: Optional[float] = field(default=None, metadata={"wire_name": "decoderUtilizationPercent"})
    encoder_utilization_percent: Optional[float] = field(default=None, metadata={"wire_name": "encoderUtilizationPercent"})
    memory_total_bytes: Optional[int] = field(default=None, metadata={"wire_name": "memoryTotalBytes"})
    memory_used_bytes: Optional[int] = field(default=None, metadata={"wire_name": "memoryUsedBytes"})
    temperature_celsius: Optional[float] = field(default=None, metadata={"wire_name": "temperatureCelsius"})
    utilization_percent: Optional[float] = field(default=None, metadata={"wire_name": "utilizationPercent"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeSystemSnapshot:
    collected_at: str = field(metadata={"wire_name": "collectedAt"})
    cpu: RuntimeManagerRuntimeCPUStats = field(metadata={"wire_name": "cpu"})
    load: RuntimeManagerRuntimeLoadStats = field(metadata={"wire_name": "load"})
    memory: RuntimeManagerRuntimeMemoryStats = field(metadata={"wire_name": "memory"})
    network: RuntimeManagerRuntimeNetworkStats = field(metadata={"wire_name": "network"})
    disks: Optional[List[RuntimeManagerRuntimeDiskStats]] = field(default=None, metadata={"wire_name": "disks"})
    gpu: Optional[RuntimeManagerRuntimeGPUStats] = field(default=None, metadata={"wire_name": "gpu"})
    uptime_seconds: Optional[float] = field(default=None, metadata={"wire_name": "uptimeSeconds"})

@dataclass(frozen=True)
class RuntimeManagerManagedServiceSnapshot:
    allow_control: bool = field(metadata={"wire_name": "allowControl"})
    allow_update: bool = field(metadata={"wire_name": "allowUpdate"})
    core: bool = field(metadata={"wire_name": "core"})
    display_name: str = field(metadata={"wire_name": "displayName"})
    enabled: bool = field(metadata={"wire_name": "enabled"})
    kind: str = field(metadata={"wire_name": "kind"})
    name: str = field(metadata={"wire_name": "name"})
    state: str = field(metadata={"wire_name": "state"})
    active_state: Optional[str] = field(default=None, metadata={"wire_name": "activeState"})
    cpu_percent: Optional[float] = field(default=None, metadata={"wire_name": "cpuPercent"})
    description: Optional[str] = field(default=None, metadata={"wire_name": "description"})
    install_path: Optional[str] = field(default=None, metadata={"wire_name": "installPath"})
    load_state: Optional[str] = field(default=None, metadata={"wire_name": "loadState"})
    log_path: Optional[str] = field(default=None, metadata={"wire_name": "logPath"})
    main_pid: Optional[int] = field(default=None, metadata={"wire_name": "mainPid"})
    memory_bytes: Optional[int] = field(default=None, metadata={"wire_name": "memoryBytes"})
    message: Optional[str] = field(default=None, metadata={"wire_name": "message"})
    process_elapsed: Optional[str] = field(default=None, metadata={"wire_name": "processElapsed"})
    script_path: Optional[str] = field(default=None, metadata={"wire_name": "scriptPath"})
    sub_state: Optional[str] = field(default=None, metadata={"wire_name": "subState"})
    systemd_unit: Optional[str] = field(default=None, metadata={"wire_name": "systemdUnit"})
    unit_file_state: Optional[str] = field(default=None, metadata={"wire_name": "unitFileState"})
    version: Optional[str] = field(default=None, metadata={"wire_name": "version"})
    version_file: Optional[str] = field(default=None, metadata={"wire_name": "versionFile"})
    version_source: Optional[str] = field(default=None, metadata={"wire_name": "versionSource"})
    version_updated_at: Optional[str] = field(default=None, metadata={"wire_name": "versionUpdatedAt"})
    working_directory: Optional[str] = field(default=None, metadata={"wire_name": "workingDirectory"})

@dataclass(frozen=True)
class RuntimeManagerManagedServiceDefinition:
    allow_control: bool = field(metadata={"wire_name": "allowControl"})
    allow_update: bool = field(metadata={"wire_name": "allowUpdate"})
    core: bool = field(metadata={"wire_name": "core"})
    enabled: bool = field(metadata={"wire_name": "enabled"})
    name: str = field(metadata={"wire_name": "name"})
    after: Optional[List[str]] = field(default=None, metadata={"wire_name": "after"})
    description: Optional[str] = field(default=None, metadata={"wire_name": "description"})
    display_name: Optional[str] = field(default=None, metadata={"wire_name": "displayName"})
    environment: Optional[Dict[str, str]] = field(default=None, metadata={"wire_name": "environment"})
    environment_files: Optional[List[str]] = field(default=None, metadata={"wire_name": "environmentFiles"})
    exec_start: Optional[List[str]] = field(default=None, metadata={"wire_name": "execStart"})
    group: Optional[str] = field(default=None, metadata={"wire_name": "group"})
    install_path: Optional[str] = field(default=None, metadata={"wire_name": "installPath"})
    kind: Optional[str] = field(default=None, metadata={"wire_name": "kind"})
    log_path: Optional[str] = field(default=None, metadata={"wire_name": "logPath"})
    requires: Optional[List[str]] = field(default=None, metadata={"wire_name": "requires"})
    restart: Optional[str] = field(default=None, metadata={"wire_name": "restart"})
    restart_sec: Optional[int] = field(default=None, metadata={"wire_name": "restartSec"})
    script_path: Optional[str] = field(default=None, metadata={"wire_name": "scriptPath"})
    setup_command: Optional[List[str]] = field(default=None, metadata={"wire_name": "setupCommand"})
    systemd_unit: Optional[str] = field(default=None, metadata={"wire_name": "systemdUnit"})
    user: Optional[str] = field(default=None, metadata={"wire_name": "user"})
    version_command: Optional[List[str]] = field(default=None, metadata={"wire_name": "versionCommand"})
    version_file: Optional[str] = field(default=None, metadata={"wire_name": "versionFile"})
    wanted_by: Optional[str] = field(default=None, metadata={"wire_name": "wantedBy"})
    working_directory: Optional[str] = field(default=None, metadata={"wire_name": "workingDirectory"})

RuntimeManagerManagedServiceDefinitionEnvironment = Dict[str, str]

@dataclass(frozen=True)
class RuntimeManagerRuntimeConfigEntry:
    name: str = field(metadata={"wire_name": "name"})
    path: str = field(metadata={"wire_name": "path"})
    consumers: Optional[List[str]] = field(default=None, metadata={"wire_name": "consumers"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeStatusPayload:
    binary_dir: str = field(metadata={"wire_name": "binaryDir"})
    config_dir: str = field(metadata={"wire_name": "configDir"})
    core_count: int = field(metadata={"wire_name": "coreCount"})
    download_dir: str = field(metadata={"wire_name": "downloadDir"})
    generated_at: str = field(metadata={"wire_name": "generatedAt"})
    log_dir: str = field(metadata={"wire_name": "logDir"})
    managed_count: int = field(metadata={"wire_name": "managedCount"})
    script_dir: str = field(metadata={"wire_name": "scriptDir"})
    services: List[RuntimeManagerManagedServiceSnapshot] = field(metadata={"wire_name": "services"})
    shared_dir: str = field(metadata={"wire_name": "sharedDir"})
    state_file: str = field(metadata={"wire_name": "stateFile"})
    system: RuntimeManagerRuntimeSystemSnapshot = field(metadata={"wire_name": "system"})
    version_dir: str = field(metadata={"wire_name": "versionDir"})
    last_action: Optional[str] = field(default=None, metadata={"wire_name": "lastAction"})
    last_error: Optional[str] = field(default=None, metadata={"wire_name": "lastError"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeActionPayload:
    action: str = field(metadata={"wire_name": "action"})
    service_name: str = field(metadata={"wire_name": "serviceName"})
    definition: Optional[RuntimeManagerManagedServiceDefinition] = field(default=None, metadata={"wire_name": "definition"})
    message: Optional[str] = field(default=None, metadata={"wire_name": "message"})
    removed: Optional[bool] = field(default=None, metadata={"wire_name": "removed"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    service: Optional[RuntimeManagerManagedServiceSnapshot] = field(default=None, metadata={"wire_name": "service"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeDefinitionPayload:
    definition: RuntimeManagerManagedServiceDefinition = field(metadata={"wire_name": "definition"})
    service_name: str = field(metadata={"wire_name": "serviceName"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeLogPayload:
    lines: List[str] = field(metadata={"wire_name": "lines"})
    service_name: str = field(metadata={"wire_name": "serviceName"})
    truncated: bool = field(metadata={"wire_name": "truncated"})
    log_path: Optional[str] = field(default=None, metadata={"wire_name": "logPath"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeErrorPayload:
    error: str = field(metadata={"wire_name": "error"})
    action: Optional[str] = field(default=None, metadata={"wire_name": "action"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    service_name: Optional[str] = field(default=None, metadata={"wire_name": "serviceName"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeConfigListPayload:
    configs: List[RuntimeManagerRuntimeConfigEntry] = field(metadata={"wire_name": "configs"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerRuntimeConfigPayload:
    config: RuntimeManagerRuntimeConfigEntry = field(metadata={"wire_name": "config"})
    content: Optional[Dict[str, Any]] = field(default=None, metadata={"wire_name": "content"})
    message: Optional[str] = field(default=None, metadata={"wire_name": "message"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    restarted_services: Optional[List[str]] = field(default=None, metadata={"wire_name": "restartedServices"})

RuntimeManagerRuntimeConfigPayloadContent = Dict[str, Any]

@dataclass(frozen=True)
class RuntimeManagerRuntimeFilePayload:
    path: str = field(metadata={"wire_name": "path"})
    message: Optional[str] = field(default=None, metadata={"wire_name": "message"})
    mode: Optional[int] = field(default=None, metadata={"wire_name": "mode"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerServiceRequest:
    service_name: str = field(metadata={"wire_name": "serviceName"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerLogRequest:
    service_name: str = field(metadata={"wire_name": "serviceName"})
    lines: Optional[int] = field(default=None, metadata={"wire_name": "lines"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerUpdateServiceRequest:
    service_name: str = field(metadata={"wire_name": "serviceName"})
    artifact_sha256: Optional[str] = field(default=None, metadata={"wire_name": "artifactSha256"})
    local_path: Optional[str] = field(default=None, metadata={"wire_name": "localPath"})
    remote_path: Optional[str] = field(default=None, metadata={"wire_name": "remotePath"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerUpsertServiceRequest:
    definition: RuntimeManagerManagedServiceDefinition = field(metadata={"wire_name": "definition"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerRemoveServiceRequest:
    service_name: str = field(metadata={"wire_name": "serviceName"})
    purge_files: Optional[bool] = field(default=None, metadata={"wire_name": "purgeFiles"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerConfigListRequest:
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerConfigRequest:
    config_name: str = field(metadata={"wire_name": "configName"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class RuntimeManagerPutConfigRequest:
    config_name: str = field(metadata={"wire_name": "configName"})
    content: Dict[str, Any] = field(metadata={"wire_name": "content"})
    create_if_missing: Optional[bool] = field(default=None, metadata={"wire_name": "createIfMissing"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    restart_services: Optional[List[str]] = field(default=None, metadata={"wire_name": "restartServices"})

RuntimeManagerPutConfigRequestContent = Dict[str, Any]

@dataclass(frozen=True)
class RuntimeManagerPutRuntimeFileRequest:
    content: str = field(metadata={"wire_name": "content"})
    path: str = field(metadata={"wire_name": "path"})
    mode: Optional[int] = field(default=None, metadata={"wire_name": "mode"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

def parse_runtime_manager_runtime_cpustats(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeCPUStats:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeCPUStats)

def parse_runtime_manager_runtime_load_stats(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeLoadStats:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeLoadStats)

def parse_runtime_manager_runtime_memory_stats(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeMemoryStats:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeMemoryStats)

def parse_runtime_manager_runtime_disk_stats(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeDiskStats:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeDiskStats)

def parse_runtime_manager_runtime_network_interface_stats(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeNetworkInterfaceStats:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeNetworkInterfaceStats)

def parse_runtime_manager_runtime_network_stats(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeNetworkStats:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeNetworkStats)

def parse_runtime_manager_runtime_gpustats(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeGPUStats:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeGPUStats)

def parse_runtime_manager_runtime_system_snapshot(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeSystemSnapshot:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeSystemSnapshot)

def parse_runtime_manager_managed_service_snapshot(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerManagedServiceSnapshot:
    return convert_value(dict(payload or {}), RuntimeManagerManagedServiceSnapshot)

def parse_runtime_manager_managed_service_definition(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerManagedServiceDefinition:
    return convert_value(dict(payload or {}), RuntimeManagerManagedServiceDefinition)

def parse_runtime_manager_runtime_config_entry(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeConfigEntry:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeConfigEntry)

def parse_runtime_manager_runtime_status_payload(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeStatusPayload:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeStatusPayload)

def parse_runtime_manager_runtime_action_payload(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeActionPayload:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeActionPayload)

def parse_runtime_manager_runtime_definition_payload(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeDefinitionPayload:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeDefinitionPayload)

def parse_runtime_manager_runtime_log_payload(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeLogPayload:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeLogPayload)

def parse_runtime_manager_runtime_error_payload(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeErrorPayload:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeErrorPayload)

def parse_runtime_manager_runtime_config_list_payload(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeConfigListPayload:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeConfigListPayload)

def parse_runtime_manager_runtime_config_payload(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeConfigPayload:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeConfigPayload)

def parse_runtime_manager_runtime_file_payload(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRuntimeFilePayload:
    return convert_value(dict(payload or {}), RuntimeManagerRuntimeFilePayload)

def parse_runtime_manager_service_request(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerServiceRequest:
    return convert_value(dict(payload or {}), RuntimeManagerServiceRequest)

def parse_runtime_manager_log_request(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerLogRequest:
    return convert_value(dict(payload or {}), RuntimeManagerLogRequest)

def parse_runtime_manager_update_service_request(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerUpdateServiceRequest:
    return convert_value(dict(payload or {}), RuntimeManagerUpdateServiceRequest)

def parse_runtime_manager_upsert_service_request(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerUpsertServiceRequest:
    return convert_value(dict(payload or {}), RuntimeManagerUpsertServiceRequest)

def parse_runtime_manager_remove_service_request(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerRemoveServiceRequest:
    return convert_value(dict(payload or {}), RuntimeManagerRemoveServiceRequest)

def parse_runtime_manager_config_list_request(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerConfigListRequest:
    return convert_value(dict(payload or {}), RuntimeManagerConfigListRequest)

def parse_runtime_manager_config_request(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerConfigRequest:
    return convert_value(dict(payload or {}), RuntimeManagerConfigRequest)

def parse_runtime_manager_put_config_request(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerPutConfigRequest:
    return convert_value(dict(payload or {}), RuntimeManagerPutConfigRequest)

def parse_runtime_manager_put_runtime_file_request(payload: Optional[Mapping[str, Any]]) -> RuntimeManagerPutRuntimeFileRequest:
    return convert_value(dict(payload or {}), RuntimeManagerPutRuntimeFileRequest)

class RuntimeManagerHandler(Protocol):
    def handle_get_status(self, source_service: str, request: RuntimeManagerConfigListRequest) -> None: ...
    def handle_get_config(self, source_service: str, request: RuntimeManagerConfigRequest) -> None: ...
    def handle_list_configs(self, source_service: str, request: RuntimeManagerConfigListRequest) -> None: ...
    def handle_get_service_definition(self, source_service: str, request: RuntimeManagerServiceRequest) -> None: ...
    def handle_get_service_log(self, source_service: str, request: RuntimeManagerLogRequest) -> None: ...
    def handle_put_config(self, source_service: str, request: RuntimeManagerPutConfigRequest) -> None: ...
    def handle_put_runtime_file(self, source_service: str, request: RuntimeManagerPutRuntimeFileRequest) -> None: ...
    def handle_remove_service(self, source_service: str, request: RuntimeManagerRemoveServiceRequest) -> None: ...
    def handle_restart_service(self, source_service: str, request: RuntimeManagerServiceRequest) -> None: ...
    def handle_start_service(self, source_service: str, request: RuntimeManagerServiceRequest) -> None: ...
    def handle_stop_service(self, source_service: str, request: RuntimeManagerServiceRequest) -> None: ...
    def handle_update_service(self, source_service: str, request: RuntimeManagerUpdateServiceRequest) -> None: ...
    def handle_upsert_service(self, source_service: str, request: RuntimeManagerUpsertServiceRequest) -> None: ...

def dispatch_runtime_manager(source_service: str, subtopic: str, envelope: Mapping[str, Any], handler: RuntimeManagerHandler) -> bool:
    normalized_subtopic = str(subtopic or "").strip().strip("/")
    message_type = str(envelope.get("type", "")).strip()
    payload = envelope.get("payload", {})
    if not isinstance(payload, Mapping):
        payload = {}
    if normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_GET_STATUS_METHOD:
        handler.handle_get_status(source_service, parse_runtime_manager_config_list_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_GET_CONFIG_METHOD:
        handler.handle_get_config(source_service, parse_runtime_manager_config_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_LIST_CONFIGS_METHOD:
        handler.handle_list_configs(source_service, parse_runtime_manager_config_list_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_GET_SERVICE_DEFINITION_METHOD:
        handler.handle_get_service_definition(source_service, parse_runtime_manager_service_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_GET_SERVICE_LOG_METHOD:
        handler.handle_get_service_log(source_service, parse_runtime_manager_log_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_PUT_CONFIG_METHOD:
        handler.handle_put_config(source_service, parse_runtime_manager_put_config_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_PUT_RUNTIME_FILE_METHOD:
        handler.handle_put_runtime_file(source_service, parse_runtime_manager_put_runtime_file_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_REMOVE_SERVICE_METHOD:
        handler.handle_remove_service(source_service, parse_runtime_manager_remove_service_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_RESTART_SERVICE_METHOD:
        handler.handle_restart_service(source_service, parse_runtime_manager_service_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_START_SERVICE_METHOD:
        handler.handle_start_service(source_service, parse_runtime_manager_service_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_STOP_SERVICE_METHOD:
        handler.handle_stop_service(source_service, parse_runtime_manager_service_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_UPDATE_SERVICE_METHOD:
        handler.handle_update_service(source_service, parse_runtime_manager_update_service_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == RUNTIME_MANAGER_UPSERT_SERVICE_METHOD:
        handler.handle_upsert_service(source_service, parse_runtime_manager_upsert_service_request(payload))
        return True
    return False

class RuntimeManagerClient:
    def __init__(self, bridge: ServiceRequestBridge, target_service: str = "") -> None:
        self._bridge = bridge
        self._target_service = target_service.strip() or RUNTIME_MANAGER_SERVICE

    def get_status(self, request: RuntimeManagerConfigListRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeStatusPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_GET_STATUS_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_STATUS_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_status_payload(response['payload'])

    def get_config(self, request: RuntimeManagerConfigRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeConfigPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_GET_CONFIG_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_CONFIG_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_config_payload(response['payload'])

    def list_configs(self, request: RuntimeManagerConfigListRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeConfigListPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_LIST_CONFIGS_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_CONFIG_LIST_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_config_list_payload(response['payload'])

    def get_service_definition(self, request: RuntimeManagerServiceRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeDefinitionPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_GET_SERVICE_DEFINITION_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_SERVICE_DEFINITION_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_definition_payload(response['payload'])

    def get_service_log(self, request: RuntimeManagerLogRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeLogPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_GET_SERVICE_LOG_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_LOG_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_log_payload(response['payload'])

    def put_config(self, request: RuntimeManagerPutConfigRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeConfigPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_PUT_CONFIG_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_CONFIG_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_config_payload(response['payload'])

    def put_runtime_file(self, request: RuntimeManagerPutRuntimeFileRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeFilePayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_PUT_RUNTIME_FILE_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_FILE_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_file_payload(response['payload'])

    def remove_service(self, request: RuntimeManagerRemoveServiceRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeActionPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_REMOVE_SERVICE_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_action_payload(response['payload'])

    def restart_service(self, request: RuntimeManagerServiceRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeActionPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_RESTART_SERVICE_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_action_payload(response['payload'])

    def start_service(self, request: RuntimeManagerServiceRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeActionPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_START_SERVICE_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_action_payload(response['payload'])

    def stop_service(self, request: RuntimeManagerServiceRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeActionPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_STOP_SERVICE_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_action_payload(response['payload'])

    def update_service(self, request: RuntimeManagerUpdateServiceRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeActionPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_UPDATE_SERVICE_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_UPDATE_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_action_payload(response['payload'])

    def upsert_service(self, request: RuntimeManagerUpsertServiceRequest, timeout_sec: float = 5.0) -> RuntimeManagerRuntimeActionPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=RUNTIME_MANAGER_UPSERT_SERVICE_METHOD,
            payload=to_wire_value(request),
            expected_types={RUNTIME_MANAGER_SERVICE_ACTION_MESSAGE, RUNTIME_MANAGER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == RUNTIME_MANAGER_ERROR_MESSAGE:
            error_payload = parse_runtime_manager_runtime_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_runtime_manager_runtime_action_payload(response['payload'])
