# Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Protocol

from trakrai_service_runtime import ServiceRequestBridge

from ._runtime import convert_value, to_wire_value

VIDEO_RECORDER_SERVICE = "video-recorder"
VIDEO_RECORDER_CAPTURE_PHOTO_METHOD = "capture-photo"
VIDEO_RECORDER_CAPTURE_PHOTO_SUBTOPIC = "command"
VIDEO_RECORDER_RECORD_CLIP_METHOD = "record-clip"
VIDEO_RECORDER_RECORD_CLIP_SUBTOPIC = "command"
VIDEO_RECORDER_GET_JOB_METHOD = "get-job"
VIDEO_RECORDER_GET_JOB_SUBTOPIC = "command"
VIDEO_RECORDER_LIST_JOBS_METHOD = "list-jobs"
VIDEO_RECORDER_LIST_JOBS_SUBTOPIC = "command"
VIDEO_RECORDER_GET_STATUS_METHOD = "get-status"
VIDEO_RECORDER_GET_STATUS_SUBTOPIC = "command"
VIDEO_RECORDER_JOB_MESSAGE = "video-recorder-job"
VIDEO_RECORDER_PHOTO_MESSAGE = "video-recorder-photo"
VIDEO_RECORDER_LIST_MESSAGE = "video-recorder-list"
VIDEO_RECORDER_STATUS_MESSAGE = "video-recorder-status"
VIDEO_RECORDER_ERROR_MESSAGE = "video-recorder-error"


@dataclass(frozen=True)
class VideoRecorderRequestEnvelope:
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class VideoRecorderRecorderStats:
    completed_jobs: int = field(metadata={"wire_name": "completedJobs"})
    failed_jobs: int = field(metadata={"wire_name": "failedJobs"})
    pending_jobs: int = field(metadata={"wire_name": "pendingJobs"})
    running_jobs: int = field(metadata={"wire_name": "runningJobs"})
    total_jobs: int = field(metadata={"wire_name": "totalJobs"})

@dataclass(frozen=True)
class VideoRecorderCameraBufferStatus:
    bytes: int = field(metadata={"wire_name": "bytes"})
    camera_id: str = field(metadata={"wire_name": "cameraId"})
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    frames: int = field(metadata={"wire_name": "frames"})
    latest_at: str = field(metadata={"wire_name": "latestAt"})
    latest_image_id: str = field(metadata={"wire_name": "latestImageId"})
    oldest_at: str = field(metadata={"wire_name": "oldestAt"})

@dataclass(frozen=True)
class VideoRecorderPhotoCapture:
    bytes: int = field(metadata={"wire_name": "bytes"})
    camera_id: str = field(metadata={"wire_name": "cameraId"})
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    captured_at: str = field(metadata={"wire_name": "capturedAt"})
    image_id: str = field(metadata={"wire_name": "imageId"})
    local_path: str = field(metadata={"wire_name": "localPath"})

@dataclass(frozen=True)
class VideoRecorderRecordingJob:
    camera_id: str = field(metadata={"wire_name": "cameraId"})
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    created_at: str = field(metadata={"wire_name": "createdAt"})
    event_at: str = field(metadata={"wire_name": "eventAt"})
    frame_count: int = field(metadata={"wire_name": "frameCount"})
    frame_rate: int = field(metadata={"wire_name": "frameRate"})
    id: str = field(metadata={"wire_name": "id"})
    image_id: str = field(metadata={"wire_name": "imageId"})
    local_path: str = field(metadata={"wire_name": "localPath"})
    post_seconds: float = field(metadata={"wire_name": "postSeconds"})
    pre_seconds: float = field(metadata={"wire_name": "preSeconds"})
    remote_path: str = field(metadata={"wire_name": "remotePath"})
    state: str = field(metadata={"wire_name": "state"})
    updated_at: str = field(metadata={"wire_name": "updatedAt"})
    completed_at: Optional[str] = field(default=None, metadata={"wire_name": "completedAt"})
    codec: Optional[str] = field(default=None, metadata={"wire_name": "codec"})
    content_type: Optional[str] = field(default=None, metadata={"wire_name": "contentType"})
    error: Optional[str] = field(default=None, metadata={"wire_name": "error"})
    metadata: Optional[Dict[str, str]] = field(default=None, metadata={"wire_name": "metadata"})
    scope: Optional[str] = field(default=None, metadata={"wire_name": "scope"})
    started_at: Optional[str] = field(default=None, metadata={"wire_name": "startedAt"})
    timeout: Optional[str] = field(default=None, metadata={"wire_name": "timeout"})
    transfer_id: Optional[str] = field(default=None, metadata={"wire_name": "transferId"})

VideoRecorderRecordingJobMetadata = Dict[str, str]

@dataclass(frozen=True)
class VideoRecorderCapturePhotoRequest:
    local_path: str = field(metadata={"wire_name": "localPath"})
    camera_id: Optional[str] = field(default=None, metadata={"wire_name": "cameraId"})
    camera_name: Optional[str] = field(default=None, metadata={"wire_name": "cameraName"})
    image_id: Optional[str] = field(default=None, metadata={"wire_name": "imageId"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class VideoRecorderRecordClipRequest:
    local_path: str = field(metadata={"wire_name": "localPath"})
    remote_path: str = field(metadata={"wire_name": "remotePath"})
    camera_id: Optional[str] = field(default=None, metadata={"wire_name": "cameraId"})
    camera_name: Optional[str] = field(default=None, metadata={"wire_name": "cameraName"})
    codec: Optional[str] = field(default=None, metadata={"wire_name": "codec"})
    content_type: Optional[str] = field(default=None, metadata={"wire_name": "contentType"})
    frame_rate: Optional[int] = field(default=None, metadata={"wire_name": "frameRate"})
    image_id: Optional[str] = field(default=None, metadata={"wire_name": "imageId"})
    metadata: Optional[Dict[str, str]] = field(default=None, metadata={"wire_name": "metadata"})
    post_seconds: Optional[float] = field(default=None, metadata={"wire_name": "postSeconds"})
    pre_seconds: Optional[float] = field(default=None, metadata={"wire_name": "preSeconds"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    scope: Optional[str] = field(default=None, metadata={"wire_name": "scope"})
    timeout: Optional[str] = field(default=None, metadata={"wire_name": "timeout"})

VideoRecorderRecordClipRequestMetadata = Dict[str, str]

@dataclass(frozen=True)
class VideoRecorderGetJobRequest:
    job_id: str = field(metadata={"wire_name": "jobId"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class VideoRecorderListJobsRequest:
    limit: Optional[int] = field(default=None, metadata={"wire_name": "limit"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class VideoRecorderRecorderJobPayload:
    job: VideoRecorderRecordingJob = field(metadata={"wire_name": "job"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class VideoRecorderRecorderPhotoPayload:
    photo: VideoRecorderPhotoCapture = field(metadata={"wire_name": "photo"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class VideoRecorderRecorderListPayload:
    items: List[VideoRecorderRecordingJob] = field(metadata={"wire_name": "items"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class VideoRecorderRecorderStatusPayload:
    buffers: List[VideoRecorderCameraBufferStatus] = field(metadata={"wire_name": "buffers"})
    device_id: str = field(metadata={"wire_name": "deviceId"})
    gstreamer: str = field(metadata={"wire_name": "gstreamer"})
    shared_dir: str = field(metadata={"wire_name": "sharedDir"})
    stats: VideoRecorderRecorderStats = field(metadata={"wire_name": "stats"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

@dataclass(frozen=True)
class VideoRecorderRecorderErrorPayload:
    error: str = field(metadata={"wire_name": "error"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    request_type: Optional[str] = field(default=None, metadata={"wire_name": "requestType"})

def parse_video_recorder_request_envelope(payload: Optional[Mapping[str, Any]]) -> VideoRecorderRequestEnvelope:
    return convert_value(dict(payload or {}), VideoRecorderRequestEnvelope)

def parse_video_recorder_recorder_stats(payload: Optional[Mapping[str, Any]]) -> VideoRecorderRecorderStats:
    return convert_value(dict(payload or {}), VideoRecorderRecorderStats)

def parse_video_recorder_camera_buffer_status(payload: Optional[Mapping[str, Any]]) -> VideoRecorderCameraBufferStatus:
    return convert_value(dict(payload or {}), VideoRecorderCameraBufferStatus)

def parse_video_recorder_photo_capture(payload: Optional[Mapping[str, Any]]) -> VideoRecorderPhotoCapture:
    return convert_value(dict(payload or {}), VideoRecorderPhotoCapture)

def parse_video_recorder_recording_job(payload: Optional[Mapping[str, Any]]) -> VideoRecorderRecordingJob:
    return convert_value(dict(payload or {}), VideoRecorderRecordingJob)

def parse_video_recorder_capture_photo_request(payload: Optional[Mapping[str, Any]]) -> VideoRecorderCapturePhotoRequest:
    return convert_value(dict(payload or {}), VideoRecorderCapturePhotoRequest)

def parse_video_recorder_record_clip_request(payload: Optional[Mapping[str, Any]]) -> VideoRecorderRecordClipRequest:
    return convert_value(dict(payload or {}), VideoRecorderRecordClipRequest)

def parse_video_recorder_get_job_request(payload: Optional[Mapping[str, Any]]) -> VideoRecorderGetJobRequest:
    return convert_value(dict(payload or {}), VideoRecorderGetJobRequest)

def parse_video_recorder_list_jobs_request(payload: Optional[Mapping[str, Any]]) -> VideoRecorderListJobsRequest:
    return convert_value(dict(payload or {}), VideoRecorderListJobsRequest)

def parse_video_recorder_recorder_job_payload(payload: Optional[Mapping[str, Any]]) -> VideoRecorderRecorderJobPayload:
    return convert_value(dict(payload or {}), VideoRecorderRecorderJobPayload)

def parse_video_recorder_recorder_photo_payload(payload: Optional[Mapping[str, Any]]) -> VideoRecorderRecorderPhotoPayload:
    return convert_value(dict(payload or {}), VideoRecorderRecorderPhotoPayload)

def parse_video_recorder_recorder_list_payload(payload: Optional[Mapping[str, Any]]) -> VideoRecorderRecorderListPayload:
    return convert_value(dict(payload or {}), VideoRecorderRecorderListPayload)

def parse_video_recorder_recorder_status_payload(payload: Optional[Mapping[str, Any]]) -> VideoRecorderRecorderStatusPayload:
    return convert_value(dict(payload or {}), VideoRecorderRecorderStatusPayload)

def parse_video_recorder_recorder_error_payload(payload: Optional[Mapping[str, Any]]) -> VideoRecorderRecorderErrorPayload:
    return convert_value(dict(payload or {}), VideoRecorderRecorderErrorPayload)

class VideoRecorderHandler(Protocol):
    def handle_capture_photo(self, source_service: str, request: VideoRecorderCapturePhotoRequest) -> None: ...
    def handle_record_clip(self, source_service: str, request: VideoRecorderRecordClipRequest) -> None: ...
    def handle_get_job(self, source_service: str, request: VideoRecorderGetJobRequest) -> None: ...
    def handle_list_jobs(self, source_service: str, request: VideoRecorderListJobsRequest) -> None: ...
    def handle_get_status(self, source_service: str, request: VideoRecorderRequestEnvelope) -> None: ...

def dispatch_video_recorder(source_service: str, subtopic: str, envelope: Mapping[str, Any], handler: VideoRecorderHandler) -> bool:
    normalized_subtopic = str(subtopic or "").strip().strip("/")
    message_type = str(envelope.get("type", "")).strip()
    payload = envelope.get("payload", {})
    if not isinstance(payload, Mapping):
        payload = {}
    if normalized_subtopic == "command" and message_type == VIDEO_RECORDER_CAPTURE_PHOTO_METHOD:
        handler.handle_capture_photo(source_service, parse_video_recorder_capture_photo_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == VIDEO_RECORDER_RECORD_CLIP_METHOD:
        handler.handle_record_clip(source_service, parse_video_recorder_record_clip_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == VIDEO_RECORDER_GET_JOB_METHOD:
        handler.handle_get_job(source_service, parse_video_recorder_get_job_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == VIDEO_RECORDER_LIST_JOBS_METHOD:
        handler.handle_list_jobs(source_service, parse_video_recorder_list_jobs_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == VIDEO_RECORDER_GET_STATUS_METHOD:
        handler.handle_get_status(source_service, parse_video_recorder_request_envelope(payload))
        return True
    return False

class VideoRecorderClient:
    def __init__(self, bridge: ServiceRequestBridge, target_service: str = "") -> None:
        self._bridge = bridge
        self._target_service = target_service.strip() or VIDEO_RECORDER_SERVICE

    def capture_photo(self, request: VideoRecorderCapturePhotoRequest, timeout_sec: float = 5.0) -> VideoRecorderRecorderPhotoPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=VIDEO_RECORDER_CAPTURE_PHOTO_METHOD,
            payload=to_wire_value(request),
            expected_types={VIDEO_RECORDER_PHOTO_MESSAGE, VIDEO_RECORDER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == VIDEO_RECORDER_ERROR_MESSAGE:
            error_payload = parse_video_recorder_recorder_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_video_recorder_recorder_photo_payload(response['payload'])

    def record_clip(self, request: VideoRecorderRecordClipRequest, timeout_sec: float = 5.0) -> VideoRecorderRecorderJobPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=VIDEO_RECORDER_RECORD_CLIP_METHOD,
            payload=to_wire_value(request),
            expected_types={VIDEO_RECORDER_JOB_MESSAGE, VIDEO_RECORDER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == VIDEO_RECORDER_ERROR_MESSAGE:
            error_payload = parse_video_recorder_recorder_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_video_recorder_recorder_job_payload(response['payload'])

    def get_job(self, request: VideoRecorderGetJobRequest, timeout_sec: float = 5.0) -> VideoRecorderRecorderJobPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=VIDEO_RECORDER_GET_JOB_METHOD,
            payload=to_wire_value(request),
            expected_types={VIDEO_RECORDER_JOB_MESSAGE, VIDEO_RECORDER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == VIDEO_RECORDER_ERROR_MESSAGE:
            error_payload = parse_video_recorder_recorder_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_video_recorder_recorder_job_payload(response['payload'])

    def list_jobs(self, request: VideoRecorderListJobsRequest, timeout_sec: float = 5.0) -> VideoRecorderRecorderListPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=VIDEO_RECORDER_LIST_JOBS_METHOD,
            payload=to_wire_value(request),
            expected_types={VIDEO_RECORDER_LIST_MESSAGE, VIDEO_RECORDER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == VIDEO_RECORDER_ERROR_MESSAGE:
            error_payload = parse_video_recorder_recorder_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_video_recorder_recorder_list_payload(response['payload'])

    def get_status(self, request: VideoRecorderRequestEnvelope, timeout_sec: float = 5.0) -> VideoRecorderRecorderStatusPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=VIDEO_RECORDER_GET_STATUS_METHOD,
            payload=to_wire_value(request),
            expected_types={VIDEO_RECORDER_STATUS_MESSAGE, VIDEO_RECORDER_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == VIDEO_RECORDER_ERROR_MESSAGE:
            error_payload = parse_video_recorder_recorder_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_video_recorder_recorder_status_payload(response['payload'])
