# Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Protocol

from trakrai_service_runtime import ServiceRequestBridge

from ._runtime import convert_value, to_wire_value

WORKFLOW_ENGINE_SERVICE = "workflow-engine"
WORKFLOW_ENGINE_ENQUEUE_DETECTION_METHOD = "enqueue-detection"
WORKFLOW_ENGINE_ENQUEUE_DETECTION_SUBTOPIC = "command"
WORKFLOW_ENGINE_GET_STATUS_METHOD = "get-status"
WORKFLOW_ENGINE_GET_STATUS_SUBTOPIC = "command"
WORKFLOW_ENGINE_RESULT_MESSAGE = "workflow-engine-result"
WORKFLOW_ENGINE_STATUS_MESSAGE = "workflow-engine-status"
WORKFLOW_ENGINE_ERROR_MESSAGE = "workflow-engine-error"


@dataclass(frozen=True)
class WorkflowEngineDetection:
    bbox: Optional[List[float]] = field(default=None, metadata={"wire_name": "bbox"})
    class_name: Optional[str] = field(default=None, metadata={"wire_name": "class_name"})
    conf: Optional[float] = field(default=None, metadata={"wire_name": "conf"})
    confidence: Optional[float] = field(default=None, metadata={"wire_name": "confidence"})
    detections: Optional[List[WorkflowEngineDetection]] = field(default=None, metadata={"wire_name": "detections"})
    label: Optional[str] = field(default=None, metadata={"wire_name": "label"})
    raw_bboxes: Optional[List[float]] = field(default=None, metadata={"wire_name": "raw_bboxes"})
    x1: Optional[float] = field(default=None, metadata={"wire_name": "x1"})
    x2: Optional[float] = field(default=None, metadata={"wire_name": "x2"})
    xyxy: Optional[List[float]] = field(default=None, metadata={"wire_name": "xyxy"})
    y1: Optional[float] = field(default=None, metadata={"wire_name": "y1"})
    y2: Optional[float] = field(default=None, metadata={"wire_name": "y2"})

@dataclass(frozen=True)
class WorkflowEngineWorkflowPayload:
    detection_per_class: Optional[Dict[str, int]] = field(default=None, metadata={"wire_name": "DetectionPerClass"})
    bbox: Optional[List[WorkflowEngineDetection]] = field(default=None, metadata={"wire_name": "bbox"})
    cam_id: Optional[str] = field(default=None, metadata={"wire_name": "cam_id"})
    cam_name: Optional[str] = field(default=None, metadata={"wire_name": "cam_name"})
    camera_id: Optional[str] = field(default=None, metadata={"wire_name": "cameraId"})
    camera_name: Optional[str] = field(default=None, metadata={"wire_name": "cameraName"})
    frame_id: Optional[str] = field(default=None, metadata={"wire_name": "frame_id"})
    image_id: Optional[str] = field(default=None, metadata={"wire_name": "imageId"})
    img_id: Optional[str] = field(default=None, metadata={"wire_name": "imgID"})

WorkflowEngineWorkflowPayloadDetectionPerClass = Dict[str, int]

@dataclass(frozen=True)
class WorkflowEngineEnqueueDetectionRequest:
    detection_per_class: Optional[Dict[str, int]] = field(default=None, metadata={"wire_name": "DetectionPerClass"})
    bbox: Optional[List[WorkflowEngineDetection]] = field(default=None, metadata={"wire_name": "bbox"})
    camera_id: Optional[str] = field(default=None, metadata={"wire_name": "cameraId"})
    camera_name: Optional[str] = field(default=None, metadata={"wire_name": "cameraName"})
    detection_data: Optional[WorkflowEngineWorkflowPayload] = field(default=None, metadata={"wire_name": "detectionData"})
    detections: Optional[List[WorkflowEngineDetection]] = field(default=None, metadata={"wire_name": "detections"})
    frame_id: Optional[str] = field(default=None, metadata={"wire_name": "frameId"})
    image_id: Optional[str] = field(default=None, metadata={"wire_name": "imageId"})
    img_id: Optional[str] = field(default=None, metadata={"wire_name": "imgID"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

WorkflowEngineEnqueueDetectionRequestDetectionPerClass = Dict[str, int]

@dataclass(frozen=True)
class WorkflowEngineNodeResult:
    duration_ms: float = field(metadata={"wire_name": "durationMs"})
    error: str = field(metadata={"wire_name": "error"})
    outputs: Dict[str, Any] = field(metadata={"wire_name": "outputs"})
    status: str = field(metadata={"wire_name": "status"})

WorkflowEngineNodeResultOutputs = Dict[str, Any]

@dataclass(frozen=True)
class WorkflowEngineWorkflowRun:
    camera_id: str = field(metadata={"wire_name": "cameraId"})
    camera_name: str = field(metadata={"wire_name": "cameraName"})
    duration_ms: float = field(metadata={"wire_name": "durationMs"})
    errors: List[str] = field(metadata={"wire_name": "errors"})
    execution_id: str = field(metadata={"wire_name": "executionId"})
    frame_id: str = field(metadata={"wire_name": "frameId"})
    node_results: Dict[str, WorkflowEngineNodeResult] = field(metadata={"wire_name": "nodeResults"})
    outputs: Dict[str, Any] = field(metadata={"wire_name": "outputs"})
    success: bool = field(metadata={"wire_name": "success"})
    workflow_generation: int = field(metadata={"wire_name": "workflowGeneration"})
    workflow_hash: str = field(metadata={"wire_name": "workflowHash"})

WorkflowEngineWorkflowRunNodeResults = Dict[str, WorkflowEngineNodeResult]

WorkflowEngineWorkflowRunOutputs = Dict[str, Any]

@dataclass(frozen=True)
class WorkflowEngineWorkflowResultPayload:
    request_id: str = field(metadata={"wire_name": "requestId"})
    run: WorkflowEngineWorkflowRun = field(metadata={"wire_name": "run"})

@dataclass(frozen=True)
class WorkflowEngineWorkflowStatusState:
    error: str = field(metadata={"wire_name": "error"})
    file_path: str = field(metadata={"wire_name": "filePath"})
    generation: int = field(metadata={"wire_name": "generation"})
    hash: str = field(metadata={"wire_name": "hash"})
    loaded: bool = field(metadata={"wire_name": "loaded"})
    loaded_at: str = field(metadata={"wire_name": "loadedAt"})
    name: str = field(metadata={"wire_name": "name"})

@dataclass(frozen=True)
class WorkflowEngineWorkflowQueueState:
    active_request_id: str = field(metadata={"wire_name": "activeRequestId"})
    max_pending: int = field(metadata={"wire_name": "maxPending"})
    pending: int = field(metadata={"wire_name": "pending"})

@dataclass(frozen=True)
class WorkflowEngineWorkflowStats:
    dropped_runs: int = field(metadata={"wire_name": "droppedRuns"})
    failed_runs: int = field(metadata={"wire_name": "failedRuns"})
    processed_runs: int = field(metadata={"wire_name": "processedRuns"})
    reload_count: int = field(metadata={"wire_name": "reloadCount"})

@dataclass(frozen=True)
class WorkflowEngineWorkflowStatusPayload:
    device_id: str = field(metadata={"wire_name": "deviceId"})
    queue: WorkflowEngineWorkflowQueueState = field(metadata={"wire_name": "queue"})
    recent_runs: List[WorkflowEngineWorkflowRun] = field(metadata={"wire_name": "recentRuns"})
    request_id: str = field(metadata={"wire_name": "requestId"})
    service: str = field(metadata={"wire_name": "service"})
    stats: WorkflowEngineWorkflowStats = field(metadata={"wire_name": "stats"})
    workflow: WorkflowEngineWorkflowStatusState = field(metadata={"wire_name": "workflow"})

@dataclass(frozen=True)
class WorkflowEngineWorkflowErrorPayload:
    error: str = field(metadata={"wire_name": "error"})
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})
    request_type: Optional[str] = field(default=None, metadata={"wire_name": "requestType"})

@dataclass(frozen=True)
class WorkflowEngineStatusRequest:
    request_id: Optional[str] = field(default=None, metadata={"wire_name": "requestId"})

def parse_workflow_engine_detection(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineDetection:
    return convert_value(dict(payload or {}), WorkflowEngineDetection)

def parse_workflow_engine_workflow_payload(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineWorkflowPayload:
    return convert_value(dict(payload or {}), WorkflowEngineWorkflowPayload)

def parse_workflow_engine_enqueue_detection_request(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineEnqueueDetectionRequest:
    return convert_value(dict(payload or {}), WorkflowEngineEnqueueDetectionRequest)

def parse_workflow_engine_node_result(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineNodeResult:
    return convert_value(dict(payload or {}), WorkflowEngineNodeResult)

def parse_workflow_engine_workflow_run(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineWorkflowRun:
    return convert_value(dict(payload or {}), WorkflowEngineWorkflowRun)

def parse_workflow_engine_workflow_result_payload(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineWorkflowResultPayload:
    return convert_value(dict(payload or {}), WorkflowEngineWorkflowResultPayload)

def parse_workflow_engine_workflow_status_state(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineWorkflowStatusState:
    return convert_value(dict(payload or {}), WorkflowEngineWorkflowStatusState)

def parse_workflow_engine_workflow_queue_state(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineWorkflowQueueState:
    return convert_value(dict(payload or {}), WorkflowEngineWorkflowQueueState)

def parse_workflow_engine_workflow_stats(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineWorkflowStats:
    return convert_value(dict(payload or {}), WorkflowEngineWorkflowStats)

def parse_workflow_engine_workflow_status_payload(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineWorkflowStatusPayload:
    return convert_value(dict(payload or {}), WorkflowEngineWorkflowStatusPayload)

def parse_workflow_engine_workflow_error_payload(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineWorkflowErrorPayload:
    return convert_value(dict(payload or {}), WorkflowEngineWorkflowErrorPayload)

def parse_workflow_engine_status_request(payload: Optional[Mapping[str, Any]]) -> WorkflowEngineStatusRequest:
    return convert_value(dict(payload or {}), WorkflowEngineStatusRequest)

class WorkflowEngineHandler(Protocol):
    def handle_enqueue_detection(self, source_service: str, request: WorkflowEngineEnqueueDetectionRequest) -> None: ...
    def handle_get_status(self, source_service: str, request: WorkflowEngineStatusRequest) -> None: ...

def dispatch_workflow_engine(source_service: str, subtopic: str, envelope: Mapping[str, Any], handler: WorkflowEngineHandler) -> bool:
    normalized_subtopic = str(subtopic or "").strip().strip("/")
    message_type = str(envelope.get("type", "")).strip()
    payload = envelope.get("payload", {})
    if not isinstance(payload, Mapping):
        payload = {}
    if normalized_subtopic == "command" and message_type == WORKFLOW_ENGINE_ENQUEUE_DETECTION_METHOD:
        handler.handle_enqueue_detection(source_service, parse_workflow_engine_enqueue_detection_request(payload))
        return True
    elif normalized_subtopic == "command" and message_type == WORKFLOW_ENGINE_GET_STATUS_METHOD:
        handler.handle_get_status(source_service, parse_workflow_engine_status_request(payload))
        return True
    return False

class WorkflowEngineClient:
    def __init__(self, bridge: ServiceRequestBridge, target_service: str = "") -> None:
        self._bridge = bridge
        self._target_service = target_service.strip() or WORKFLOW_ENGINE_SERVICE

    def enqueue_detection(self, request: WorkflowEngineEnqueueDetectionRequest, timeout_sec: float = 5.0) -> WorkflowEngineWorkflowResultPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=WORKFLOW_ENGINE_ENQUEUE_DETECTION_METHOD,
            payload=to_wire_value(request),
            expected_types={WORKFLOW_ENGINE_RESULT_MESSAGE, WORKFLOW_ENGINE_ERROR_MESSAGE},
            timeout_sec=timeout_sec,
        )
        if response['type'] == WORKFLOW_ENGINE_ERROR_MESSAGE:
            error_payload = parse_workflow_engine_workflow_error_payload(response['payload'])
            raise RuntimeError(str(error_payload.error).strip())
        return parse_workflow_engine_workflow_result_payload(response['payload'])

    def get_status(self, request: WorkflowEngineStatusRequest, timeout_sec: float = 5.0) -> WorkflowEngineWorkflowStatusPayload:
        response = self._bridge.request(
            target_service=self._target_service,
            message_type=WORKFLOW_ENGINE_GET_STATUS_METHOD,
            payload=to_wire_value(request),
            expected_types={WORKFLOW_ENGINE_STATUS_MESSAGE},
            timeout_sec=timeout_sec,
        )
        return parse_workflow_engine_workflow_status_payload(response['payload'])
