// Code generated by `python -m device.devtool config codegen`. DO NOT EDIT.

package generatedconfig

import (
	"encoding/json"
	"os"
)

type CloudTransferConfig struct {
	CloudApi CloudTransferConfigCloudApi `json:"cloud_api"`
	DeviceId string `json:"device_id"`
	Ipc CloudTransferConfigIpc `json:"ipc"`
	LogLevel string `json:"log_level"`
	Queue CloudTransferConfigQueue `json:"queue"`
	Storage CloudTransferConfigStorage `json:"storage"`
}

type CloudTransferConfigCloudApi struct {
	AccessToken string `json:"access_token"`
	BaseUrl string `json:"base_url"`
	DownloadPresignPath string `json:"download_presign_path"`
	PackageDownloadPresignPath string `json:"package_download_presign_path"`
	RequestTimeoutSec int `json:"request_timeout_sec"`
	UploadPresignPath string `json:"upload_presign_path"`
}

type CloudTransferConfigIpc struct {
	SocketPath string `json:"socket_path"`
}

type CloudTransferConfigQueue struct {
	InitialBackoffSec int `json:"initial_backoff_sec"`
	MaxBackoffSec int `json:"max_backoff_sec"`
	PollIntervalMs int `json:"poll_interval_ms"`
	StatusReportIntervalSec int `json:"status_report_interval_sec"`
	WorkerCount int `json:"worker_count"`
}

type CloudTransferConfigStorage struct {
	DatabasePath string `json:"database_path"`
	SharedDir string `json:"shared_dir"`
}

func DefaultCloudTransferConfig() CloudTransferConfig {
	return CloudTransferConfig{CloudApi: CloudTransferConfigCloudApi{AccessToken: "", BaseUrl: "https://api.trakrai.example", DownloadPresignPath: "/api/external/storage/devices/download-session", PackageDownloadPresignPath: "/api/external/storage/packages/download-session", RequestTimeoutSec: 30, UploadPresignPath: "/api/external/storage/devices/upload-session"}, DeviceId: "default", Ipc: CloudTransferConfigIpc{SocketPath: "/tmp/trakrai-cloud-comm.sock"}, LogLevel: "info", Queue: CloudTransferConfigQueue{InitialBackoffSec: 5, MaxBackoffSec: 300, PollIntervalMs: 1000, StatusReportIntervalSec: 15, WorkerCount: 1}, Storage: CloudTransferConfigStorage{DatabasePath: "/home/hacklab/trakrai-device-runtime/state/cloud-transfer/transfers.sqlite", SharedDir: "/home/hacklab/trakrai-device-runtime/shared"}}
}

func LoadCloudTransferConfig(path string) (CloudTransferConfig, error) {
	cfg := DefaultCloudTransferConfig()
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg, err
	}
	if err := json.Unmarshal(data, &cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}
