// Code generated by `python -m device.devtool config codegen`. DO NOT EDIT.

package generatedconfig

import (
	"encoding/json"
	"os"
)

type LiveFeedConfig struct {
	Composite LiveFeedConfigComposite `json:"composite"`
	Ipc LiveFeedConfigIpc `json:"ipc"`
	LogLevel string `json:"log_level"`
	Redis LiveFeedConfigRedis `json:"redis"`
	Webrtc LiveFeedConfigWebrtc `json:"webrtc"`
}

type LiveFeedConfigComposite struct {
	Height int `json:"height"`
	TilePadding int `json:"tile_padding"`
	Width int `json:"width"`
}

type LiveFeedConfigIpc struct {
	SocketPath string `json:"socket_path"`
}

type LiveFeedConfigRedis struct {
	Db int `json:"db"`
	Host string `json:"host"`
	KeyPrefix string `json:"key_prefix"`
	Password string `json:"password"`
	Port int `json:"port"`
}

type LiveFeedConfigWebrtc struct {
	AdvertiseRelayCandidates bool `json:"advertise_relay_candidates"`
	ExcludedInterfacePrefixes []string `json:"excluded_interface_prefixes"`
	ForceIpv4Candidates bool `json:"force_ipv4_candidates"`
	FramerateFps int `json:"framerate_fps"`
	HostCandidateIps []string `json:"host_candidate_ips"`
	StunServers []string `json:"stun_servers"`
	TurnServers []LiveFeedConfigWebrtcTurnServersItem `json:"turn_servers"`
	UdpPortRange LiveFeedConfigWebrtcUdpPortRange `json:"udp_port_range"`
}

type LiveFeedConfigWebrtcTurnServersItem struct {
	Credential string `json:"credential"`
	Url string `json:"url"`
	Username string `json:"username"`
}

type LiveFeedConfigWebrtcUdpPortRange struct {
	Max int `json:"max"`
	Min int `json:"min"`
}

func DefaultLiveFeedConfig() LiveFeedConfig {
	return LiveFeedConfig{Composite: LiveFeedConfigComposite{Height: 540, TilePadding: 8, Width: 960}, Ipc: LiveFeedConfigIpc{SocketPath: "/tmp/trakrai-cloud-comm.sock"}, LogLevel: "info", Redis: LiveFeedConfigRedis{Db: 0, Host: "localhost", KeyPrefix: "camera", Password: "", Port: 6379}, Webrtc: LiveFeedConfigWebrtc{AdvertiseRelayCandidates: false, ExcludedInterfacePrefixes: []string{"lo", "docker", "br-", "veth", "virbr", "cni", "flannel"}, ForceIpv4Candidates: true, FramerateFps: 10, HostCandidateIps: []string{"127.0.0.1"}, StunServers: []string{"stun:stun.l.google.com:19302"}, TurnServers: []LiveFeedConfigWebrtcTurnServersItem{LiveFeedConfigWebrtcTurnServersItem{Credential: "trakrai-secret", Url: "turn:192.168.1.100:3478", Username: "trakrai"}}, UdpPortRange: LiveFeedConfigWebrtcUdpPortRange{Max: 40049, Min: 40000}}}
}

func LoadLiveFeedConfig(path string) (LiveFeedConfig, error) {
	cfg := DefaultLiveFeedConfig()
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg, err
	}
	if err := json.Unmarshal(data, &cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}
