// Code generated by `python -m device.devtool config codegen`. DO NOT EDIT.

package generatedconfig

import (
	"encoding/json"
	"os"
)

type PtzControlConfig struct {
	Cameras []PtzControlConfigCamerasItem `json:"cameras"`
	Defaults PtzControlConfigDefaults `json:"defaults"`
	Ipc PtzControlConfigIpc `json:"ipc"`
	LogLevel string `json:"log_level"`
}

type PtzControlConfigCamerasItem struct {
	Address string `json:"address"`
	Driver string `json:"driver"`
	Enabled bool `json:"enabled"`
	Home PtzControlConfigCamerasItemHome `json:"home"`
	Name string `json:"name"`
	OnvifPort int `json:"onvif_port"`
	ProfileToken string `json:"profile_token"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type PtzControlConfigCamerasItemHome struct {
	Pan float64 `json:"pan"`
	Tilt float64 `json:"tilt"`
	Zoom float64 `json:"zoom"`
}

type PtzControlConfigDefaults struct {
	AbsoluteSpeed float64 `json:"absolute_speed"`
	PanTiltSpeed float64 `json:"pan_tilt_speed"`
	ZoomSpeed float64 `json:"zoom_speed"`
}

type PtzControlConfigIpc struct {
	SocketPath string `json:"socket_path"`
}

func DefaultPtzControlConfig() PtzControlConfig {
	return PtzControlConfig{Cameras: []PtzControlConfigCamerasItem{PtzControlConfigCamerasItem{Address: "192.168.1.20", Driver: "onvif", Enabled: true, Name: "LP1-Main", OnvifPort: 80, Password: "HACK_LAB", Username: "admin"}, PtzControlConfigCamerasItem{Address: "192.168.1.25", Driver: "onvif", Enabled: true, Name: "LP1-Sec", OnvifPort: 80, Password: "HACK_LAB", Username: "admin"}}, Defaults: PtzControlConfigDefaults{AbsoluteSpeed: 0.8, PanTiltSpeed: 0.55, ZoomSpeed: 0.45}, Ipc: PtzControlConfigIpc{SocketPath: "/tmp/trakrai-cloud-comm.sock"}, LogLevel: "info"}
}

func LoadPtzControlConfig(path string) (PtzControlConfig, error) {
	cfg := DefaultPtzControlConfig()
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg, err
	}
	if err := json.Unmarshal(data, &cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}
