// Code generated by `python -m device.devtool config codegen`. DO NOT EDIT.

package generatedconfig

import (
	"encoding/json"
	"os"
)

type RoiConfigConfig struct {
	Ipc RoiConfigConfigIpc `json:"ipc"`
	LogLevel string `json:"log_level"`
	Storage RoiConfigConfigStorage `json:"storage"`
}

type RoiConfigConfigIpc struct {
	SocketPath string `json:"socket_path"`
}

type RoiConfigConfigStorage struct {
	FilePath string `json:"file_path"`
}

func DefaultRoiConfigConfig() RoiConfigConfig {
	return RoiConfigConfig{Ipc: RoiConfigConfigIpc{SocketPath: "/tmp/trakrai-cloud-comm.sock"}, LogLevel: "info", Storage: RoiConfigConfigStorage{FilePath: "/home/hacklab/trakrai-device-runtime/shared/roi-config.json"}}
}

func LoadRoiConfigConfig(path string) (RoiConfigConfig, error) {
	cfg := DefaultRoiConfigConfig()
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg, err
	}
	if err := json.Unmarshal(data, &cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}
