// Code generated by `python -m device.devtool config codegen`. DO NOT EDIT.

package generatedconfig

import (
	"encoding/json"
	"os"
)

type RtspFeederConfig struct {
	Cameras []RtspFeederConfigCamerasItem `json:"cameras"`
	Defaults RtspFeederConfigDefaults `json:"defaults"`
	LogLevel string `json:"log_level"`
	Redis RtspFeederConfigRedis `json:"redis"`
}

type RtspFeederConfigCamerasItem struct {
	CaptureMethod string `json:"capture_method"`
	Enabled bool `json:"enabled"`
	Framerate float64 `json:"framerate"`
	Height int `json:"height"`
	Id int `json:"id"`
	JpegQuality int `json:"jpeg_quality"`
	LatencyMs int `json:"latency_ms"`
	Name string `json:"name"`
	PipelineTimeoutSec int `json:"pipeline_timeout_sec"`
	Protocols string `json:"protocols"`
	ReconnectDelaySec int `json:"reconnect_delay_sec"`
	Rotate180 bool `json:"rotate_180"`
	RtspUrl string `json:"rtsp_url"`
	SaveFrames bool `json:"save_frames"`
	SavePath string `json:"save_path"`
	Width int `json:"width"`
}

type RtspFeederConfigDefaults struct {
	CaptureMethod string `json:"capture_method"`
	Framerate float64 `json:"framerate"`
	Height int `json:"height"`
	JpegQuality int `json:"jpeg_quality"`
	LatencyMs int `json:"latency_ms"`
	PipelineTimeoutSec int `json:"pipeline_timeout_sec"`
	Protocols string `json:"protocols"`
	ReconnectDelaySec int `json:"reconnect_delay_sec"`
	Rotate180 bool `json:"rotate_180"`
	SaveFrames bool `json:"save_frames"`
	SavePath string `json:"save_path"`
	Width int `json:"width"`
}

type RtspFeederConfigRedis struct {
	Db int `json:"db"`
	Host string `json:"host"`
	KeyPrefix string `json:"key_prefix"`
	Password string `json:"password"`
	Port int `json:"port"`
}

func DefaultRtspFeederConfig() RtspFeederConfig {
	return RtspFeederConfig{Cameras: []RtspFeederConfigCamerasItem{RtspFeederConfigCamerasItem{Enabled: true, Id: 1, Name: "Camera-1", Rotate180: false, RtspUrl: "rtsp://user:password@192.168.1.10:554/stream"}, RtspFeederConfigCamerasItem{Enabled: true, Framerate: 5, Height: 720, Id: 2, Name: "Camera-2", Rotate180: true, RtspUrl: "rtsp://user:password@192.168.1.11:554/stream", Width: 1280}}, Defaults: RtspFeederConfigDefaults{CaptureMethod: "auto", Framerate: 10, Height: 480, JpegQuality: 85, LatencyMs: 200, PipelineTimeoutSec: 15, Protocols: "tcp", ReconnectDelaySec: 5, Rotate180: false, SaveFrames: false, SavePath: "/data/raw", Width: 640}, LogLevel: "info", Redis: RtspFeederConfigRedis{Db: 0, Host: "localhost", KeyPrefix: "camera", Password: "", Port: 6379}}
}

func LoadRtspFeederConfig(path string) (RtspFeederConfig, error) {
	cfg := DefaultRtspFeederConfig()
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg, err
	}
	if err := json.Unmarshal(data, &cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}
