// Code generated by `python -m device.devtool config codegen`. DO NOT EDIT.

package generatedconfig

import (
	"encoding/json"
	"os"
)

type VideoRecorderConfig struct {
	Buffer VideoRecorderConfigBuffer `json:"buffer"`
	Cameras []VideoRecorderConfigCamerasItem `json:"cameras"`
	DeviceId string `json:"device_id"`
	Ipc VideoRecorderConfigIpc `json:"ipc"`
	LogLevel string `json:"log_level"`
	Queue VideoRecorderConfigQueue `json:"queue"`
	Recording VideoRecorderConfigRecording `json:"recording"`
	Redis VideoRecorderConfigRedis `json:"redis"`
	Storage VideoRecorderConfigStorage `json:"storage"`
	Upload VideoRecorderConfigUpload `json:"upload"`
}

type VideoRecorderConfigBuffer struct {
	DurationSec int `json:"duration_sec"`
	MaxBytesPerCamera int `json:"max_bytes_per_camera"`
	MaxFramesPerCamera int `json:"max_frames_per_camera"`
	MaxSegmentBytes int `json:"max_segment_bytes"`
	PollIntervalMs int `json:"poll_interval_ms"`
	StatusReportIntervalSec int `json:"status_report_interval_sec"`
}

type VideoRecorderConfigCamerasItem struct {
	Enabled bool `json:"enabled"`
	Height int `json:"height"`
	Id int `json:"id"`
	Name string `json:"name"`
	Width int `json:"width"`
}

type VideoRecorderConfigIpc struct {
	SocketPath string `json:"socket_path"`
}

type VideoRecorderConfigQueue struct {
	MaxPending int `json:"max_pending"`
	WorkerCount int `json:"worker_count"`
}

type VideoRecorderConfigRecording struct {
	DefaultCodec string `json:"default_codec"`
	DefaultFrameRate int `json:"default_frame_rate"`
	DefaultPostSec int `json:"default_post_sec"`
	DefaultPreSec int `json:"default_pre_sec"`
	GstreamerBin string `json:"gstreamer_bin"`
	MaxFrameRate int `json:"max_frame_rate"`
	WriteTimeoutSec int `json:"write_timeout_sec"`
}

type VideoRecorderConfigRedis struct {
	Db int `json:"db"`
	Host string `json:"host"`
	KeyPrefix string `json:"key_prefix"`
	Password string `json:"password"`
	Port int `json:"port"`
}

type VideoRecorderConfigStorage struct {
	BufferDir string `json:"buffer_dir"`
	SharedDir string `json:"shared_dir"`
}

type VideoRecorderConfigUpload struct {
	ServiceName string `json:"service_name"`
}

func DefaultVideoRecorderConfig() VideoRecorderConfig {
	return VideoRecorderConfig{Buffer: VideoRecorderConfigBuffer{DurationSec: 600, MaxBytesPerCamera: 268435456, MaxFramesPerCamera: 6000, MaxSegmentBytes: 16777216, PollIntervalMs: 100, StatusReportIntervalSec: 5}, Cameras: []VideoRecorderConfigCamerasItem{VideoRecorderConfigCamerasItem{Enabled: true, Height: 480, Id: 1, Name: "Camera-1", Width: 640}}, DeviceId: "trakrai-device", Ipc: VideoRecorderConfigIpc{SocketPath: "/tmp/trakrai-cloud-comm.sock"}, LogLevel: "info", Queue: VideoRecorderConfigQueue{MaxPending: 64, WorkerCount: 1}, Recording: VideoRecorderConfigRecording{DefaultCodec: "h264", DefaultFrameRate: 10, DefaultPostSec: 5, DefaultPreSec: 5, GstreamerBin: "gst-launch-1.0", MaxFrameRate: 25, WriteTimeoutSec: 60}, Redis: VideoRecorderConfigRedis{Db: 0, Host: "localhost", KeyPrefix: "camera", Password: "", Port: 6379}, Storage: VideoRecorderConfigStorage{BufferDir: "/home/hacklab/trakrai-device-runtime/state/video-recorder", SharedDir: "/home/hacklab/trakrai-device-runtime/shared"}, Upload: VideoRecorderConfigUpload{ServiceName: "cloud-transfer"}}
}

func LoadVideoRecorderConfig(path string) (VideoRecorderConfig, error) {
	cfg := DefaultVideoRecorderConfig()
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg, err
	}
	if err := json.Unmarshal(data, &cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}
