# Code generated by `python -m device.devtool config codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from ._runtime import load_dataclass_from_json

@dataclass(frozen=True)
class AudioManagerConfig:
    device_id: str
    ipc: AudioManagerConfigIpc
    log_level: str
    playback: AudioManagerConfigPlayback
    queue: AudioManagerConfigQueue
    speaker: AudioManagerConfigSpeaker
    storage: AudioManagerConfigStorage
    tts: AudioManagerConfigTts

@dataclass(frozen=True)
class AudioManagerConfigIpc:
    socket_path: str

@dataclass(frozen=True)
class AudioManagerConfigPlayback:
    backend: str
    command_template: list[str]
    timeout_sec: int

@dataclass(frozen=True)
class AudioManagerConfigQueue:
    dedupe_window_sec: int
    max_pending: int
    status_report_interval_sec: int

@dataclass(frozen=True)
class AudioManagerConfigSpeaker:
    backoff_sec: float
    default_address: str
    enabled: bool
    mapping_file: str
    request_timeout_sec: int
    retry_count: int
    transport: str

@dataclass(frozen=True)
class AudioManagerConfigStorage:
    cache_dir: str
    event_log_path: str
    state_db_path: str

@dataclass(frozen=True)
class AudioManagerConfigTts:
    default_language: str
    timeout_sec: int
    voice_map: dict[str, str]

DEFAULT_AUDIO_MANAGER_JSON = "{\"log_level\": \"info\", \"device_id\": \"trakrai-device-001\", \"ipc\": {\"socket_path\": \"/tmp/trakrai-cloud-comm.sock\"}, \"queue\": {\"max_pending\": 128, \"status_report_interval_sec\": 15, \"dedupe_window_sec\": 60}, \"storage\": {\"state_db_path\": \"/home/hacklab/trakrai-device-runtime/state/audio-manager.sqlite3\", \"cache_dir\": \"/home/hacklab/trakrai-device-runtime/shared/audio/cache\", \"event_log_path\": \"/home/hacklab/trakrai-device-runtime/shared/audio/audio-events.jsonl\"}, \"tts\": {\"default_language\": \"en\", \"timeout_sec\": 30, \"voice_map\": {\"en\": \"en\", \"hi\": \"hi\"}}, \"playback\": {\"backend\": \"auto\", \"timeout_sec\": 60, \"command_template\": [\"curl\", \"--fail\", \"--silent\", \"--show-error\", \"-X\", \"POST\", \"--data-binary\", \"@{audio_path}\", \"-H\", \"Content-Type: {audio_content_type}\", \"http://host.docker.internal:18920/play\"]}, \"speaker\": {\"enabled\": true, \"transport\": \"short-code-http\", \"mapping_file\": \"/home/hacklab/trakrai-device-runtime/shared/audio/speaker-codes.csv\", \"default_address\": \"\", \"request_timeout_sec\": 2, \"retry_count\": 2, \"backoff_sec\": 1}}"

def load_audio_manager_config(path: str | Path) -> AudioManagerConfig:
    return load_dataclass_from_json(path, AudioManagerConfig, default_json=DEFAULT_AUDIO_MANAGER_JSON)
