# Code generated by `python -m device.devtool config codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from ._runtime import load_dataclass_from_json

@dataclass(frozen=True)
class TrakraiAiInferenceConfig:
    cameras: list[TrakraiAiInferenceConfigCamerasItem]
    inference: TrakraiAiInferenceConfigInference
    log_level: str
    redis: TrakraiAiInferenceConfigRedis

@dataclass(frozen=True)
class TrakraiAiInferenceConfigCamerasItem:
    enabled: bool
    id: int
    name: str

@dataclass(frozen=True)
class TrakraiAiInferenceConfigInference:
    confidence_threshold: float
    device: str
    fp16_inference: bool
    idle_sleep_ms: int
    inference_image_size: list[int]
    iou_threshold: float
    min_brightness: int
    models: list[TrakraiAiInferenceConfigInferenceModelsItem]
    poll_interval_ms: int
    processed_images_maxlen: int

@dataclass(frozen=True)
class TrakraiAiInferenceConfigInferenceModelsItem:
    allowed_detections: str
    weights_path: str

@dataclass(frozen=True)
class TrakraiAiInferenceConfigRedis:
    db: int
    host: str
    key_prefix: str
    password: str
    port: int

DEFAULT_TRAKRAI_AI_INFERENCE_JSON = "{\"log_level\": \"info\", \"redis\": {\"host\": \"localhost\", \"port\": 6379, \"password\": \"\", \"db\": 0, \"key_prefix\": \"camera\"}, \"inference\": {\"device\": \"0\", \"poll_interval_ms\": 5, \"idle_sleep_ms\": 40, \"min_brightness\": 25, \"processed_images_maxlen\": 10, \"inference_image_size\": [512, 512], \"confidence_threshold\": 0.5, \"iou_threshold\": 0.75, \"fp16_inference\": true, \"models\": [{\"weights_path\": \"/home/hacklab/trakrai-device-runtime/models/primary.engine\", \"allowed_detections\": \"*\"}]}, \"cameras\": [{\"id\": 1, \"name\": \"Camera-1\", \"enabled\": true}]}"

def load_trakrai_ai_inference_config(path: str | Path) -> TrakraiAiInferenceConfig:
    return load_dataclass_from_json(path, TrakraiAiInferenceConfig, default_json=DEFAULT_TRAKRAI_AI_INFERENCE_JSON)
