# Code generated by `python -m device.devtool config codegen`. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List

from ._runtime import load_dataclass_from_json

@dataclass(frozen=True)
class WorkflowEngineConfig:
    device_id: str
    ipc: WorkflowEngineConfigIpc
    log_level: str
    queue: WorkflowEngineConfigQueue
    workflow: WorkflowEngineConfigWorkflow

@dataclass(frozen=True)
class WorkflowEngineConfigIpc:
    socket_path: str

@dataclass(frozen=True)
class WorkflowEngineConfigQueue:
    max_pending: int
    status_report_interval_sec: int

@dataclass(frozen=True)
class WorkflowEngineConfigWorkflow:
    file_path: str
    max_workers: int
    reload_poll_interval_ms: int
    result_history_size: int

DEFAULT_WORKFLOW_ENGINE_JSON = "{\"log_level\": \"info\", \"device_id\": \"trakrai-device-001\", \"ipc\": {\"socket_path\": \"/tmp/trakrai-cloud-comm.sock\"}, \"queue\": {\"max_pending\": 256, \"status_report_interval_sec\": 15}, \"workflow\": {\"file_path\": \"/home/hacklab/trakrai-device-runtime/shared/workflow.json\", \"reload_poll_interval_ms\": 1000, \"max_workers\": 4, \"result_history_size\": 20}}"

def load_workflow_engine_config(path: str | Path) -> WorkflowEngineConfig:
    return load_dataclass_from_json(path, WorkflowEngineConfig, default_json=DEFAULT_WORKFLOW_ENGINE_JSON)
