// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
'use client';

import {
  defineServiceContract,
  defineServiceContractMethod,
  defineServiceContractOutput,
  type ServiceContractOutput,
} from '../lib/service-contract-runtime';

export const CLOUD_TRANSFER_SERVICE = 'cloud-transfer';
export const CLOUD_TRANSFER_ENQUEUE_UPLOAD_METHOD = 'enqueue-upload';
export const CLOUD_TRANSFER_ENQUEUE_UPLOAD_SUBTOPIC = 'command';
export const CLOUD_TRANSFER_ENQUEUE_DOWNLOAD_METHOD = 'enqueue-download';
export const CLOUD_TRANSFER_ENQUEUE_DOWNLOAD_SUBTOPIC = 'command';
export const CLOUD_TRANSFER_GET_TRANSFER_METHOD = 'get-transfer';
export const CLOUD_TRANSFER_GET_TRANSFER_SUBTOPIC = 'command';
export const CLOUD_TRANSFER_LIST_TRANSFERS_METHOD = 'list-transfers';
export const CLOUD_TRANSFER_LIST_TRANSFERS_SUBTOPIC = 'command';
export const CLOUD_TRANSFER_GET_STATS_METHOD = 'get-stats';
export const CLOUD_TRANSFER_GET_STATS_SUBTOPIC = 'command';
export const CLOUD_TRANSFER_GET_STATUS_METHOD = 'get-status';
export const CLOUD_TRANSFER_GET_STATUS_SUBTOPIC = 'command';
export const CLOUD_TRANSFER_TRANSFER_MESSAGE = 'cloud-transfer-transfer';
export const CLOUD_TRANSFER_LIST_MESSAGE = 'cloud-transfer-list';
export const CLOUD_TRANSFER_STATS_MESSAGE = 'cloud-transfer-stats';
export const CLOUD_TRANSFER_STATUS_MESSAGE = 'cloud-transfer-status';
export const CLOUD_TRANSFER_ERROR_MESSAGE = 'cloud-transfer-error';

export type CloudTransfer_QueueStats = Readonly<{
  completed: number;
  downloadQueued: number;
  downloadsCompleted: number;
  downloadsFailed: number;
  failed: number;
  nextAttemptAt?: string;
  pending: number;
  running: number;
  total: number;
  uploadQueued: number;
  uploadsCompleted: number;
  uploadsFailed: number;
}>;

export type CloudTransfer_Transfer = Readonly<{
  attempts: number;
  completedAt?: string;
  contentType?: string;
  createdAt: string;
  deadlineAt?: string;
  deviceId: string;
  direction: 'download' | 'upload';
  id: string;
  lastError?: string;
  localPath: string;
  metadata?: Record<string, string>;
  nextAttemptAt?: string;
  objectKey?: string;
  remotePath: string;
  scope?: 'device' | 'package';
  startedAt?: string;
  state: 'completed' | 'failed' | 'queued' | 'retry_wait' | 'running';
  updatedAt: string;
}>;

export type CloudTransfer_TransferMetadata = Readonly<Record<string, string>>;

export type CloudTransfer_EnqueueUploadRequest = Readonly<{
  contentType?: string;
  localPath: string;
  metadata?: Record<string, string>;
  requestId?: string;
  remotePath: string;
  scope?: 'device' | 'package';
  timeout?: string;
}>;

export type CloudTransfer_EnqueueUploadRequestMetadata = Readonly<Record<string, string>>;

export type CloudTransfer_EnqueueDownloadRequest = Readonly<{
  localPath: string;
  metadata?: Record<string, string>;
  requestId?: string;
  remotePath: string;
  scope?: 'device' | 'package';
  timeout?: string;
}>;

export type CloudTransfer_EnqueueDownloadRequestMetadata = Readonly<Record<string, string>>;

export type CloudTransfer_GetTransferRequest = Readonly<{
  requestId?: string;
  transferId: string;
}>;

export type CloudTransfer_ListTransfersRequest = Readonly<{
  direction?: 'download' | 'upload';
  limit?: number;
  requestId?: string;
  state?: 'completed' | 'failed' | 'queued' | 'retry_wait' | 'running';
}>;

export type CloudTransfer_StatsRequest = Readonly<{
  requestId?: string;
}>;

export type CloudTransfer_TransferPayload = Readonly<{
  requestId?: string;
  transfer: CloudTransfer_Transfer;
}>;

export type CloudTransferTransfer = Readonly<{
  attempts: number;
  completedAt?: string;
  contentType?: string;
  createdAt: string;
  deadlineAt?: string;
  deviceId: string;
  direction: 'download' | 'upload';
  id: string;
  lastError?: string;
  localPath: string;
  metadata?: Record<string, string>;
  nextAttemptAt?: string;
  objectKey?: string;
  remotePath: string;
  scope?: 'device' | 'package';
  startedAt?: string;
  state: 'completed' | 'failed' | 'queued' | 'retry_wait' | 'running';
  updatedAt: string;
}>;

export type CloudTransferTransferMetadata = Readonly<Record<string, string>>;

export type CloudTransfer_TransferListPayload = Readonly<{
  items: Array<CloudTransfer_Transfer>;
  requestId?: string;
}>;

export type CloudTransfer_TransferStatsPayload = Readonly<{
  requestId?: string;
  stats: CloudTransfer_QueueStats;
}>;

export type CloudTransferQueueStats = Readonly<{
  completed: number;
  downloadQueued: number;
  downloadsCompleted: number;
  downloadsFailed: number;
  failed: number;
  nextAttemptAt?: string;
  pending: number;
  running: number;
  total: number;
  uploadQueued: number;
  uploadsCompleted: number;
  uploadsFailed: number;
}>;

export type CloudTransfer_TransferStatusPayload = Readonly<{
  databasePath: string;
  deviceId: string;
  requestId?: string;
  sharedDir: string;
  stats: CloudTransfer_QueueStats;
}>;

export type CloudTransfer_TransferErrorPayload = Readonly<{
  error: string;
  requestId?: string;
  requestType?: string;
}>;

export type CloudTransfer_Transfer_Message = CloudTransfer_TransferPayload;
export type CloudTransfer_List_Message = CloudTransfer_TransferListPayload;
export type CloudTransfer_Stats_Message = CloudTransfer_TransferStatsPayload;
export type CloudTransfer_Status_Message = CloudTransfer_TransferStatusPayload;
export type CloudTransfer_Error_Message = CloudTransfer_TransferErrorPayload;

export type CloudTransfer_EnqueueUpload_Input = CloudTransfer_EnqueueUploadRequest;
export type CloudTransfer_EnqueueUpload_Output = CloudTransfer_TransferPayload;
export type CloudTransfer_EnqueueUpload_Error = CloudTransfer_TransferErrorPayload;
export type CloudTransfer_EnqueueDownload_Input = CloudTransfer_EnqueueDownloadRequest;
export type CloudTransfer_EnqueueDownload_Output = CloudTransfer_TransferPayload;
export type CloudTransfer_EnqueueDownload_Error = CloudTransfer_TransferErrorPayload;
export type CloudTransfer_GetTransfer_Input = CloudTransfer_GetTransferRequest;
export type CloudTransfer_GetTransfer_Output = CloudTransfer_TransferPayload;
export type CloudTransfer_GetTransfer_Error = CloudTransfer_TransferErrorPayload;
export type CloudTransfer_ListTransfers_Input = CloudTransfer_ListTransfersRequest;
export type CloudTransfer_ListTransfers_Output = CloudTransfer_TransferListPayload;
export type CloudTransfer_ListTransfers_Error = CloudTransfer_TransferErrorPayload;
export type CloudTransfer_GetStats_Input = CloudTransfer_StatsRequest;
export type CloudTransfer_GetStats_Output = CloudTransfer_TransferStatsPayload;
export type CloudTransfer_GetStats_Error = CloudTransfer_TransferErrorPayload;
export type CloudTransfer_GetStatus_Input = CloudTransfer_StatsRequest;
export type CloudTransfer_GetStatus_Output = CloudTransfer_TransferStatusPayload;
export type CloudTransfer_GetStatus_Error = CloudTransfer_TransferErrorPayload;

export const cloud_transferContract = defineServiceContract({
  name: CLOUD_TRANSFER_SERVICE,
  methods: {
    'enqueue-upload': defineServiceContractMethod<
      CloudTransfer_EnqueueUpload_Input,
      readonly [
        ServiceContractOutput<
          CloudTransfer_TransferPayload,
          'success',
          typeof CLOUD_TRANSFER_TRANSFER_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          CloudTransfer_TransferPayload,
          'success',
          typeof CLOUD_TRANSFER_TRANSFER_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: CLOUD_TRANSFER_TRANSFER_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: CLOUD_TRANSFER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: CLOUD_TRANSFER_ENQUEUE_UPLOAD_SUBTOPIC,
    }),
    'enqueue-download': defineServiceContractMethod<
      CloudTransfer_EnqueueDownload_Input,
      readonly [
        ServiceContractOutput<
          CloudTransfer_TransferPayload,
          'success',
          typeof CLOUD_TRANSFER_TRANSFER_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          CloudTransfer_TransferPayload,
          'success',
          typeof CLOUD_TRANSFER_TRANSFER_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: CLOUD_TRANSFER_TRANSFER_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: CLOUD_TRANSFER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: CLOUD_TRANSFER_ENQUEUE_DOWNLOAD_SUBTOPIC,
    }),
    'get-transfer': defineServiceContractMethod<
      CloudTransfer_GetTransfer_Input,
      readonly [
        ServiceContractOutput<
          CloudTransfer_TransferPayload,
          'success',
          typeof CLOUD_TRANSFER_TRANSFER_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          CloudTransfer_TransferPayload,
          'success',
          typeof CLOUD_TRANSFER_TRANSFER_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: CLOUD_TRANSFER_TRANSFER_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: CLOUD_TRANSFER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: CLOUD_TRANSFER_GET_TRANSFER_SUBTOPIC,
    }),
    'list-transfers': defineServiceContractMethod<
      CloudTransfer_ListTransfers_Input,
      readonly [
        ServiceContractOutput<
          CloudTransfer_TransferListPayload,
          'success',
          typeof CLOUD_TRANSFER_LIST_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          CloudTransfer_TransferListPayload,
          'success',
          typeof CLOUD_TRANSFER_LIST_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: CLOUD_TRANSFER_LIST_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: CLOUD_TRANSFER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: CLOUD_TRANSFER_LIST_TRANSFERS_SUBTOPIC,
    }),
    'get-stats': defineServiceContractMethod<
      CloudTransfer_GetStats_Input,
      readonly [
        ServiceContractOutput<
          CloudTransfer_TransferStatsPayload,
          'success',
          typeof CLOUD_TRANSFER_STATS_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          CloudTransfer_TransferStatsPayload,
          'success',
          typeof CLOUD_TRANSFER_STATS_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: CLOUD_TRANSFER_STATS_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: CLOUD_TRANSFER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: CLOUD_TRANSFER_GET_STATS_SUBTOPIC,
    }),
    'get-status': defineServiceContractMethod<
      CloudTransfer_GetStatus_Input,
      readonly [
        ServiceContractOutput<
          CloudTransfer_TransferStatusPayload,
          'success',
          typeof CLOUD_TRANSFER_STATUS_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          CloudTransfer_TransferStatusPayload,
          'success',
          typeof CLOUD_TRANSFER_STATUS_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: CLOUD_TRANSFER_STATUS_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          CloudTransfer_TransferErrorPayload,
          'error',
          typeof CLOUD_TRANSFER_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: CLOUD_TRANSFER_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: CLOUD_TRANSFER_GET_STATUS_SUBTOPIC,
    }),
  },
});

export type CloudTransferContract = typeof cloud_transferContract;
