// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
'use client';

import {
  defineServiceContract,
  defineServiceContractMethod,
  defineServiceContractOutput,
  type ServiceContractOutput,
} from '../lib/service-contract-runtime';

export const PTZ_CONTROL_SERVICE = 'ptz-control';
export const PTZ_CONTROL_GET_STATUS_METHOD = 'get-status';
export const PTZ_CONTROL_GET_STATUS_SUBTOPIC = 'command';
export const PTZ_CONTROL_GET_POSITION_METHOD = 'get-position';
export const PTZ_CONTROL_GET_POSITION_SUBTOPIC = 'command';
export const PTZ_CONTROL_START_MOVE_METHOD = 'start-move';
export const PTZ_CONTROL_START_MOVE_SUBTOPIC = 'command';
export const PTZ_CONTROL_STOP_MOVE_METHOD = 'stop-move';
export const PTZ_CONTROL_STOP_MOVE_SUBTOPIC = 'command';
export const PTZ_CONTROL_SET_ZOOM_METHOD = 'set-zoom';
export const PTZ_CONTROL_SET_ZOOM_SUBTOPIC = 'command';
export const PTZ_CONTROL_SET_POSITION_METHOD = 'set-position';
export const PTZ_CONTROL_SET_POSITION_SUBTOPIC = 'command';
export const PTZ_CONTROL_GO_HOME_METHOD = 'go-home';
export const PTZ_CONTROL_GO_HOME_SUBTOPIC = 'command';
export const PTZ_CONTROL_PTZ_STATUS_MESSAGE = 'ptz-status';
export const PTZ_CONTROL_PTZ_POSITION_MESSAGE = 'ptz-position';
export const PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE = 'ptz-command-ack';
export const PTZ_CONTROL_PTZ_ERROR_MESSAGE = 'ptz-error';

export type PtzControl_PtzRange = Readonly<{
  max: number;
  min: number;
}>;

export type PtzControl_MoveStatus = Readonly<{
  panTilt?: string;
  zoom?: string;
}>;

export type PtzControl_PtzCapabilities = Readonly<{
  canAbsolutePanTilt: boolean;
  canAbsoluteZoom: boolean;
  canContinuousPanTilt: boolean;
  canContinuousZoom: boolean;
  canGoHome: boolean;
  panRange?: PtzControl_PtzRange;
  tiltRange?: PtzControl_PtzRange;
  zoomRange?: PtzControl_PtzRange;
}>;

export type PtzControlPtzRange = Readonly<{
  max: number;
  min: number;
}>;

export type PtzControl_PositionSnapshot = Readonly<{
  capabilities?: PtzControl_PtzCapabilities;
  cameraName: string;
  moveStatus?: PtzControl_MoveStatus;
  pan: number;
  tilt: number;
  updatedAt: string;
  zoom: number;
}>;

export type PtzControlPtzCapabilities = Readonly<{
  canAbsolutePanTilt: boolean;
  canAbsoluteZoom: boolean;
  canContinuousPanTilt: boolean;
  canContinuousZoom: boolean;
  canGoHome: boolean;
  panRange?: PtzControl_PtzRange;
  tiltRange?: PtzControl_PtzRange;
  zoomRange?: PtzControl_PtzRange;
}>;

export type PtzControlMoveStatus = Readonly<{
  panTilt?: string;
  zoom?: string;
}>;

export type PtzControl_VelocityCommand = Readonly<{
  pan: number;
  tilt: number;
  zoom: number;
}>;

export type PtzControl_StatusPayload = Readonly<{
  activeCamera?: string;
  capabilities?: PtzControl_PtzCapabilities;
  configuredCameras: Array<string>;
  lastCommand?: string;
  lastError?: string;
  position?: PtzControl_PositionSnapshot;
}>;

export type PtzControlPositionSnapshot = Readonly<{
  capabilities?: PtzControl_PtzCapabilities;
  cameraName: string;
  moveStatus?: PtzControl_MoveStatus;
  pan: number;
  tilt: number;
  updatedAt: string;
  zoom: number;
}>;

export type PtzControl_StatusResponsePayload = Readonly<{
  activeCamera?: string;
  capabilities?: PtzControl_PtzCapabilities;
  configuredCameras: Array<string>;
  lastCommand?: string;
  lastError?: string;
  position?: PtzControl_PositionSnapshot;
  requestId?: string;
}>;

export type PtzControl_CommandAckPayload = Readonly<{
  capabilities?: PtzControl_PtzCapabilities;
  cameraName: string;
  command: string;
  ok: boolean;
  position?: PtzControl_PositionSnapshot;
  requestId?: string;
  velocity?: PtzControl_VelocityCommand;
}>;

export type PtzControlVelocityCommand = Readonly<{
  pan: number;
  tilt: number;
  zoom: number;
}>;

export type PtzControl_PositionResponsePayload = Readonly<{
  capabilities?: PtzControl_PtzCapabilities;
  cameraName: string;
  moveStatus?: PtzControl_MoveStatus;
  pan: number;
  requestId?: string;
  tilt: number;
  updatedAt: string;
  zoom: number;
}>;

export type PtzControl_ErrorPayload = Readonly<{
  cameraName?: string;
  command: string;
  error: string;
  requestId?: string;
}>;

export type PtzControl_CameraCommand = Readonly<{
  cameraName?: string;
  requestId?: string;
}>;

export type PtzControl_MoveCommand = Readonly<{
  cameraName: string;
  requestId?: string;
  velocity: PtzControl_VelocityCommand;
}>;

export type PtzControl_ZoomCommand = Readonly<{
  cameraName: string;
  requestId?: string;
  zoom: number;
}>;

export type PtzControl_PositionCommand = Readonly<{
  cameraName: string;
  pan: number;
  requestId?: string;
  tilt: number;
  zoom: number;
}>;

export type PtzControl_PtzStatus_Message = PtzControl_StatusResponsePayload;
export type PtzControl_PtzPosition_Message = PtzControl_PositionResponsePayload;
export type PtzControl_PtzCommandAck_Message = PtzControl_CommandAckPayload;
export type PtzControl_PtzError_Message = PtzControl_ErrorPayload;

export type PtzControl_GetStatus_Input = PtzControl_CameraCommand;
export type PtzControl_GetStatus_Output = PtzControl_StatusResponsePayload;
export type PtzControl_GetStatus_Error = PtzControl_ErrorPayload;
export type PtzControl_GetPosition_Input = PtzControl_CameraCommand;
export type PtzControl_GetPosition_Output = PtzControl_PositionResponsePayload;
export type PtzControl_GetPosition_Error = PtzControl_ErrorPayload;
export type PtzControl_StartMove_Input = PtzControl_MoveCommand;
export type PtzControl_StartMove_Output = PtzControl_CommandAckPayload;
export type PtzControl_StartMove_Error = PtzControl_ErrorPayload;
export type PtzControl_StopMove_Input = PtzControl_CameraCommand;
export type PtzControl_StopMove_Output = PtzControl_CommandAckPayload;
export type PtzControl_StopMove_Error = PtzControl_ErrorPayload;
export type PtzControl_SetZoom_Input = PtzControl_ZoomCommand;
export type PtzControl_SetZoom_Output = PtzControl_CommandAckPayload;
export type PtzControl_SetZoom_Error = PtzControl_ErrorPayload;
export type PtzControl_SetPosition_Input = PtzControl_PositionCommand;
export type PtzControl_SetPosition_Output = PtzControl_CommandAckPayload;
export type PtzControl_SetPosition_Error = PtzControl_ErrorPayload;
export type PtzControl_GoHome_Input = PtzControl_CameraCommand;
export type PtzControl_GoHome_Output = PtzControl_CommandAckPayload;
export type PtzControl_GoHome_Error = PtzControl_ErrorPayload;

export const ptz_controlContract = defineServiceContract({
  name: PTZ_CONTROL_SERVICE,
  methods: {
    'get-status': defineServiceContractMethod<
      PtzControl_GetStatus_Input,
      readonly [
        ServiceContractOutput<
          PtzControl_StatusResponsePayload,
          'success',
          typeof PTZ_CONTROL_PTZ_STATUS_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          PtzControl_StatusResponsePayload,
          'success',
          typeof PTZ_CONTROL_PTZ_STATUS_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: PTZ_CONTROL_PTZ_STATUS_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: PTZ_CONTROL_GET_STATUS_SUBTOPIC,
    }),
    'get-position': defineServiceContractMethod<
      PtzControl_GetPosition_Input,
      readonly [
        ServiceContractOutput<
          PtzControl_PositionResponsePayload,
          'success',
          typeof PTZ_CONTROL_PTZ_POSITION_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          PtzControl_PositionResponsePayload,
          'success',
          typeof PTZ_CONTROL_PTZ_POSITION_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: PTZ_CONTROL_PTZ_POSITION_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: PTZ_CONTROL_GET_POSITION_SUBTOPIC,
    }),
    'start-move': defineServiceContractMethod<
      PtzControl_StartMove_Input,
      readonly [
        ServiceContractOutput<
          PtzControl_CommandAckPayload,
          'success',
          typeof PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          PtzControl_CommandAckPayload,
          'success',
          typeof PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: PTZ_CONTROL_START_MOVE_SUBTOPIC,
    }),
    'stop-move': defineServiceContractMethod<
      PtzControl_StopMove_Input,
      readonly [
        ServiceContractOutput<
          PtzControl_CommandAckPayload,
          'success',
          typeof PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          PtzControl_CommandAckPayload,
          'success',
          typeof PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: PTZ_CONTROL_STOP_MOVE_SUBTOPIC,
    }),
    'set-zoom': defineServiceContractMethod<
      PtzControl_SetZoom_Input,
      readonly [
        ServiceContractOutput<
          PtzControl_CommandAckPayload,
          'success',
          typeof PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          PtzControl_CommandAckPayload,
          'success',
          typeof PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: PTZ_CONTROL_SET_ZOOM_SUBTOPIC,
    }),
    'set-position': defineServiceContractMethod<
      PtzControl_SetPosition_Input,
      readonly [
        ServiceContractOutput<
          PtzControl_CommandAckPayload,
          'success',
          typeof PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          PtzControl_CommandAckPayload,
          'success',
          typeof PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: PTZ_CONTROL_SET_POSITION_SUBTOPIC,
    }),
    'go-home': defineServiceContractMethod<
      PtzControl_GoHome_Input,
      readonly [
        ServiceContractOutput<
          PtzControl_CommandAckPayload,
          'success',
          typeof PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          PtzControl_CommandAckPayload,
          'success',
          typeof PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: PTZ_CONTROL_PTZ_COMMAND_ACK_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          PtzControl_ErrorPayload,
          'error',
          typeof PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: PTZ_CONTROL_PTZ_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: PTZ_CONTROL_GO_HOME_SUBTOPIC,
    }),
  },
});

export type PtzControlContract = typeof ptz_controlContract;
