// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
'use client';

import {
  defineServiceContract,
  defineServiceContractMethod,
  defineServiceContractOutput,
  type ServiceContractOutput,
} from '../lib/service-contract-runtime';

export const ROI_CONFIG_SERVICE = 'roi-config';
export const ROI_CONFIG_GET_STATUS_METHOD = 'get-status';
export const ROI_CONFIG_GET_STATUS_SUBTOPIC = 'command';
export const ROI_CONFIG_GET_CONFIG_METHOD = 'get-config';
export const ROI_CONFIG_GET_CONFIG_SUBTOPIC = 'command';
export const ROI_CONFIG_SAVE_CONFIG_METHOD = 'save-config';
export const ROI_CONFIG_SAVE_CONFIG_SUBTOPIC = 'command';
export const ROI_CONFIG_STATUS_MESSAGE = 'roi-config-status';
export const ROI_CONFIG_DOCUMENT_MESSAGE = 'roi-config-document';
export const ROI_CONFIG_ERROR_MESSAGE = 'roi-config-error';

export type RoiConfig_RequestEnvelope = Readonly<{
  requestId?: string;
}>;

export type RoiConfig_ROIBox = Readonly<{
  height: number;
  width: number;
  x: number;
  y: number;
}>;

export type RoiConfig_PTZPosition = Readonly<{
  pan: number;
  tilt: number;
  zoom: number;
}>;

export type RoiConfig_ROIBoxSpec = Readonly<{
  active: boolean;
  bounds: RoiConfig_ROIBox;
  color?: string;
  id: string;
  name: string;
  tags?: Array<string>;
}>;

export type RoiConfigROIBox = Readonly<{
  height: number;
  width: number;
  x: number;
  y: number;
}>;

export type RoiConfig_BaseLocation = Readonly<{
  active: boolean;
  id: string;
  name: string;
  ptz: RoiConfig_PTZPosition;
  rois: Array<RoiConfig_ROIBoxSpec>;
}>;

export type RoiConfigPTZPosition = Readonly<{
  pan: number;
  tilt: number;
  zoom: number;
}>;

export type RoiConfigROIBoxSpec = Readonly<{
  active: boolean;
  bounds: RoiConfig_ROIBox;
  color?: string;
  id: string;
  name: string;
  tags?: Array<string>;
}>;

export type RoiConfig_CameraROIConfig = Readonly<{
  baseLocations: Array<RoiConfig_BaseLocation>;
  cameraName: string;
}>;

export type RoiConfigBaseLocation = Readonly<{
  active: boolean;
  id: string;
  name: string;
  ptz: RoiConfig_PTZPosition;
  rois: Array<RoiConfig_ROIBoxSpec>;
}>;

export type RoiConfig_Document = Readonly<{
  cameras: Array<RoiConfig_CameraROIConfig>;
  updatedAt?: string;
  version: number;
}>;

export type RoiConfigCameraROIConfig = Readonly<{
  baseLocations: Array<RoiConfig_BaseLocation>;
  cameraName: string;
}>;

export type RoiConfig_StatusPayload = Readonly<{
  baseLocationCount: number;
  cameraCount: number;
  documentHash: string;
  filePath: string;
  roiBoxCount: number;
  updatedAt?: string;
}>;

export type RoiConfig_StatusResponsePayload = Readonly<{
  requestId?: string;
  baseLocationCount: number;
  cameraCount: number;
  documentHash: string;
  filePath: string;
  roiBoxCount: number;
  updatedAt?: string;
}>;

export type RoiConfig_GetConfigPayload = Readonly<{
  document: RoiConfig_Document;
  filePath: string;
  requestId?: string;
  baseLocationCount: number;
  cameraCount: number;
  documentHash: string;
  roiBoxCount: number;
  updatedAt?: string;
}>;

export type RoiConfigDocument = Readonly<{
  cameras: Array<RoiConfig_CameraROIConfig>;
  updatedAt?: string;
  version: number;
}>;

export type RoiConfig_SaveConfigRequest = Readonly<{
  document: RoiConfig_Document;
  requestId?: string;
}>;

export type RoiConfig_ErrorPayload = Readonly<{
  error: string;
  requestId?: string;
  requestType?: string;
}>;

export type RoiConfig_Status_Message = RoiConfig_StatusResponsePayload;
export type RoiConfig_Document_Message = RoiConfig_GetConfigPayload;
export type RoiConfig_Error_Message = RoiConfig_ErrorPayload;

export type RoiConfig_GetStatus_Input = RoiConfig_RequestEnvelope;
export type RoiConfig_GetStatus_Output = RoiConfig_StatusResponsePayload;
export type RoiConfig_GetStatus_Error = RoiConfig_ErrorPayload;
export type RoiConfig_GetConfig_Input = RoiConfig_RequestEnvelope;
export type RoiConfig_GetConfig_Output = RoiConfig_GetConfigPayload;
export type RoiConfig_GetConfig_Error = RoiConfig_ErrorPayload;
export type RoiConfig_SaveConfig_Input = RoiConfig_SaveConfigRequest;
export type RoiConfig_SaveConfig_Output = RoiConfig_GetConfigPayload;
export type RoiConfig_SaveConfig_Error = RoiConfig_ErrorPayload;

export const roi_configContract = defineServiceContract({
  name: ROI_CONFIG_SERVICE,
  methods: {
    'get-status': defineServiceContractMethod<
      RoiConfig_GetStatus_Input,
      readonly [
        ServiceContractOutput<
          RoiConfig_StatusResponsePayload,
          'success',
          typeof ROI_CONFIG_STATUS_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RoiConfig_ErrorPayload,
          'error',
          typeof ROI_CONFIG_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RoiConfig_StatusResponsePayload,
          'success',
          typeof ROI_CONFIG_STATUS_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: ROI_CONFIG_STATUS_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RoiConfig_ErrorPayload,
          'error',
          typeof ROI_CONFIG_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: ROI_CONFIG_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: ROI_CONFIG_GET_STATUS_SUBTOPIC,
    }),
    'get-config': defineServiceContractMethod<
      RoiConfig_GetConfig_Input,
      readonly [
        ServiceContractOutput<
          RoiConfig_GetConfigPayload,
          'success',
          typeof ROI_CONFIG_DOCUMENT_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RoiConfig_ErrorPayload,
          'error',
          typeof ROI_CONFIG_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RoiConfig_GetConfigPayload,
          'success',
          typeof ROI_CONFIG_DOCUMENT_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: ROI_CONFIG_DOCUMENT_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RoiConfig_ErrorPayload,
          'error',
          typeof ROI_CONFIG_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: ROI_CONFIG_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: ROI_CONFIG_GET_CONFIG_SUBTOPIC,
    }),
    'save-config': defineServiceContractMethod<
      RoiConfig_SaveConfig_Input,
      readonly [
        ServiceContractOutput<
          RoiConfig_GetConfigPayload,
          'success',
          typeof ROI_CONFIG_DOCUMENT_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          RoiConfig_ErrorPayload,
          'error',
          typeof ROI_CONFIG_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          RoiConfig_GetConfigPayload,
          'success',
          typeof ROI_CONFIG_DOCUMENT_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: ROI_CONFIG_DOCUMENT_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          RoiConfig_ErrorPayload,
          'error',
          typeof ROI_CONFIG_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: ROI_CONFIG_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: ROI_CONFIG_SAVE_CONFIG_SUBTOPIC,
    }),
  },
});

export type RoiConfigContract = typeof roi_configContract;
