// Code generated by `python -m device.devtool contract codegen`. DO NOT EDIT.
'use client';

import {
  defineServiceContract,
  defineServiceContractMethod,
  defineServiceContractOutput,
  type ServiceContractOutput,
} from '../lib/service-contract-runtime';

export const WORKFLOW_ENGINE_SERVICE = 'workflow-engine';
export const WORKFLOW_ENGINE_ENQUEUE_DETECTION_METHOD = 'enqueue-detection';
export const WORKFLOW_ENGINE_ENQUEUE_DETECTION_SUBTOPIC = 'command';
export const WORKFLOW_ENGINE_GET_STATUS_METHOD = 'get-status';
export const WORKFLOW_ENGINE_GET_STATUS_SUBTOPIC = 'command';
export const WORKFLOW_ENGINE_RESULT_MESSAGE = 'workflow-engine-result';
export const WORKFLOW_ENGINE_STATUS_MESSAGE = 'workflow-engine-status';
export const WORKFLOW_ENGINE_ERROR_MESSAGE = 'workflow-engine-error';

export type WorkflowEngine_Detection = Readonly<{
  bbox?: Array<number>;
  class_name?: string;
  conf?: number;
  confidence?: number;
  detections?: Array<WorkflowEngine_Detection>;
  label?: string;
  raw_bboxes?: Array<number>;
  x1?: number;
  x2?: number;
  xyxy?: Array<number>;
  y1?: number;
  y2?: number;
}>;

export type WorkflowEngineDetection = Readonly<{
  bbox?: Array<number>;
  class_name?: string;
  conf?: number;
  confidence?: number;
  detections?: Array<WorkflowEngine_Detection>;
  label?: string;
  raw_bboxes?: Array<number>;
  x1?: number;
  x2?: number;
  xyxy?: Array<number>;
  y1?: number;
  y2?: number;
}>;

export type WorkflowEngine_WorkflowPayload = Readonly<{
  DetectionPerClass?: Record<string, number>;
  bbox?: Array<WorkflowEngine_Detection>;
  cam_id?: string;
  cam_name?: string;
  cameraId?: string;
  cameraName?: string;
  frame_id?: string;
  imageId?: string;
  imgID?: string;
}>;

export type WorkflowEngine_WorkflowPayloadDetectionPerClass = Readonly<Record<string, number>>;

export type WorkflowEngine_EnqueueDetectionRequest = Readonly<{
  DetectionPerClass?: Record<string, number>;
  bbox?: Array<WorkflowEngine_Detection>;
  cameraId?: string;
  cameraName?: string;
  detectionData?: WorkflowEngine_WorkflowPayload;
  detections?: Array<WorkflowEngine_Detection>;
  frameId?: string;
  imageId?: string;
  imgID?: string;
  requestId?: string;
}>;

export type WorkflowEngine_EnqueueDetectionRequestDetectionPerClass = Readonly<
  Record<string, number>
>;

export type WorkflowEngineWorkflowPayload = Readonly<{
  DetectionPerClass?: Record<string, number>;
  bbox?: Array<WorkflowEngine_Detection>;
  cam_id?: string;
  cam_name?: string;
  cameraId?: string;
  cameraName?: string;
  frame_id?: string;
  imageId?: string;
  imgID?: string;
}>;

export type WorkflowEngineWorkflowPayloadDetectionPerClass = Readonly<Record<string, number>>;

export type WorkflowEngine_NodeResult = Readonly<{
  durationMs: number;
  error: string;
  outputs: Record<string, unknown>;
  status: string;
}>;

export type WorkflowEngine_NodeResultOutputs = Readonly<Record<string, unknown>>;

export type WorkflowEngine_WorkflowRun = Readonly<{
  cameraId: string;
  cameraName: string;
  durationMs: number;
  errors: Array<string>;
  executionId: string;
  frameId: string;
  nodeResults: Record<string, WorkflowEngine_NodeResult>;
  outputs: Record<string, unknown>;
  success: boolean;
  workflowGeneration: number;
  workflowHash: string;
}>;

export type WorkflowEngine_WorkflowRunNodeResults = Readonly<
  Record<string, WorkflowEngine_NodeResult>
>;

export type WorkflowEngineNodeResult = Readonly<{
  durationMs: number;
  error: string;
  outputs: Record<string, unknown>;
  status: string;
}>;

export type WorkflowEngineNodeResultOutputs = Readonly<Record<string, unknown>>;

export type WorkflowEngine_WorkflowRunOutputs = Readonly<Record<string, unknown>>;

export type WorkflowEngine_WorkflowResultPayload = Readonly<{
  requestId: string;
  run: WorkflowEngine_WorkflowRun;
}>;

export type WorkflowEngineWorkflowRun = Readonly<{
  cameraId: string;
  cameraName: string;
  durationMs: number;
  errors: Array<string>;
  executionId: string;
  frameId: string;
  nodeResults: Record<string, WorkflowEngine_NodeResult>;
  outputs: Record<string, unknown>;
  success: boolean;
  workflowGeneration: number;
  workflowHash: string;
}>;

export type WorkflowEngineWorkflowRunNodeResults = Readonly<
  Record<string, WorkflowEngine_NodeResult>
>;

export type WorkflowEngineWorkflowRunOutputs = Readonly<Record<string, unknown>>;

export type WorkflowEngine_WorkflowStatusState = Readonly<{
  error: string;
  filePath: string;
  generation: number;
  hash: string;
  loaded: boolean;
  loadedAt: string;
  name: string;
}>;

export type WorkflowEngine_WorkflowQueueState = Readonly<{
  activeRequestId: string;
  maxPending: number;
  pending: number;
}>;

export type WorkflowEngine_WorkflowStats = Readonly<{
  droppedRuns: number;
  failedRuns: number;
  processedRuns: number;
  reloadCount: number;
}>;

export type WorkflowEngine_WorkflowStatusPayload = Readonly<{
  deviceId: string;
  queue: WorkflowEngine_WorkflowQueueState;
  recentRuns: Array<WorkflowEngine_WorkflowRun>;
  requestId: string;
  service: string;
  stats: WorkflowEngine_WorkflowStats;
  workflow: WorkflowEngine_WorkflowStatusState;
}>;

export type WorkflowEngineWorkflowQueueState = Readonly<{
  activeRequestId: string;
  maxPending: number;
  pending: number;
}>;

export type WorkflowEngineWorkflowStats = Readonly<{
  droppedRuns: number;
  failedRuns: number;
  processedRuns: number;
  reloadCount: number;
}>;

export type WorkflowEngineWorkflowStatusState = Readonly<{
  error: string;
  filePath: string;
  generation: number;
  hash: string;
  loaded: boolean;
  loadedAt: string;
  name: string;
}>;

export type WorkflowEngine_WorkflowErrorPayload = Readonly<{
  error: string;
  requestId?: string;
  requestType?: string;
}>;

export type WorkflowEngine_StatusRequest = Readonly<{
  requestId?: string;
}>;

export type WorkflowEngine_Result_Message = WorkflowEngine_WorkflowResultPayload;
export type WorkflowEngine_Status_Message = WorkflowEngine_WorkflowStatusPayload;
export type WorkflowEngine_Error_Message = WorkflowEngine_WorkflowErrorPayload;

export type WorkflowEngine_EnqueueDetection_Input = WorkflowEngine_EnqueueDetectionRequest;
export type WorkflowEngine_EnqueueDetection_Output = WorkflowEngine_WorkflowResultPayload;
export type WorkflowEngine_EnqueueDetection_Error = WorkflowEngine_WorkflowErrorPayload;
export type WorkflowEngine_GetStatus_Input = WorkflowEngine_StatusRequest;
export type WorkflowEngine_GetStatus_Output = WorkflowEngine_WorkflowStatusPayload;
export type WorkflowEngine_GetStatus_Error = never;

export const workflow_engineContract = defineServiceContract({
  name: WORKFLOW_ENGINE_SERVICE,
  methods: {
    'enqueue-detection': defineServiceContractMethod<
      WorkflowEngine_EnqueueDetection_Input,
      readonly [
        ServiceContractOutput<
          WorkflowEngine_WorkflowResultPayload,
          'success',
          typeof WORKFLOW_ENGINE_RESULT_MESSAGE,
          'response'
        >,
        ServiceContractOutput<
          WorkflowEngine_WorkflowErrorPayload,
          'error',
          typeof WORKFLOW_ENGINE_ERROR_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          WorkflowEngine_WorkflowResultPayload,
          'success',
          typeof WORKFLOW_ENGINE_RESULT_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: WORKFLOW_ENGINE_RESULT_MESSAGE,
          subtopic: 'response',
        }),
        defineServiceContractOutput<
          WorkflowEngine_WorkflowErrorPayload,
          'error',
          typeof WORKFLOW_ENGINE_ERROR_MESSAGE,
          'response'
        >({
          kind: 'error',
          messageType: WORKFLOW_ENGINE_ERROR_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: WORKFLOW_ENGINE_ENQUEUE_DETECTION_SUBTOPIC,
    }),
    'get-status': defineServiceContractMethod<
      WorkflowEngine_GetStatus_Input,
      readonly [
        ServiceContractOutput<
          WorkflowEngine_WorkflowStatusPayload,
          'success',
          typeof WORKFLOW_ENGINE_STATUS_MESSAGE,
          'response'
        >,
      ]
    >({
      outputs: [
        defineServiceContractOutput<
          WorkflowEngine_WorkflowStatusPayload,
          'success',
          typeof WORKFLOW_ENGINE_STATUS_MESSAGE,
          'response'
        >({
          kind: 'success',
          messageType: WORKFLOW_ENGINE_STATUS_MESSAGE,
          subtopic: 'response',
        }),
      ] as const,
      subtopic: WORKFLOW_ENGINE_GET_STATUS_SUBTOPIC,
    }),
  },
});

export type WorkflowEngineContract = typeof workflow_engineContract;
